// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type Number = number;
export type Array = Object[];

export interface CONTRACT_AUTHORIZEInput {
  clauses: Array;
}
export interface Object {
  clauseId: String;
  amount: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type String_2 = string;
export type Number_1 = number;

export interface CONTRACT_AUTHORIZEOutput {
  transactionId: String_1;
  totalAmount: String_2;
  timestamp: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CONTRACT_GETInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type StringNumber = String_6 | Number_2;
export type String_6 = string;
export type Number_2 = number;
export type String_7 = string;
export type String_8 = string;
export type Array_2 = String_8[];
export type Array_1 = Object_2[];

export interface CONTRACT_GETOutput {
  appName?: String_3;
  contract: Object_1;
}
export interface Object_1 {
  body?: String_4;
  clauses?: Array_1;
}
export interface Object_2 {
  id: String_5;
  price: StringNumber;
  description?: String_7;
  usedByTools?: Array_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_9 = string;
export type String_10 = string;
export type Number_3 = number;
export type Array_3 = Object_3[];
export type Number_4 = number;
export type String_11 = string;

export interface CONTRACT_SETTLEInput {
  transactionId: String_9;
  clauses?: Array_3;
  amount?: Number_4;
  vendorId: String_11;
}
export interface Object_3 {
  clauseId: String_10;
  amount: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_12 = string;

export interface CONTRACT_SETTLEOutput {
  transactionId: String_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_13 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_14 = string;
export type Array_4 = String_14[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_15 = string;

export interface FS_DELETEInput {
  path: String_15;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_DELETEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The root directory to list files from
 */
export type String_16 = string;

export interface FS_LISTInput {
  prefix: String_16;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Array_5 = unknown[];

export interface FS_LISTOutput {
  items: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_17 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number_5 = number;

export interface FS_READInput {
  path: String_17;
  expiresIn?: Number_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to read the file from
 */
export type String_18 = string;

export interface FS_READOutput {
  url: String_18;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_19 = string;

export interface FS_READ_METADATAInput {
  path: String_19;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_READ_METADATAOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_20 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number_6 = number;
/**
 * Content-Type for the file. This is required.
 */
export type String_21 = string;

export interface FS_WRITEInput {
  path: String_20;
  expiresIn?: Number_6;
  contentType: String_21;
  metadata?: Object_4;
}
/**
 * Metadata to be added to the file
 */
export interface Object_4 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to upload the file to
 */
export type String_22 = string;

export interface FS_WRITEOutput {
  url: String_22;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_23 = string;

export interface DECO_CHAT_OAUTH_STARTInput_1 {
  returnUrl: String_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_24 = string;
export type Array_6 = String_24[];

export interface DECO_CHAT_OAUTH_STARTOutput_1 {
  stateSchema?: unknown;
  scopes?: Array_6;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_25 = string;
export type String_26 = string;
export type String_27 = string;
export type String_28 = string;
export type String_29 = string;
export type String_30 = string;
export type String_31 = string;
export type String_32 = string;
export type String_33 = string;
export type Array_8 = String_33[];
export type String_34 = string;
export type String_35 = "none" | "open" | "autoPin";
export type Array_7 = Object_5[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_7;
}
export interface Object_5 {
  id?: String_25;
  name?: String_26;
  title: String_27;
  description?: String_28;
  icon: String_29;
  url?: String_30;
  mimeTypePattern?: String_31;
  resourceName?: String_32;
  tools?: Array_8;
  prompt?: String_34;
  installBehavior?: String_35;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The text prompt describing the image to generate
 */
export type String_36 = string;
/**
 * URL of an existing image to use as base (image-to-image generation)
 */
export type StringNull = String_37 | Null;
export type String_37 = string;
export type Null = null;
/**
 * Aspect ratio for the generated image (default: 1:1)
 */
export type String_38 =
  | "1:1"
  | "2:3"
  | "3:2"
  | "3:4"
  | "4:3"
  | "4:5"
  | "5:4"
  | "9:16"
  | "16:9"
  | "21:9";

export interface GENERATE_IMAGEInput {
  prompt: String_36;
  baseImageUrl?: StringNull;
  aspectRatio?: String_38;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * URL of the generated image
 */
export type String_39 = string;
/**
 * Whether the request failed
 */
export type Boolean_1 = boolean;
/**
 * Native finish reason
 */
export type String_40 = string;

export interface GENERATE_IMAGEOutput {
  image?: String_39;
  error?: Boolean_1;
  finishReason?: String_40;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_41 = string;
export type StringNull_1 = String_42 | Null_1;
export type String_42 = string;
export type Null_1 = null;
export type StringNull_2 = String_43 | Null_2;
export type String_43 = string;
export type Null_2 = null;
export type String_44 = string;

export interface GET_USEROutput {
  id: String_41;
  name: StringNull_1;
  avatar: StringNull_2;
  email: String_44;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  NANOBANANA_CONTRACT: z.object({
    value: z.string(),
    __type: z
      .literal("@deco/nanobanana-1015fd7069e194c8463a93ff7e5070d1")
      .default("@deco/nanobanana-1015fd7069e194c8463a93ff7e5070d1"),
  }),
  FILE_SYSTEM: z.object({
    value: z.string(),
    __type: z.literal("@deco/file-system").default("@deco/file-system"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  NANOBANANA_CONTRACT: Mcp<{
    /**
     * Authorize a charge for a contract clause. Creates a single authorization with transactionId.
     */
    CONTRACT_AUTHORIZE: (
      input: CONTRACT_AUTHORIZEInput,
    ) => Promise<CONTRACT_AUTHORIZEOutput>;
    /**
     * Get the current contract state.
     */
    CONTRACT_GET: (input: CONTRACT_GETInput) => Promise<CONTRACT_GETOutput>;
    /**
     * Settle the current authorized charge. Processes the payment for the current authorization.
     */
    CONTRACT_SETTLE: (
      input: CONTRACT_SETTLEInput,
    ) => Promise<CONTRACT_SETTLEOutput>;
    /**
     * Start the OAuth flow for the contract app.
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
  }>;
  FILE_SYSTEM: Mcp<{
    /**
     * Delete a file
     */
    FS_DELETE: (input: FS_DELETEInput) => Promise<FS_DELETEOutput>;
    /**
     * List files from a given bucket given a prefix
     */
    FS_LIST: (input: FS_LISTInput) => Promise<FS_LISTOutput>;
    /**
     * Get a secure temporary link to read a file
     */
    FS_READ: (input: FS_READInput) => Promise<FS_READOutput>;
    /**
     * Get metadata about a file
     */
    FS_READ_METADATA: (
      input: FS_READ_METADATAInput,
    ) => Promise<FS_READ_METADATAOutput>;
    /**
     * Get a secure temporary link to upload a file
     */
    FS_WRITE: (input: FS_WRITEInput) => Promise<FS_WRITEOutput>;
  }>;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Generate an image using the Gemini API
     */
    GENERATE_IMAGE: (
      input: GENERATE_IMAGEInput,
    ) => Promise<GENERATE_IMAGEOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
  }>;
}

export const Scopes = {
  NANOBANANA_CONTRACT: {
    CONTRACT_AUTHORIZE: "NANOBANANA_CONTRACT::CONTRACT_AUTHORIZE",
    CONTRACT_GET: "NANOBANANA_CONTRACT::CONTRACT_GET",
    CONTRACT_SETTLE: "NANOBANANA_CONTRACT::CONTRACT_SETTLE",
    DECO_CHAT_OAUTH_START: "NANOBANANA_CONTRACT::DECO_CHAT_OAUTH_START",
  },
  FILE_SYSTEM: {
    FS_DELETE: "FILE_SYSTEM::FS_DELETE",
    FS_LIST: "FILE_SYSTEM::FS_LIST",
    FS_READ: "FILE_SYSTEM::FS_READ",
    FS_READ_METADATA: "FILE_SYSTEM::FS_READ_METADATA",
    FS_WRITE: "FILE_SYSTEM::FS_WRITE",
  },
};
