/**
 * Blacklist of MCP servers that should be excluded from listings
 * Add server names here to filter them out from the registry results
 */

export const BLACKLISTED_SERVERS: string[] = [
  // Add server names here that you want to exclude
  // Examples:
  // "com.example/broken-server",
  "ai.waystation/airtable",
  "ai.waystation/gmail",
  "ai.waystation/jira",
  "ai.waystation/mcp",
  "ai.waystation/miro",
  "ai.waystation/monday",
  "ai.waystation/office",
  "ai.waystation/postgres",
  "ai.waystation/slack",
  "ai.waystation/supabase",
  "ai.waystation/teams",
  "ai.waystation/wrike",
  "ai.explorium/mcp-explorium",
  "ai.gomarble/mcp-api",
  "ai.seltz/seltz-ai-seltz-mcp",
  "ai.shawndurrani/mcp-merchant",
  "ai.shawndurrani/mcp-registry",
  "ai.kubit/mcp-server",
  "ai.meminal/meminal",
  "com.apify/apify-mcp-server",
  "ai.vendor/non-functional-mcp",
  "ai.smithery/arjunkmrm-ahoy",
  "ai.smithery/arjunkmrm-ahoy2",
  "ai.smithery/arjunkmrm-boba-tea",
  "ai.smithery/arjunkmrm-bobo",
  "ai.smithery/arjunkmrm-brave-search-mcp-server",
  "ai.smithery/arjunkmrm-clock",
  "ai.smithery/arjunkmrm-fetch",
  "ai.smithery/arjunkmrm-lta-mcp",
  "ai.smithery/arjunkmrm-mango-sago",
  "ai.smithery/arjunkmrm-perplexity-search",
  "ai.smithery/arjunkmrm-scrapermcp_el",
  "ai.smithery/arjunkmrm-time",
  "ai.smithery/arjunkmrm-tutorials",
  "ai.smithery/arjunkmrm-watch2",
  "io.github.BamaCharanChhandogi/blogcaster-mcp",
  "io.github.KSAklfszf921/riksdag-regering-mcp",
  "io.github.MindscapeHQ/mcp-server-raygun",
  "io.github.ONLYOFFICE/docspace",
  "io.github.PayRam/payram-helper-mcp",
  "io.github.SELISEdigitalplatforms/l0-py-blocks-mcp",
  "io.github.Speeron-Polska/speeron-next",
  "io.github.TranThienTrong/asset-auto-generator",
  "io.github.Vonage/vonage-documentation-mcp",
  "io.github.abhijitjavelin/javelin-guardrails-mcp-server",
  "io.github.alphavantage/alpha_vantage_mcp",
  "io.github.ax-platform/ax-platform",
  "io.github.bahfahh/noteit-mcp",
  "io.github.bitrix24/bitrix-mcp-rest",
  "io.github.clouatre-labs/math-mcp-learning-server",
  "io.github.elankeeran/companies-house-mcp",
  "io.github.equilibrium-team/tweekit",
  "io.github.github/github-mcp-server",
  "io.github.hatgit/forex-gpt-mcp",
  "io.github.humanjesse/textarttools-mcp",
  "io.github.isakskogstad/kolada-mcp",
  "io.github.isakskogstad/oecd-mcp",
  "io.github.isakskogstad/scb-mcp",
  "io.github.jfrog/jfrog-mcp-server",
  "io.github.lemonadolabs/lemonado-mcp-server",
  "io.github.lio1204/what2watch-mcp",
  "io.github.lvpiggyqq/xcatcher",
  "io.github.mcp-fortress/mcp-fortress",
  "io.github.mcpcentral-io/mcp-time",
  "io.github.meloncafe/chromadb-remote-mcp",
  "io.github.mia-platform/console-mcp-server",
  "io.github.mmorris35/devplan-mcp-server",
  "io.github.perplexityai/mcp-server",
  "io.github.promplate/hmr",
  "io.github.ptyagiegnyte/egnyte-remote",
  "io.github.semilattice-research/mcp",
  "io.github.sharksalesinfo-blip/portfolio",
  "io.github.timescale/pg-aiguide",
  "io.github.tonymaynard97/blockscholes-mcp-server",
  "io.github.youdotcom-oss/mcp",
  "com.gitlab/mcp",
  "com.supabase/mcp",
  "com.atlassian/atlassian-mcp-server",
  "ai.cirra/salesforce-mcp", // CORS error
  "com.figma.mcp/mcp", // CORS error
  "io.github.microsoft/EnterpriseMCP", // error "Authentication failed: Incompatible auth server: does not support dynamic client registration" but have support
  "ai.smithery/exa-labs-exa-code-mcp", // error "Authentication failed: Incompatible auth server: does not support dynamic client registration" but have support
];
