export const ACTIVE_STATUSES_SET = new Set([
  "creating_repo",
  "provisioning_sandbox",
  "baselining",
  "migrating_script",
  "opening_pr",
  "reviewing",
  "merging",
  "triaging",
  "fixing",
  "paritying",
  "deploying",
  // legacy
  "migrating",
  "migrating2",
  "migrating3",
  "installing_sync",
  "validating",
  "validating2",
  "validating3",
  "deploying_cf",
]);
