// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Court code (e.g., tjdft, tjsp, tjrj, trf1, tst). If not provided, uses the configured default tribunal.
 */
export type String = string;

export interface AGGREGATE_STATISTICSInput {
  tribunal?: String;
  aggregations: Object;
  filters?: Object_1;
}
/**
 * Aggregation definitions in Elasticsearch format. Example: {'por_classe': {'terms': {'field': 'classe.codigo', 'size': 10}}}
 */
export interface Object {
  [k: string]: unknown;
}
/**
 * Optional filters to limit processes included in statistics. Same format as SEARCH_PROCESSES.
 */
export interface Object_1 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Total number of documents that matched the filters
 */
export type Number = number;
/**
 * Code of the consulted tribunal
 */
export type String_1 = string;

export interface AGGREGATE_STATISTICSOutput {
  aggregations: Object_2;
  totalDocuments: Number;
  tribunal: String_1;
}
/**
 * Results of executed aggregations
 */
export interface Object_2 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_2 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type Array = String_3[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_4 = string;
export type String_5 = string;
export type String_6 = string;
export type String_7 = string;
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;
export type String_11 = string;
export type String_12 = string;
export type Array_2 = String_12[];
export type String_13 = string;
export type String_14 = "none" | "open" | "autoPin";
export type Array_1 = Object_3[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_1;
}
export interface Object_3 {
  id?: String_4;
  name?: String_5;
  title: String_6;
  description?: String_7;
  icon: String_8;
  url?: String_9;
  mimeTypePattern?: String_10;
  resourceName?: String_11;
  tools?: Array_2;
  prompt?: String_13;
  installBehavior?: String_14;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Court code (e.g., tjdft, tjsp, tjrj, trf1, tst). If not provided, uses the configured default tribunal.
 */
export type String_15 = string;
/**
 * Process number in CNJ format (20 digits). Example: 0000000-00.0000.0.00.0000
 */
export type String_16 = string;

export interface GET_PROCESSInput {
  tribunal?: String_15;
  numeroProcesso: String_16;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Indicates whether the process was found
 */
export type Boolean_1 = boolean;
export type Null = null;
/**
 * Code of the consulted tribunal
 */
export type String_17 = string;

export interface GET_PROCESSOutput {
  found: Boolean_1;
  /**
   * Complete process metadata, or null if not found
   */
  process: Object_4 | Null;
  tribunal: String_17;
}
export interface Object_4 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_18 = string;
export type StringNull = String_19 | Null_1;
export type String_19 = string;
export type Null_1 = null;
export type StringNull_1 = String_20 | Null_2;
export type String_20 = string;
export type Null_2 = null;
export type String_21 = string;

export interface GET_USEROutput {
  id: String_18;
  name: StringNull;
  avatar: StringNull_1;
  email: String_21;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Court code (e.g., tjdft, tjsp, tjrj, trf1, tst). If not provided, uses the configured default tribunal.
 */
export type String_22 = string;
/**
 * Maximum number of processes to return (default: 10)
 */
export type Number_1 = number;
/**
 * Pagination offset, number of processes to skip (default: 0)
 */
export type Number_2 = number;
/**
 * Result sorting. Example: [{'dataAjuizamento': 'desc'}]
 */
export type Array_3 = Object_6[];

export interface SEARCH_PROCESSESInput {
  tribunal?: String_22;
  filters?: Object_5;
  size?: Number_1;
  from?: Number_2;
  sort?: Array_3;
}
/**
 * Search filters. Examples: {'classe.nome': 'Procedimento Comum', 'grau': 'G2', 'orgaoJulgador.nomeOrgao': '1ª Turma Cível'}
 */
export interface Object_5 {
  [k: string]: unknown;
}
export interface Object_6 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Total number of processes found
 */
export type Number_3 = number;
/**
 * Number of processes returned in this page
 */
export type Number_4 = number;
/**
 * List of found processes with their metadata
 */
export type Array_4 = Object_7[];
/**
 * Code of the consulted tribunal
 */
export type String_23 = string;

export interface SEARCH_PROCESSESOutput {
  total: Number_3;
  returned: Number_4;
  processes: Array_4;
  tribunal: String_23;
}
export interface Object_7 {
  [k: string]: unknown;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  SELF: Mcp<{
    /**
     * Execute aggregations and generate statistics about judicial processes in Datajud. Allows calculating counts, averages, sums, and other metrics grouped by fields such as class, subject, court, filing year, etc. Uses Elasticsearch aggregation syntax.
     */
    AGGREGATE_STATISTICS: (
      input: AGGREGATE_STATISTICSInput,
    ) => Promise<AGGREGATE_STATISTICSOutput>;
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Search for a specific judicial process by process number in Datajud. Returns all available process metadata, including class, subjects, movements, court, etc.
     */
    GET_PROCESS: (input: GET_PROCESSInput) => Promise<GET_PROCESSOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * Search judicial processes in Datajud with filters. Allows filtering by class, subject, court, filing date, and other fields from the Data Transfer Model (MTD). Returns a list of processes with their metadata.
     */
    SEARCH_PROCESSES: (
      input: SEARCH_PROCESSESInput,
    ) => Promise<SEARCH_PROCESSESOutput>;
  }>;
}

export const Scopes = {};
