// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type Array = String_1[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_2 = string;
export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type String_6 = string;
export type String_7 = string;
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;
export type Array_2 = String_10[];
export type String_11 = string;
export type String_12 = "none" | "open" | "autoPin";
export type Array_1 = Object[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_1;
}
export interface Object {
  id?: String_2;
  name?: String_3;
  title: String_4;
  description?: String_5;
  icon: String_6;
  url?: String_7;
  mimeTypePattern?: String_8;
  resourceName?: String_9;
  tools?: Array_2;
  prompt?: String_11;
  installBehavior?: String_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_13 = string;
/**
 * Optional array of vector IDs to delete
 */
export type Array_3 = String_13[];
/**
 * If true, deletes all vectors in the namespace (use with caution)
 */
export type Boolean_1 = boolean;
/**
 * Optional namespace to delete from (uses state default if not provided)
 */
export type String_14 = string;

export interface DELETE_VECTORSInput {
  ids?: Array_3;
  deleteAll?: Boolean_1;
  namespace?: String_14;
  filter?: Object_1;
}
/**
 * Optional metadata filter to select vectors to delete (e.g., {status: 'archived'})
 */
export interface Object_1 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DELETE_VECTORSOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Array of vector IDs to fetch (max 1000)
 *
 * @minItems 1
 * @maxItems 1000
 */
export type Array_4 = [String_15, ...String_15[]];
export type String_15 = string;
/**
 * Optional namespace to fetch from (uses state default if not provided)
 */
export type String_16 = string;

export interface FETCH_VECTORSInput {
  ids: Array_4;
  namespace?: String_16;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FETCH_VECTORSOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_17 = string;
export type StringNull = String_18 | Null;
export type String_18 = string;
export type Null = null;
export type StringNull_1 = String_19 | Null_1;
export type String_19 = string;
export type Null_1 = null;
export type String_20 = string;

export interface GET_USEROutput {
  id: String_17;
  name: StringNull;
  avatar: StringNull_1;
  email: String_20;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Number = number;
/**
 * Query vector to search with (mutually exclusive with id)
 */
export type Array_5 = Number[];
/**
 * ID of an existing vector to use as query (mutually exclusive with vector)
 */
export type String_21 = string;
/**
 * Number of most similar results to return (default: 10)
 */
export type Number_1 = number;
/**
 * Optional namespace to search within (uses state default if not provided)
 */
export type String_22 = string;
/**
 * Whether to include metadata in results (default: true)
 */
export type Boolean_2 = boolean;
/**
 * Whether to include vector values in results (default: false)
 */
export type Boolean_3 = boolean;
export type Number_2 = number;
/**
 * Indices of non-zero values
 */
export type Array_6 = Number_2[];
export type Number_3 = number;
/**
 * Non-zero values
 */
export type Array_7 = Number_3[];

export interface QUERY_VECTORSInput {
  vector?: Array_5;
  id?: String_21;
  topK?: Number_1;
  namespace?: String_22;
  filter?: Object_2;
  includeMetadata?: Boolean_2;
  includeValues?: Boolean_3;
  sparseVector?: Object_3;
}
/**
 * Optional metadata filter to apply (e.g., {category: 'electronics'})
 */
export interface Object_2 {
  [k: string]: unknown;
}
/**
 * Optional sparse vector for hybrid search
 */
export interface Object_3 {
  indices: Array_6;
  values: Array_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface QUERY_VECTORSOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Array of vectors to upsert (max 1000 per request)
 *
 * @minItems 1
 * @maxItems 1000
 */
export type Array_8 = [Object_4, ...Object_4[]];
/**
 * Unique identifier for the vector
 */
export type String_23 = string;
export type Number_4 = number;
/**
 * Vector embedding values
 */
export type Array_9 = Number_4[];
export type String_24 = string;
export type Number_5 = number;
export type Boolean_4 = boolean;
export type String_25 = string;
export type Array_10 = String_25[];
export type Number_6 = number;
/**
 * Indices of non-zero values
 */
export type Array_11 = Number_6[];
export type Number_7 = number;
/**
 * Non-zero values
 */
export type Array_12 = Number_7[];
/**
 * Optional namespace to organize vectors (uses state default if not provided)
 */
export type String_26 = string;

export interface UPSERT_VECTORSInput {
  vectors: Array_8;
  namespace?: String_26;
}
export interface Object_4 {
  id: String_23;
  values: Array_9;
  metadata?: Object_5;
  sparseValues?: Object_6;
}
/**
 * Optional metadata associated with the vector
 */
export interface Object_5 {
  [k: string]: String_24 | Number_5 | Boolean_4 | Array_10;
}
/**
 * Optional sparse vector values for hybrid search
 */
export interface Object_6 {
  indices: Array_11;
  values: Array_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UPSERT_VECTORSOutput {}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Delete vectors from the Pinecone index. You can delete specific vectors by IDs, delete all vectors in a namespace, or delete vectors matching a metadata filter. Use with caution as this operation is irreversible.
     */
    DELETE_VECTORS: (
      input: DELETE_VECTORSInput,
    ) => Promise<DELETE_VECTORSOutput>;
    /**
     * Fetch specific vectors by their IDs. Returns the complete vector data including values and metadata. Use this to retrieve known vectors by their identifiers. Maximum 1000 IDs per request.
     */
    FETCH_VECTORS: (input: FETCH_VECTORSInput) => Promise<FETCH_VECTORSOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * Query vectors by similarity using either a query vector or an existing vector ID. Returns the most similar vectors ranked by score. Use this for semantic search, finding similar items, or recommendation systems. You can filter results by metadata and control which data is included in the response.
     */
    QUERY_VECTORS: (input: QUERY_VECTORSInput) => Promise<QUERY_VECTORSOutput>;
    /**
     * Insert or update vectors in the Pinecone index. If a vector with the same ID exists, it will be updated. Supports batch operations with multiple vectors at once. Use this to add embeddings to your vector database.
     */
    UPSERT_VECTORS: (
      input: UPSERT_VECTORSInput,
    ) => Promise<UPSERT_VECTORSOutput>;
  }>;
}

export const Scopes = {};
