// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type Number = number;
export type Array = Object[];

export interface CONTRACT_AUTHORIZEInput {
  clauses: Array;
}
export interface Object {
  clauseId: String;
  amount: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type String_2 = string;
export type Number_1 = number;

export interface CONTRACT_AUTHORIZEOutput {
  transactionId: String_1;
  totalAmount: String_2;
  timestamp: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CONTRACT_GETInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type StringNumber = String_6 | Number_2;
export type String_6 = string;
export type Number_2 = number;
export type String_7 = string;
export type String_8 = string;
export type Array_2 = String_8[];
export type Array_1 = Object_2[];

export interface CONTRACT_GETOutput {
  appName?: String_3;
  contract: Object_1;
}
export interface Object_1 {
  body?: String_4;
  clauses?: Array_1;
}
export interface Object_2 {
  id: String_5;
  price: StringNumber;
  description?: String_7;
  usedByTools?: Array_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_9 = string;
export type String_10 = string;
export type Number_3 = number;
export type Array_3 = Object_3[];
export type Number_4 = number;
export type String_11 = string;

export interface CONTRACT_SETTLEInput {
  transactionId: String_9;
  clauses?: Array_3;
  amount?: Number_4;
  vendorId: String_11;
}
export interface Object_3 {
  clauseId: String_10;
  amount: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_12 = string;

export interface CONTRACT_SETTLEOutput {
  transactionId: String_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_13 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_14 = string;
export type Array_4 = String_14[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_15 = string;

export interface DECO_CHAT_OAUTH_STARTInput_1 {
  returnUrl: String_15;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_16 = string;
export type Array_5 = String_16[];

export interface DECO_CHAT_OAUTH_STARTOutput_1 {
  stateSchema?: unknown;
  scopes?: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_17 = string;
export type String_18 = string;
export type String_19 = string;
export type String_20 = string;
export type String_21 = string;
export type String_22 = string;
export type String_23 = string;
export type String_24 = string;
export type String_25 = string;
export type Array_7 = String_25[];
export type String_26 = string;
export type String_27 = "none" | "open" | "autoPin";
export type Array_6 = Object_4[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_6;
}
export interface Object_4 {
  id?: String_17;
  name?: String_18;
  title: String_19;
  description?: String_20;
  icon: String_21;
  url?: String_22;
  mimeTypePattern?: String_23;
  resourceName?: String_24;
  tools?: Array_7;
  prompt?: String_26;
  installBehavior?: String_27;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the file to delete
 */
export type String_28 = string;

export interface DeleteFileInput {
  fileId: String_28;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_1 = boolean;
export type String_29 = string;

export interface DeleteFileOutput {
  success: Boolean_1;
  message?: String_29;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the file to retrieve
 */
export type String_30 = string;
/**
 * Whether to include a signed URL for downloading the file
 */
export type Boolean_2 = boolean;

export interface GetFileInput {
  fileId: String_30;
  includeUrl?: Boolean_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_3 = boolean;
export type String_31 = string;
export type String_32 = string;
export type String_33 = string;
export type String_34 = string;
export type String_35 = string;
export type Null = null;
export type StringNull = String_36 | Null_1;
export type String_36 = string;
export type Null_1 = null;
export type NumberNull = Number_5 | Null_2;
export type Number_5 = number;
export type Null_2 = null;
export type StringNull_1 = String_37 | Null_3;
export type String_37 = string;
export type Null_3 = null;
export type Null_4 = null;
export type String_38 = string;

export interface GetFileOutput {
  success: Boolean_3;
  file: Object_5 | Null_4;
  message?: String_38;
}
export interface Object_5 {
  id: String_31;
  name: String_32;
  status?: String_33;
  created_on?: String_34;
  updated_on?: String_35;
  metadata?: Object_6 | Null;
  signed_url?: StringNull;
  percent_done?: NumberNull;
  error_message?: StringNull_1;
}
export interface Object_6 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_39 = string;
export type StringNull_2 = String_40 | Null_5;
export type String_40 = string;
export type Null_5 = null;
export type StringNull_3 = String_41 | Null_6;
export type String_41 = string;
export type Null_6 = null;
export type String_42 = string;

export interface GET_USEROutput {
  id: String_39;
  name: StringNull_2;
  avatar: StringNull_3;
  email: String_42;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Optional filter for files
 */
export type String_43 = string;
/**
 * Maximum number of files to return
 */
export type Number_6 = number;
/**
 * Number of files to skip
 */
export type Number_7 = number;

export interface ListFilesInput {
  filter?: String_43;
  limit?: Number_6;
  offset?: Number_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_4 = boolean;
export type String_44 = string;
export type String_45 = string;
export type String_46 = string;
export type String_47 = string;
export type String_48 = string;
export type Null_7 = null;
export type Array_8 = Object_7[];
export type Number_8 = number;
export type String_49 = string;

export interface ListFilesOutput {
  success: Boolean_4;
  files: Array_8;
  total?: Number_8;
  message?: String_49;
}
export interface Object_7 {
  id: String_44;
  name: String_45;
  status?: String_46;
  created_on?: String_47;
  updated_on?: String_48;
  metadata?: Object_8 | Null_7;
}
export interface Object_8 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Query to search for
 */
export type String_50 = string;
/**
 * Optionally filter which documents can be retrieved using metadata fields. Example: {"type": "faq_entry"}
 */
export type String_51 = string;
/**
 * The number of context snippets to retrieve. Defaults to 15.
 */
export type Number_9 = number;
/**
 * Whether to include metadata in the response. Defaults to false.
 */
export type Boolean_5 = boolean;

export interface SearchContextInput {
  query: String_50;
  filter?: String_51;
  topK?: Number_9;
  includeMetadata?: Boolean_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_52 = string;
export type String_53 = string;
export type String_54 = string;
export type Array_9 = Object_9[];

export interface SearchContextOutput {
  content: Array_9;
}
export interface Object_9 {
  type: String_52;
  text: String_53;
  metadata?: Object_10;
}
export interface Object_10 {
  [k: string]: String_54;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL of the file to upload
 */
export type String_55 = string;
/**
 * The content of the file to upload (text only)
 */
export type String_56 = string;
/**
 * The optional name of the file with extension (if not provided, the file will be named 'file-{timestamp}.txt')
 */
export type String_57 = string;

export interface UploadFileInput {
  fileUrl?: String_55;
  fileContent?: String_56;
  fileName?: String_57;
  metadata?: Object_11;
}
/**
 * The optional metadata to attach to the file
 */
export interface Object_11 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_6 = boolean;
export type String_58 = string;
export type String_59 = string;
export type String_60 = string;
export type String_61 = string;
export type String_62 = string;
export type Null_8 = null;
export type Null_9 = null;
export type String_63 = string;

export interface UploadFileOutput {
  success: Boolean_6;
  file: Object_12 | Null_9;
  message?: String_63;
}
export interface Object_12 {
  id: String_58;
  name: String_59;
  status?: String_60;
  created_on?: String_61;
  updated_on?: String_62;
  metadata?: Object_13 | Null_8;
}
export interface Object_13 {
  [k: string]: unknown;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  PINECONE_CONTRACT: z.object({
    value: z.string(),
    __type: z
      .literal("@deco/pinecone-01ec759d28a7f0a0519974dcbafcc5d6")
      .default("@deco/pinecone-01ec759d28a7f0a0519974dcbafcc5d6"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  PINECONE_CONTRACT: Mcp<{
    /**
     * Authorize a charge for a contract clause. Creates a single authorization with transactionId.
     */
    CONTRACT_AUTHORIZE: (
      input: CONTRACT_AUTHORIZEInput,
    ) => Promise<CONTRACT_AUTHORIZEOutput>;
    /**
     * Get the current contract state.
     */
    CONTRACT_GET: (input: CONTRACT_GETInput) => Promise<CONTRACT_GETOutput>;
    /**
     * Settle the current authorized charge. Processes the payment for the current authorization.
     */
    CONTRACT_SETTLE: (
      input: CONTRACT_SETTLEInput,
    ) => Promise<CONTRACT_SETTLEOutput>;
    /**
     * Start the OAuth flow for the contract app.
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
  }>;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Deletes a file from the Pinecone assistant
     */
    delete_file: (input: DeleteFileInput) => Promise<DeleteFileOutput>;
    /**
     * Gets details of a specific file from the Pinecone assistant
     */
    get_file: (input: GetFileInput) => Promise<GetFileOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * Lists all files in the Pinecone assistant
     */
    list_files: (input: ListFilesInput) => Promise<ListFilesOutput>;
    /**
     * Retrieves relevant document snippets from the assistant's knowledge base. Returns an array of text snippets from the most relevant documents. Use the 'topK' parameter to control result count (default: 15). Recommended topK: a few (5-8) for simple/narrow queries, 10-20 for complex/broad topics.
     */
    search_context: (input: SearchContextInput) => Promise<SearchContextOutput>;
    /**
     * Uploads a file to the Pinecone assistant. You can provide either a file URL or file content. The file will be processed and made available for context retrieval.
     */
    upload_file: (input: UploadFileInput) => Promise<UploadFileOutput>;
  }>;
}

export const Scopes = {
  PINECONE_CONTRACT: {
    CONTRACT_AUTHORIZE: "PINECONE_CONTRACT::CONTRACT_AUTHORIZE",
    CONTRACT_GET: "PINECONE_CONTRACT::CONTRACT_GET",
    CONTRACT_SETTLE: "PINECONE_CONTRACT::CONTRACT_SETTLE",
    DECO_CHAT_OAUTH_START: "PINECONE_CONTRACT::DECO_CHAT_OAUTH_START",
  },
};
