/**
 * Generated types for Google Analytics MCP
 * This file is typically auto-generated by the Deco runtime
 */

import type { DefaultEnv } from "@decocms/runtime";

/**
 * Environment type for Google Analytics MCP
 * Includes OAuth tokens and other runtime configuration
 */
export type Env = DefaultEnv;
