// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique ID of the prediction to cancel
 */
export type String = string;

export interface CANCEL_PREDICTIONInput {
  predictionId: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique prediction ID
 */
export type String_1 = string;
/**
 * Current status of the prediction (should be 'canceled')
 */
export type String_2 = string;
/**
 * Confirmation message
 */
export type String_3 = string;

export interface CANCEL_PREDICTIONOutput {
  id: String_1;
  status: String_2;
  message: String_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_4 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_5 = string;
export type Array = String_5[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_6 = string;
export type String_7 = string;
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;
export type String_11 = string;
export type String_12 = string;
export type String_13 = string;
export type String_14 = string;
export type Array_2 = String_14[];
export type String_15 = string;
export type String_16 = "none" | "open" | "autoPin";
export type Array_1 = Object[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_1;
}
export interface Object {
  id?: String_6;
  name?: String_7;
  title: String_8;
  description?: String_9;
  icon: String_10;
  url?: String_11;
  mimeTypePattern?: String_12;
  resourceName?: String_13;
  tools?: Array_2;
  prompt?: String_15;
  installBehavior?: String_16;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Model identifier in format 'owner/name'. Examples: 'stability-ai/sdxl', 'meta/llama-2-70b-chat'
 */
export type String_17 = string;

export interface GET_MODELInput {
  model: String_17;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Model owner username
 */
export type String_18 = string;
/**
 * Model name
 */
export type String_19 = string;
/**
 * Model description
 */
export type String_20 = string;
/**
 * Model visibility (public/private)
 */
export type String_21 = string;
/**
 * Number of times model has been run
 */
export type Number = number;
/**
 * URL of model cover image
 */
export type String_22 = string;
/**
 * Full model URL
 */
export type String_23 = string;
/**
 * GitHub repository URL
 */
export type String_24 = string;
/**
 * Research paper URL
 */
export type String_25 = string;
/**
 * License URL
 */
export type String_26 = string;
/**
 * Version ID
 */
export type String_27 = string;
/**
 * Version creation date
 */
export type String_28 = string;
/**
 * Cog version used
 */
export type String_29 = string;

export interface GET_MODELOutput {
  owner: String_18;
  name: String_19;
  description?: String_20;
  visibility: String_21;
  run_count: Number;
  cover_image_url?: String_22;
  url: String_23;
  github_url?: String_24;
  paper_url?: String_25;
  license_url?: String_26;
  latest_version?: Object_1;
  default_example?: Object_3;
}
/**
 * Latest version information with full schema
 */
export interface Object_1 {
  id: String_27;
  created_at: String_28;
  cog_version: String_29;
  openapi_schema: Object_2;
}
/**
 * OpenAPI schema for the model
 */
export interface Object_2 {
  [k: string]: unknown;
}
/**
 * Default example input/output
 */
export interface Object_3 {
  input: Object_4;
  /**
   * Example output
   */
  output?: {
    [k: string]: unknown;
  };
}
/**
 * Example input parameters
 */
export interface Object_4 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique ID of the prediction to retrieve
 */
export type String_30 = string;

export interface GET_PREDICTIONInput {
  predictionId: String_30;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique prediction ID
 */
export type String_31 = string;
/**
 * Current status of the prediction
 */
export type String_32 = string;
/**
 * Model used for the prediction
 */
export type String_33 = string;
/**
 * Error message (if failed)
 */
export type String_34 = string;
/**
 * Execution logs
 */
export type String_35 = string;
/**
 * Prediction execution time
 */
export type Number_1 = number;
/**
 * URL to get prediction status
 */
export type String_36 = string;
/**
 * URL to cancel the prediction
 */
export type String_37 = string;
/**
 * Model version used
 */
export type String_38 = string;
/**
 * When the prediction was created
 */
export type String_39 = string;
/**
 * When processing started
 */
export type String_40 = string;
/**
 * When the prediction completed
 */
export type String_41 = string;

export interface GET_PREDICTIONOutput {
  id: String_31;
  status: String_32;
  model: String_33;
  /**
   * Model output (if completed)
   */
  output?: {
    [k: string]: unknown;
  };
  error?: String_34;
  logs?: String_35;
  metrics?: Object_5;
  urls?: Object_6;
  version: String_38;
  input: Object_7;
  created_at: String_39;
  started_at?: String_40;
  completed_at?: String_41;
}
/**
 * Performance metrics
 */
export interface Object_5 {
  predict_time?: Number_1;
}
/**
 * URLs to get status or cancel the prediction
 */
export interface Object_6 {
  get: String_36;
  cancel: String_37;
}
/**
 * Input parameters used
 */
export interface Object_7 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_42 = string;
export type StringNull = String_43 | Null;
export type String_43 = string;
export type Null = null;
export type StringNull_1 = String_44 | Null_1;
export type String_44 = string;
export type Null_1 = null;
export type String_45 = string;

export interface GET_USEROutput {
  id: String_42;
  name: StringNull;
  avatar: StringNull_1;
  email: String_45;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Filter models by owner username or organization. Examples: 'stability-ai', 'meta', 'replicate'. Leave empty to see featured models.
 */
export type String_46 = string;
/**
 * Pagination cursor from previous response
 */
export type String_47 = string;

export interface LIST_MODELSInput {
  owner?: String_46;
  cursor?: String_47;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Model owner username
 */
export type String_48 = string;
/**
 * Model name
 */
export type String_49 = string;
/**
 * Model description
 */
export type String_50 = string;
/**
 * Model visibility (public/private)
 */
export type String_51 = string;
/**
 * Number of times model has been run
 */
export type Number_2 = number;
/**
 * URL of model cover image
 */
export type String_52 = string;
/**
 * Full model URL
 */
export type String_53 = string;
/**
 * Version ID
 */
export type String_54 = string;
/**
 * Version creation date
 */
export type String_55 = string;
export type Array_3 = Object_8[];
/**
 * Cursor for next page of results
 */
export type String_56 = string;

export interface LIST_MODELSOutput {
  models: Array_3;
  next_cursor?: String_56;
}
export interface Object_8 {
  owner: String_48;
  name: String_49;
  description?: String_50;
  visibility: String_51;
  run_count: Number_2;
  cover_image_url?: String_52;
  url: String_53;
  latest_version?: Object_9;
}
/**
 * Latest version information
 */
export interface Object_9 {
  id: String_54;
  created_at: String_55;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Model identifier in format 'owner/name' or 'owner/name:version'. Examples: 'stability-ai/sdxl', 'meta/llama-2-70b-chat'
 */
export type String_57 = string;
/**
 * Whether to wait for the prediction to complete. If false, returns immediately with prediction ID.
 */
export type Boolean_1 = boolean;
/**
 * Optional webhook URL to receive prediction updates. Replicate will POST to this URL when prediction completes.
 */
export type String_58 = string;

export interface RUN_MODELInput {
  model: String_57;
  input: Object_10;
  wait?: Boolean_1;
  webhook?: String_58;
}
/**
 * Input parameters for the model as key-value pairs. Check model documentation for required/optional parameters.
 */
export interface Object_10 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique prediction ID
 */
export type String_59 = string;
/**
 * Current status of the prediction
 */
export type String_60 = string;
/**
 * Model used for the prediction
 */
export type String_61 = string;
/**
 * Error message (if failed)
 */
export type String_62 = string;
/**
 * Execution logs
 */
export type String_63 = string;
/**
 * Prediction execution time
 */
export type Number_3 = number;
/**
 * URL to get prediction status
 */
export type String_64 = string;
/**
 * URL to cancel the prediction
 */
export type String_65 = string;

export interface RUN_MODELOutput {
  id: String_59;
  status: String_60;
  model: String_61;
  /**
   * Model output (if completed)
   */
  output?: {
    [k: string]: unknown;
  };
  error?: String_62;
  logs?: String_63;
  metrics?: Object_11;
  urls?: Object_12;
}
/**
 * Performance metrics
 */
export interface Object_11 {
  predict_time?: Number_3;
}
/**
 * URLs to get status or cancel the prediction
 */
export interface Object_12 {
  get: String_64;
  cancel: String_65;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  SELF: Mcp<{
    /**
     * Cancel a prediction that is currently starting or processing. Once canceled, the prediction cannot be resumed. Returns the updated prediction status.
     */
    CANCEL_PREDICTION: (
      input: CANCEL_PREDICTIONInput,
    ) => Promise<CANCEL_PREDICTIONOutput>;
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Get detailed information about a specific Replicate model. Returns comprehensive metadata including description, run count, example inputs/outputs, latest version details, and schema information.
     */
    GET_MODEL: (input: GET_MODELInput) => Promise<GET_MODELOutput>;
    /**
     * Get the current status and results of a prediction by its ID. Use this to check on predictions created with wait=false, or to retrieve results after receiving a webhook notification.
     */
    GET_PREDICTION: (
      input: GET_PREDICTIONInput,
    ) => Promise<GET_PREDICTIONOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * List available models from Replicate. You can filter by owner (user or organization) to see their models. Returns model metadata including name, description, run count, and latest version info.
     */
    LIST_MODELS: (input: LIST_MODELSInput) => Promise<LIST_MODELSOutput>;
    /**
     * Execute a prediction using a Replicate model. Provide the model identifier (e.g., 'stability-ai/sdxl') and input parameters. The tool will create a prediction and wait for it to complete. Returns the prediction output, which varies by model (images, text, audio, etc.).
     */
    RUN_MODEL: (input: RUN_MODELInput) => Promise<RUN_MODELOutput>;
  }>;
}

export const Scopes = {};
