/**
 * Keyless transcript fetch via YouTube's timedtext endpoint (Innertube).
 *
 * The official captions.download endpoint 403s for auto-generated (ASR)
 * tracks — this is the documented workaround, identical to the path the
 * youtube-search MCP uses. Works for public/unlisted videos only.
 */
import { Innertube, UniversalCache } from "youtubei.js";

let instance: Promise<Innertube> | null = null;

function getInnertube(): Promise<Innertube> {
  instance ??= Innertube.create({
    cache: new UniversalCache(true, "/tmp/yt-cache"),
    generate_session_locally: true,
  });
  return instance;
}

interface Segment {
  startMs: number;
  endMs: number;
  text: string;
}

interface TimedTextJson3 {
  events?: Array<{
    tStartMs?: number;
    dDurationMs?: number;
    aAppend?: number;
    segs?: Array<{ utf8?: string }>;
  }>;
}

function pad(value: number, length: number): string {
  return String(value).padStart(length, "0");
}

function stamp(ms: number, separator: "," | "."): string {
  const h = Math.floor(ms / 3_600_000);
  const m = Math.floor((ms % 3_600_000) / 60_000);
  const s = Math.floor((ms % 60_000) / 1000);
  return `${pad(h, 2)}:${pad(m, 2)}:${pad(s, 2)}${separator}${pad(Math.floor(ms % 1000), 3)}`;
}

function render(segments: Segment[], format: "text" | "srt" | "vtt"): string {
  if (format === "srt") {
    return segments
      .map(
        (seg, i) =>
          `${i + 1}\n${stamp(seg.startMs, ",")} --> ${stamp(seg.endMs, ",")}\n${seg.text}\n`,
      )
      .join("\n");
  }
  if (format === "vtt") {
    return `WEBVTT\n\n${segments
      .map(
        (seg) =>
          `${stamp(seg.startMs, ".")} --> ${stamp(seg.endMs, ".")}\n${seg.text}\n`,
      )
      .join("\n")}`;
  }
  return segments.map((seg) => seg.text).join("\n");
}

export async function fetchTimedTextTranscript(
  videoId: string,
  language: string | undefined,
  format: "text" | "srt" | "vtt",
): Promise<{
  transcript: string;
  language?: string;
  isAutoGenerated: boolean;
}> {
  const yt = await getInnertube();
  let info;
  try {
    info = await yt.getInfo(videoId);
  } catch (error) {
    throw new Error(
      `Could not read captions keyless (video may be private — set it to unlisted temporarily): ${error instanceof Error ? error.message : error}`,
    );
  }

  // deno-lint-ignore no-explicit-any
  const tracks: any[] = info.captions?.caption_tracks ?? [];
  if (tracks.length === 0) {
    throw new Error("This video has no caption tracks at all.");
  }
  const wanted = language?.toLowerCase();
  const track =
    (wanted &&
      tracks.find((candidate) =>
        String(candidate.language_code ?? "")
          .toLowerCase()
          .startsWith(wanted),
      )) ||
    tracks[0];

  const url = new URL(String(track.base_url));
  url.searchParams.set("fmt", "json3");
  const response = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0" },
  });
  if (!response.ok) {
    throw new Error(`timedtext request failed with status ${response.status}`);
  }
  const data = (await response.json()) as TimedTextJson3;

  const segments: Segment[] = (data.events ?? [])
    .filter((event) => event.segs?.length && !event.aAppend)
    .map((event) => {
      const startMs = event.tStartMs ?? 0;
      return {
        startMs,
        endMs: startMs + (event.dDurationMs ?? 0),
        text: (event.segs ?? [])
          .map((seg) => seg.utf8 ?? "")
          .join("")
          .replace(/\n/g, " ")
          .trim(),
      };
    })
    .filter((segment) => segment.text.length > 0);

  if (segments.length === 0) {
    throw new Error("Caption track exists but returned no segments.");
  }

  return {
    transcript: render(segments, format),
    language: String(track.language_code ?? ""),
    isAutoGenerated:
      track.kind === "asr" || String(track.vss_id ?? "").startsWith("a."),
  };
}
