// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MCP_CONFIGURATIONInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type Array = String[];

export interface MCP_CONFIGURATIONOutput {
  stateSchema?: unknown;
  scopes?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * URL of the audio file to transcribe
 */
export type String_1 = string;
/**
 * Language code (e.g., pt-BR, en-US, es-ES)
 */
export type String_2 = string;
/**
 * Speech recognition model
 */
export type String_3 =
  | "default"
  | "command_and_search"
  | "phone_call"
  | "video"
  | "medical_conversation"
  | "medical_dictation";
/**
 * Enable automatic punctuation
 */
export type Boolean = boolean;
/**
 * Include word-level timestamps
 */
export type Boolean_1 = boolean;

export interface SpeechToTextInput {
  audioUrl: String_1;
  languageCode?: String_2;
  model?: String_3;
  enableAutomaticPunctuation?: Boolean;
  enableWordTimeOffsets?: Boolean_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_2 = boolean;
/**
 * Transcribed text
 */
export type String_4 = string;
/**
 * Confidence score (0-1)
 */
export type Number = number;
export type String_5 = string;
export type String_6 = string;
export type String_7 = string;
export type Number_1 = number;
/**
 * Word-level timestamps
 */
export type Array_1 = Object[];
/**
 * Billed duration
 */
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;

export interface SpeechToTextOutput {
  success: Boolean_2;
  transcript?: String_4;
  confidence?: Number;
  words?: Array_1;
  billedDuration?: String_8;
  message: String_9;
  error?: String_10;
}
export interface Object {
  word: String_5;
  startTime: String_6;
  endTime: String_7;
  confidence: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Text to convert to speech (max 5000 characters)
 */
export type String_11 = string;
/**
 * Language code (e.g., pt-BR, en-US, es-ES)
 */
export type String_12 = string;
/**
 * Voice name (e.g., pt-BR-Standard-A, pt-BR-Neural2-A)
 */
export type String_13 = string;
/**
 * Audio encoding format
 */
export type String_14 = "LINEAR16" | "MP3" | "OGG_OPUS" | "MULAW";
/**
 * Speaking rate (0.25 to 4.0)
 */
export type Number_2 = number;
/**
 * Pitch adjustment (-20.0 to 20.0)
 */
export type Number_3 = number;

export interface TextToSpeechInput {
  text: String_11;
  languageCode?: String_12;
  voiceName?: String_13;
  audioEncoding?: String_14;
  speakingRate?: Number_2;
  pitch?: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_3 = boolean;
/**
 * Base64 encoded audio
 */
export type String_15 = string;
export type String_16 = string;
export type Number_4 = number;
export type Number_5 = number;
export type Number_6 = number;
export type String_17 = string;
export type String_18 = string;

export interface TextToSpeechOutput {
  success: Boolean_3;
  audioContent?: String_15;
  audioConfig?: Object_1;
  contentLength?: Number_6;
  message: String_17;
  error?: String_18;
}
export interface Object_1 {
  audioEncoding: String_16;
  sampleRateHertz?: Number_4;
  effectiveChannel?: Number_5;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  SELF: Mcp<{
    /**
     * MCP Configuration
     */
    MCP_CONFIGURATION: (
      input: MCP_CONFIGURATIONInput,
    ) => Promise<MCP_CONFIGURATIONOutput>;
    /**
     * Convert audio to text using Google Cloud Speech-to-Text API
     */
    speech_to_text: (input: SpeechToTextInput) => Promise<SpeechToTextOutput>;
    /**
     * Convert text to speech using Google Cloud Text-to-Speech API
     */
    text_to_speech: (input: TextToSpeechInput) => Promise<TextToSpeechOutput>;
  }>;
}

export const Scopes = {};
