// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain or URL to analyze
 */
export type String = string;
/**
 * Maximum number of results
 */
export type Number = number;
/**
 * Offset for pagination
 */
export type Number_1 = number;

export interface DATAFORSEO_GET_BACKLINKSInput {
  target: String;
  limit?: Number;
  offset?: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_BACKLINKSOutput {
  /**
   * Detailed list of backlinks with anchor text and status
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain or URL to analyze
 */
export type String_1 = string;

export interface DATAFORSEO_GET_BACKLINKS_OVERVIEWInput {
  target: String_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_BACKLINKS_OVERVIEWOutput {
  /**
   * Backlinks overview including total counts and metrics
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Search keyword to analyze
 */
export type String_2 = string;
/**
 * Language code (e.g., 'en')
 */
export type String_3 = string;
/**
 * Location code (e.g., 2840 for US)
 */
export type Number_2 = number;
/**
 * Sort order
 */
export type String_4 = "relevance" | "date";
/**
 * Time range filter
 */
export type String_5 = "all" | "1h" | "1d" | "1w" | "1m" | "1y";

export interface DATAFORSEO_GET_NEWS_SERPInput {
  keyword: String_2;
  languageCode?: String_3;
  locationCode?: Number_2;
  sortBy?: String_4;
  timeRange?: String_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_NEWS_SERPOutput {
  /**
   * News results with titles, sources, and timestamps
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Search keyword to analyze
 */
export type String_6 = string;
/**
 * Language code (e.g., 'en')
 */
export type String_7 = string;
/**
 * Location code (e.g., 2840 for US)
 */
export type Number_3 = number;
/**
 * Device type
 */
export type String_8 = "desktop" | "mobile";
/**
 * Number of results to return
 */
export type Number_4 = number;

export interface DATAFORSEO_GET_ORGANIC_SERPInput {
  keyword: String_6;
  languageCode?: String_7;
  locationCode?: Number_3;
  device?: String_8;
  depth?: Number_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_ORGANIC_SERPOutput {
  /**
   * SERP data with rankings, URLs, titles, and descriptions
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain or URL to analyze
 */
export type String_9 = string;
/**
 * Maximum number of results
 */
export type Number_5 = number;
/**
 * Offset for pagination
 */
export type Number_6 = number;

export interface DATAFORSEO_GET_REFERRING_DOMAINSInput {
  target: String_9;
  limit?: Number_5;
  offset?: Number_6;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_REFERRING_DOMAINSOutput {
  /**
   * List of referring domains with ranks and backlink counts
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_10 = string;
/**
 * Seed keywords to find related terms
 */
export type Array = String_10[];
/**
 * Language name (e.g., 'English')
 */
export type String_11 = string;
/**
 * Location name (e.g., 'United States')
 */
export type String_12 = string;
/**
 * Depth of keyword expansion (1-10)
 */
export type Number_7 = number;
/**
 * Maximum number of results
 */
export type Number_8 = number;

export interface DATAFORSEO_GET_RELATED_KEYWORDSInput {
  keywords: Array;
  languageName?: String_11;
  locationName?: String_12;
  depth?: Number_7;
  limit?: Number_8;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_RELATED_KEYWORDSOutput {
  /**
   * Related keywords with search volume and metrics
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_13 = string;
/**
 * Array of keywords to analyze
 */
export type Array_1 = String_13[];
/**
 * Language name (e.g., 'English')
 */
export type String_14 = string;
/**
 * Location name (e.g., 'United States')
 */
export type String_15 = string;
/**
 * Language code (e.g., 'en')
 */
export type String_16 = string;
/**
 * Location code (e.g., 2840 for US)
 */
export type Number_9 = number;

export interface DATAFORSEO_GET_SEARCH_VOLUMEInput {
  keywords: Array_1;
  languageName?: String_14;
  locationName?: String_15;
  languageCode?: String_16;
  locationCode?: Number_9;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_SEARCH_VOLUMEOutput {
  /**
   * Search volume data including CPC, competition, and trends
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain to analyze
 */
export type String_17 = string;
/**
 * Maximum number of results
 */
export type Number_10 = number;
/**
 * Offset for pagination
 */
export type Number_11 = number;

export interface DATAFORSEO_GET_TRAFFIC_BY_COUNTRYInput {
  target: String_17;
  limit?: Number_10;
  offset?: Number_11;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_TRAFFIC_BY_COUNTRYOutput {
  /**
   * Traffic distribution by country
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain to analyze
 */
export type String_18 = string;
/**
 * Maximum number of results
 */
export type Number_12 = number;
/**
 * Offset for pagination
 */
export type Number_13 = number;

export interface DATAFORSEO_GET_TRAFFIC_BY_PAGESInput {
  target: String_18;
  limit?: Number_12;
  offset?: Number_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_TRAFFIC_BY_PAGESOutput {
  /**
   * Traffic metrics for individual pages
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain to analyze
 */
export type String_19 = string;

export interface DATAFORSEO_GET_TRAFFIC_BY_SOURCESInput {
  target: String_19;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_TRAFFIC_BY_SOURCESOutput {
  /**
   * Traffic breakdown by source (direct, organic, paid, etc)
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target domain to analyze
 */
export type String_20 = string;

export interface DATAFORSEO_GET_TRAFFIC_OVERVIEWInput {
  target: String_20;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATAFORSEO_GET_TRAFFIC_OVERVIEWOutput {
  /**
   * Traffic overview with visits, bounce rate, and metrics
   */
  data?: {
    [k: string]: unknown;
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_21 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_21;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_22 = string;
export type Array_2 = String_22[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_23 = string;
export type String_24 = string;
export type String_25 = string;
export type String_26 = string;
export type String_27 = string;
export type String_28 = string;
export type String_29 = string;
export type String_30 = string;
export type String_31 = string;
export type Array_4 = String_31[];
export type String_32 = string;
export type String_33 = "none" | "open" | "autoPin";
export type Array_3 = Object[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_3;
}
export interface Object {
  id?: String_23;
  name?: String_24;
  title: String_25;
  description?: String_26;
  icon: String_27;
  url?: String_28;
  mimeTypePattern?: String_29;
  resourceName?: String_30;
  tools?: Array_4;
  prompt?: String_32;
  installBehavior?: String_33;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_34 = string;
export type StringNull = String_35 | Null;
export type String_35 = string;
export type Null = null;
export type StringNull_1 = String_36 | Null_1;
export type String_36 = string;
export type Null_1 = null;
export type String_37 = string;

export interface GET_USEROutput {
  id: String_34;
  name: StringNull;
  avatar: StringNull_1;
  email: String_37;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  login: z
    .string()
    .describe(
      "DataForSEO API Login from https://app.dataforseo.com/api-access",
    ),
  password: z
    .string()
    .describe(
      "DataForSEO API Password/Token from https://app.dataforseo.com/api-access (NOT your account password)",
    ),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  SELF: Mcp<{
    /**
     * Get a detailed list of backlinks for a domain or URL. Returns source URLs, anchor text, follow/nofollow status, and more.
     */
    DATAFORSEO_GET_BACKLINKS: (
      input: DATAFORSEO_GET_BACKLINKSInput,
    ) => Promise<DATAFORSEO_GET_BACKLINKSOutput>;
    /**
     * Get an overview of backlinks data for a domain. Returns total backlinks, referring domains, domain rank, and other key metrics.
     */
    DATAFORSEO_GET_BACKLINKS_OVERVIEW: (
      input: DATAFORSEO_GET_BACKLINKS_OVERVIEWInput,
    ) => Promise<DATAFORSEO_GET_BACKLINKS_OVERVIEWOutput>;
    /**
     * Get Google News search results. Returns news articles with titles, sources, timestamps, and snippets.
     */
    DATAFORSEO_GET_NEWS_SERP: (
      input: DATAFORSEO_GET_NEWS_SERPInput,
    ) => Promise<DATAFORSEO_GET_NEWS_SERPOutput>;
    /**
     * Get organic search results from Google SERP. Returns detailed SERP data including rankings, URLs, titles, and descriptions.
     */
    DATAFORSEO_GET_ORGANIC_SERP: (
      input: DATAFORSEO_GET_ORGANIC_SERPInput,
    ) => Promise<DATAFORSEO_GET_ORGANIC_SERPOutput>;
    /**
     * Get list of domains linking to target. Returns domain ranks, number of backlinks per domain, and dofollow counts.
     */
    DATAFORSEO_GET_REFERRING_DOMAINS: (
      input: DATAFORSEO_GET_REFERRING_DOMAINSInput,
    ) => Promise<DATAFORSEO_GET_REFERRING_DOMAINSOutput>;
    /**
     * Get keyword suggestions related to seed keywords. Returns related terms with search volume and competition data.
     */
    DATAFORSEO_GET_RELATED_KEYWORDS: (
      input: DATAFORSEO_GET_RELATED_KEYWORDSInput,
    ) => Promise<DATAFORSEO_GET_RELATED_KEYWORDSOutput>;
    /**
     * Get search volume, CPC, and competition data for keywords. Returns detailed metrics including monthly search trends.
     */
    DATAFORSEO_GET_SEARCH_VOLUME: (
      input: DATAFORSEO_GET_SEARCH_VOLUMEInput,
    ) => Promise<DATAFORSEO_GET_SEARCH_VOLUMEOutput>;
    /**
     * Get traffic distribution by country. Returns visits and percentage per country.
     */
    DATAFORSEO_GET_TRAFFIC_BY_COUNTRY: (
      input: DATAFORSEO_GET_TRAFFIC_BY_COUNTRYInput,
    ) => Promise<DATAFORSEO_GET_TRAFFIC_BY_COUNTRYOutput>;
    /**
     * Get traffic metrics for individual pages. Returns page views, unique visitors, bounce rate, and average time on page.
     */
    DATAFORSEO_GET_TRAFFIC_BY_PAGES: (
      input: DATAFORSEO_GET_TRAFFIC_BY_PAGESInput,
    ) => Promise<DATAFORSEO_GET_TRAFFIC_BY_PAGESOutput>;
    /**
     * Get traffic breakdown by source. Returns distribution across direct, organic search, paid search, referral, social, mail, and display ads.
     */
    DATAFORSEO_GET_TRAFFIC_BY_SOURCES: (
      input: DATAFORSEO_GET_TRAFFIC_BY_SOURCESInput,
    ) => Promise<DATAFORSEO_GET_TRAFFIC_BY_SOURCESOutput>;
    /**
     * Get website traffic overview metrics. Returns visits, unique visitors, bounce rate, pages per visit, and average visit duration.
     */
    DATAFORSEO_GET_TRAFFIC_OVERVIEW: (
      input: DATAFORSEO_GET_TRAFFIC_OVERVIEWInput,
    ) => Promise<DATAFORSEO_GET_TRAFFIC_OVERVIEWOutput>;
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
  }>;
}

export const Scopes = {};
