#!/usr/bin/env bun
/**
 * Script to generate the allowlist of MCP servers
 *
 * This script fetches ALL servers from the registry, applies filters
 * (remotes, blacklist, excluded words), and generates an allowlist file.
 *
 * Usage:
 *   bun run scripts/generate-allowlist.ts
 */

import { BLACKLISTED_SERVERS } from "../server/lib/blacklist.ts";

const REGISTRY_URL = "https://registry.modelcontextprotocol.io/v0.1/servers";

interface RegistryServer {
  server: {
    name: string;
    version: string;
    remotes?: Array<{ type: string; url: string }>;
  };
  _meta: Record<string, unknown>;
}

interface RegistryResponse {
  servers: RegistryServer[];
  metadata: {
    nextCursor?: string;
  };
}

// Words to exclude from server names
const EXCLUDED_WORDS = ["local", "test", "demo", "example"];

function hasExcludedWord(name: string): boolean {
  return EXCLUDED_WORDS.some((word) => name.toLowerCase().includes(word));
}

async function fetchAllServers(): Promise<RegistryServer[]> {
  const allServers: RegistryServer[] = [];
  let cursor: string | undefined;
  let pageCount = 0;

  console.log("🔍 Fetching all servers from registry...\n");

  do {
    const url = new URL(REGISTRY_URL);
    url.searchParams.set("limit", "100");
    url.searchParams.set("version", "latest");
    if (cursor) {
      url.searchParams.set("cursor", cursor);
    }

    const response = await fetch(url.toString());
    if (!response.ok) {
      throw new Error(`Failed to fetch: ${response.status}`);
    }

    const data: RegistryResponse = await response.json();
    allServers.push(...data.servers);
    cursor = data.metadata.nextCursor;
    pageCount++;

    console.log(
      `   Page ${pageCount}: +${data.servers.length} servers (total: ${allServers.length})`,
    );
  } while (cursor);

  console.log(`\n✅ Total servers fetched: ${allServers.length}`);
  return allServers;
}

function applyFilters(servers: RegistryServer[]): string[] {
  console.log("\n🔧 Applying filters...");

  // Filter 1: Must have remotes
  const withRemotes = servers.filter(
    (s) =>
      s.server.remotes &&
      Array.isArray(s.server.remotes) &&
      s.server.remotes.length > 0,
  );
  console.log(`   With remotes: ${withRemotes.length}`);

  // Filter 2: Not in blacklist
  const notBlacklisted = withRemotes.filter(
    (s) => !BLACKLISTED_SERVERS.includes(s.server.name),
  );
  console.log(`   Not blacklisted: ${notBlacklisted.length}`);

  // Filter 3: No excluded words
  const noExcludedWords = notBlacklisted.filter(
    (s) => !hasExcludedWord(s.server.name),
  );
  console.log(`   No excluded words: ${noExcludedWords.length}`);

  // Extract names and sort
  const names = noExcludedWords.map((s) => s.server.name).sort();

  console.log(`\n✅ Final allowlist: ${names.length} servers`);
  return names;
}

function generateAllowlistFile(names: string[]): string {
  const timestamp = new Date().toISOString();

  return `/**
 * Allowlist of MCP servers that passed all filters
 *
 * Generated: ${timestamp}
 * Total servers: ${names.length}
 *
 * This file is auto-generated by: bun run scripts/generate-allowlist.ts
 * DO NOT EDIT MANUALLY
 */

export const ALLOWED_SERVERS: string[] = [
${names.map((name) => `  "${name}",`).join("\n")}
];

/**
 * Set for O(1) lookup
 */
export const ALLOWED_SERVERS_SET = new Set(ALLOWED_SERVERS);

/**
 * Check if a server is in the allowlist
 */
export function isServerAllowed(name: string): boolean {
  return ALLOWED_SERVERS_SET.has(name);
}

/**
 * Get server at specific index (for pagination)
 */
export function getServerAtIndex(index: number): string | undefined {
  return ALLOWED_SERVERS[index];
}

/**
 * Get a slice of server names (for pagination)
 */
export function getServersSlice(start: number, end: number): string[] {
  return ALLOWED_SERVERS.slice(start, end);
}

/**
 * Total count of allowed servers
 */
export const ALLOWED_SERVERS_COUNT = ALLOWED_SERVERS.length;
`;
}

async function main() {
  console.log("═══════════════════════════════════════════════════════════");
  console.log("           MCP Registry Allowlist Generator");
  console.log("═══════════════════════════════════════════════════════════\n");

  try {
    // Fetch all servers
    const allServers = await fetchAllServers();

    // Apply filters
    const allowedNames = applyFilters(allServers);

    // Generate file content
    const fileContent = generateAllowlistFile(allowedNames);

    // Write to file
    const outputPath = new URL("../server/lib/allowlist.ts", import.meta.url)
      .pathname;
    await Bun.write(outputPath, fileContent);

    console.log(`\n📁 Allowlist written to: ${outputPath}`);
    console.log(
      "\n═══════════════════════════════════════════════════════════",
    );
    console.log("                        DONE!");
    console.log(
      "═══════════════════════════════════════════════════════════\n",
    );

    // Show some stats
    console.log("📊 Summary:");
    console.log(`   Total in registry: ${allServers.length}`);
    console.log(`   Allowed (passed filters): ${allowedNames.length}`);
    console.log(`   Filtered out: ${allServers.length - allowedNames.length}`);
    console.log(
      `   Filter rate: ${(((allServers.length - allowedNames.length) / allServers.length) * 100).toFixed(1)}%`,
    );
  } catch (error) {
    console.error("\n❌ Error:", error);
    process.exit(1);
  }
}

main();
