/**
 * Design System Generator Utilities
 *
 * Pure functions for generating CSS, JSX, and style guides from brand identity.
 */
import type { BrandIdentity } from "./research.ts";

// Helper functions
export function lightenColor(hex: string, percent: number): string {
  const num = parseInt(hex.replace("#", ""), 16);
  const amt = Math.round(2.55 * percent);
  const R = Math.min(255, (num >> 16) + amt);
  const G = Math.min(255, ((num >> 8) & 0x00ff) + amt);
  const B = Math.min(255, (num & 0x0000ff) + amt);
  return `#${((1 << 24) + (R << 16) + (G << 8) + B).toString(16).slice(1)}`;
}

export function darkenColor(hex: string, percent: number): string {
  const num = parseInt(hex.replace("#", ""), 16);
  const amt = Math.round(2.55 * percent);
  const R = Math.max(0, (num >> 16) - amt);
  const G = Math.max(0, ((num >> 8) & 0x00ff) - amt);
  const B = Math.max(0, (num & 0x0000ff) - amt);
  return `#${((1 << 24) + (R << 16) + (G << 8) + B).toString(16).slice(1)}`;
}

/**
 * Generate CSS variables from brand identity
 */
export function generateCSSVariables(identity: BrandIdentity): string {
  const colors = identity.colors || { primary: "#8B5CF6" };
  const typography = identity.typography || {};

  return `/**
 * ${identity.name} Design System
 * Generated by Brand MCP
 */

:root {
  /* Primary Colors */
  --brand-primary: ${colors.primary};
  --brand-primary-light: ${lightenColor(colors.primary, 20)};
  --brand-primary-dark: ${darkenColor(colors.primary, 20)};
  
  /* Secondary Colors */
  --brand-secondary: ${colors.secondary || colors.primary};
  --brand-accent: ${colors.accent || colors.primary};
  
  /* Background Colors */
  --bg-dark: ${colors.background || "#1a1a1a"};
  --bg-light: #FFFFFF;
  --bg-gray: #F5F5F5;
  
  /* Text Colors */
  --text-primary: ${colors.text || "#1A1A1A"};
  --text-secondary: #6B7280;
  --text-light: #FFFFFF;
  --text-muted: #9CA3AF;
  
  /* Typography */
  --font-heading: ${typography.headingFont || "'Inter', system-ui, sans-serif"};
  --font-body: ${typography.bodyFont || "'Inter', system-ui, sans-serif"};
  --font-mono: ${typography.monoFont || "'JetBrains Mono', monospace"};
  
  /* Spacing */
  --spacing-xs: 0.25rem;
  --spacing-sm: 0.5rem;
  --spacing-md: 1rem;
  --spacing-lg: 1.5rem;
  --spacing-xl: 2rem;
  --spacing-2xl: 3rem;
  
  /* Border Radius */
  --radius-sm: 0.25rem;
  --radius-md: 0.5rem;
  --radius-lg: 1rem;
  --radius-full: 9999px;
  
  /* Shadows */
  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.05);
  --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.1);
  --shadow-lg: 0 10px 15px rgba(0, 0, 0, 0.1);
}

/* Dark Mode */
[data-theme="dark"] {
  --bg-dark: #0f0f0f;
  --bg-light: #1a1a1a;
  --bg-gray: #2a2a2a;
  --text-primary: #FFFFFF;
  --text-secondary: #9CA3AF;
}
`;
}

/**
 * Generate JSX design system components
 */
export function generateDesignSystemJSX(identity: BrandIdentity): string {
  const colors = identity.colors || { primary: "#8B5CF6" };
  const logos = identity.logos || {};
  const typography = identity.typography || {};

  return `/**
 * ${identity.name} Design System
 * 
 * Auto-generated design system with brand components.
 */

const BRAND = {
  name: "${identity.name}",
  tagline: "${identity.tagline || ""}",
  
  colors: {
    primary: "${colors.primary}",
    primaryLight: "${lightenColor(colors.primary, 20)}",
    primaryDark: "${darkenColor(colors.primary, 20)}",
    secondary: "${colors.secondary || colors.primary}",
    accent: "${colors.accent || colors.primary}",
    background: "${colors.background || "#1a1a1a"}",
    text: "${colors.text || "#1A1A1A"}",
    textLight: "#FFFFFF",
    textMuted: "#6B7280",
  },
  
  logos: {
    primary: ${logos.primary ? `"${logos.primary}"` : "null"},
    light: ${logos.light ? `"${logos.light}"` : "null"},
    dark: ${logos.dark ? `"${logos.dark}"` : "null"},
    icon: ${logos.icon ? `"${logos.icon}"` : "null"},
  },
  
  typography: {
    heading: "${typography.headingFont || "Inter, system-ui, sans-serif"}",
    body: "${typography.bodyFont || "Inter, system-ui, sans-serif"}",
    mono: "${typography.monoFont || "JetBrains Mono, monospace"}",
  },
  
  hasImageLogo: ${Boolean(logos.primary)},
};

function BrandLogo({ variant = "primary", height = 40 }) {
  const logoUrl = variant === "light" ? BRAND.logos.light :
                  variant === "dark" ? BRAND.logos.dark :
                  BRAND.logos.primary;
  
  if (logoUrl) {
    return <img src={logoUrl} alt={BRAND.name} style={{ height, width: "auto" }} />;
  }
  
  return (
    <span style={{ fontSize: height * 0.6, fontWeight: 700, color: BRAND.colors.primary }}>
      {BRAND.name}
    </span>
  );
}

function Heading({ level = 1, children, color = "primary" }) {
  const Tag = \`h\${level}\`;
  const sizes = { 1: "3rem", 2: "2.25rem", 3: "1.875rem", 4: "1.5rem" };
  const colors = { primary: BRAND.colors.text, brand: BRAND.colors.primary, light: "#FFFFFF" };
  
  return <Tag style={{ fontFamily: BRAND.typography.heading, fontSize: sizes[level], color: colors[color] }}>{children}</Tag>;
}

function Button({ variant = "primary", children }) {
  const styles = {
    primary: { backgroundColor: BRAND.colors.primary, color: "#FFFFFF" },
    secondary: { backgroundColor: "transparent", color: BRAND.colors.primary, border: \`2px solid \${BRAND.colors.primary}\` },
  };
  
  return <button style={{ ...styles[variant], padding: "0.75rem 1.5rem", borderRadius: "0.5rem", fontWeight: 600 }}>{children}</button>;
}

export { BRAND, BrandLogo, Heading, Button };
`;
}

/**
 * Generate style guide markdown
 */
export function generateStyleGuide(identity: BrandIdentity): string {
  const colors = identity.colors || { primary: "#8B5CF6" };
  const typography = identity.typography || {};
  const voice = identity.voice || {};

  return `# ${identity.name} Brand Style Guide

${identity.description ? `> ${identity.description}` : ""}
${identity.tagline ? `**Tagline:** "${identity.tagline}"` : ""}

---

## Color Palette

### Primary Colors

| Color | Hex | Usage |
|-------|-----|-------|
| Primary | \`${colors.primary}\` | Main brand color, CTAs, links |
| Primary Light | \`${lightenColor(colors.primary, 20)}\` | Hover states, backgrounds |
| Primary Dark | \`${darkenColor(colors.primary, 20)}\` | Active states, emphasis |

${
  colors.secondary
    ? `### Secondary Colors

| Color | Hex | Usage |
|-------|-----|-------|
| Secondary | \`${colors.secondary}\` | Supporting elements |
${colors.accent ? `| Accent | \`${colors.accent}\` | Highlights, notifications |` : ""}`
    : ""
}

---

## Typography

### Font Families

- **Headings:** ${typography.headingFont || "Inter, system-ui, sans-serif"}
- **Body:** ${typography.bodyFont || "Inter, system-ui, sans-serif"}
${typography.monoFont ? `- **Monospace:** ${typography.monoFont}` : ""}

### Type Scale

| Element | Size | Weight |
|---------|------|--------|
| H1 | 3rem (48px) | Bold (700) |
| H2 | 2.25rem (36px) | Bold (700) |
| H3 | 1.875rem (30px) | Semibold (600) |
| Body | 1rem (16px) | Regular (400) |

---

## Logo Usage

${
  identity.logos?.primary
    ? `### Primary Logo

![${identity.name} Logo](${identity.logos.primary})

- Use on light backgrounds
- Maintain clear space equal to the height of the logo`
    : `### Logo

*Logo URL not available. Please provide logo assets.*`
}

---

${
  voice.tone || voice.personality?.length
    ? `## Brand Voice

${voice.tone ? `**Tone:** ${voice.tone}` : ""}
${voice.personality?.length ? `**Personality:** ${voice.personality.join(", ")}` : ""}

---`
    : ""
}

*Generated by Brand MCP*
`;
}
