// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type Array = String_1[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_2 = string;
export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type String_6 = string;
export type String_7 = string;
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;
export type Array_2 = String_10[];
export type String_11 = string;
export type String_12 = "none" | "open" | "autoPin";
export type Array_1 = Object[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_1;
}
export interface Object {
  id?: String_2;
  name?: String_3;
  title: String_4;
  description?: String_5;
  icon: String_6;
  url?: String_7;
  mimeTypePattern?: String_8;
  resourceName?: String_9;
  tools?: Array_2;
  prompt?: String_11;
  installBehavior?: String_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object key/path to delete
 */
export type String_13 = string;

export interface DELETE_OBJECTInput {
  key: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the deletion was successful
 */
export type Boolean_1 = boolean;
/**
 * The key that was deleted
 */
export type String_14 = string;

export interface DELETE_OBJECTOutput {
  success: Boolean_1;
  key: String_14;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_15 = string;
/**
 * Array of object keys/paths to delete (max 1000)
 *
 * @maxItems 1000
 */
export type Array_3 = String_15[];

export interface DELETE_OBJECTSInput {
  keys: Array_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_16 = string;
/**
 * Array of successfully deleted keys
 */
export type Array_4 = String_16[];
export type String_17 = string;
export type String_18 = string;
/**
 * Array of errors for failed deletions
 */
export type Array_5 = Object_1[];

export interface DELETE_OBJECTSOutput {
  deleted: Array_4;
  errors: Array_5;
}
export interface Object_1 {
  key: String_17;
  message: String_18;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object key/path to get metadata for
 */
export type String_19 = string;

export interface GET_OBJECT_METADATAInput {
  key: String_19;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * MIME type of the object
 */
export type String_20 = string;
/**
 * Size of the object in bytes
 */
export type Number = number;
/**
 * Last modified timestamp
 */
export type String_21 = string;
/**
 * Entity tag for the object
 */
export type String_22 = string;
export type String_23 = string;

export interface GET_OBJECT_METADATAOutput {
  contentType?: String_20;
  contentLength: Number;
  lastModified: String_21;
  etag: String_22;
  metadata?: Object_2;
}
/**
 * Custom metadata key-value pairs
 */
export interface Object_2 {
  [k: string]: String_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object key/path to generate URL for
 */
export type String_24 = string;
/**
 * URL expiration time in seconds (default: from state config or 3600)
 */
export type Number_1 = number;

export interface GET_PRESIGNED_URLInput {
  key: String_24;
  expiresIn?: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Presigned URL for downloading the object
 */
export type String_25 = string;
/**
 * Expiration time in seconds that was used
 */
export type Number_2 = number;

export interface GET_PRESIGNED_URLOutput {
  url: String_25;
  expiresIn: Number_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_26 = string;
export type StringNull = String_27 | Null;
export type String_27 = string;
export type Null = null;
export type StringNull_1 = String_28 | Null_1;
export type String_28 = string;
export type Null_1 = null;
export type String_29 = string;

export interface GET_USEROutput {
  id: String_26;
  name: StringNull;
  avatar: StringNull_1;
  email: String_29;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Filter objects by prefix (e.g., 'folder/' for folder contents)
 */
export type String_30 = string;
/**
 * Maximum number of keys to return (default: 1000)
 */
export type Number_3 = number;
/**
 * Token for pagination from previous response
 */
export type String_31 = string;

export interface LIST_OBJECTSInput {
  prefix?: String_30;
  maxKeys?: Number_3;
  continuationToken?: String_31;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object key/path
 */
export type String_32 = string;
/**
 * Object size in bytes
 */
export type Number_4 = number;
/**
 * Last modified timestamp
 */
export type String_33 = string;
/**
 * Entity tag for the object
 */
export type String_34 = string;
export type Array_6 = Object_3[];
/**
 * Token for fetching next page of results
 */
export type String_35 = string;
/**
 * Whether there are more results available
 */
export type Boolean_2 = boolean;

export interface LIST_OBJECTSOutput {
  objects: Array_6;
  nextContinuationToken?: String_35;
  isTruncated: Boolean_2;
}
export interface Object_3 {
  key: String_32;
  size: Number_4;
  lastModified: String_33;
  etag: String_34;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object key/path for the upload
 */
export type String_36 = string;
/**
 * URL expiration time in seconds (default: from state config or 3600)
 */
export type Number_5 = number;
/**
 * MIME type for the object being uploaded
 */
export type String_37 = string;

export interface PUT_PRESIGNED_URLInput {
  key: String_36;
  expiresIn?: Number_5;
  contentType?: String_37;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Presigned URL for uploading the object
 */
export type String_38 = string;
/**
 * Expiration time in seconds that was used
 */
export type Number_6 = number;

export interface PUT_PRESIGNED_URLOutput {
  url: String_38;
  expiresIn: Number_6;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Delete a single object from the bucket
     */
    DELETE_OBJECT: (input: DELETE_OBJECTInput) => Promise<DELETE_OBJECTOutput>;
    /**
     * Delete multiple objects in a single batch operation (max 1000 objects)
     */
    DELETE_OBJECTS: (
      input: DELETE_OBJECTSInput,
    ) => Promise<DELETE_OBJECTSOutput>;
    /**
     * Get metadata for an object without downloading it (HEAD operation)
     */
    GET_OBJECT_METADATA: (
      input: GET_OBJECT_METADATAInput,
    ) => Promise<GET_OBJECT_METADATAOutput>;
    /**
     * Generate a presigned URL for downloading an object. The URL allows temporary access without credentials.
     */
    GET_PRESIGNED_URL: (
      input: GET_PRESIGNED_URLInput,
    ) => Promise<GET_PRESIGNED_URLOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * List objects in the S3 bucket. Supports prefix filtering and pagination for large buckets.
     */
    LIST_OBJECTS: (input: LIST_OBJECTSInput) => Promise<LIST_OBJECTSOutput>;
    /**
     * Generate a presigned URL for uploading an object. The URL allows temporary upload access without credentials.
     */
    PUT_PRESIGNED_URL: (
      input: PUT_PRESIGNED_URLInput,
    ) => Promise<PUT_PRESIGNED_URLOutput>;
  }>;
}

export const Scopes = {};
