/**
 * Reusable codegen helper for "official Google MCP wrapper" packages.
 *
 * Each wrapper has a `server/scripts/generate-tools.ts` that imports this
 * helper, passes its backend URL(s), and emits per-backend snapshot JSONs and
 * a TOOLS.md preview alongside.
 *
 * The script needs no Google credentials — both `tools/list` and the RFC 9728
 * PRM endpoint are reachable without auth.
 */

import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

interface JsonRpcResponse {
  jsonrpc: "2.0";
  id: number | string;
  result?: { tools: unknown[] };
  error?: { code: number; message: string };
}

interface ProtectedResourceMetadata {
  resource?: string;
  authorization_servers?: string[];
  scopes_supported?: string[];
}

interface BackendTool {
  name: string;
  description?: string;
}

export interface BackendDescriptor {
  /** Logical name. Used as the snapshot file name and as the tool prefix when multi-backend. */
  service: string;
  /** Endpoint speaking MCP JSON-RPC. */
  url: string;
}

export interface GenerateSnapshotsOptions {
  /** One or more backends to fetch and snapshot. */
  backends: BackendDescriptor[];
  /** Directory where `<service>.json` and `_index.json` are written. */
  outDir: string;
  /** Path of the markdown file to render with the catalog. */
  toolsMarkdownPath: string;
  /** Title used at the top of the generated markdown. */
  title: string;
  /**
   * Whether to emit prefixed names in TOOLS.md (`calendar_list_events`).
   * Set true for multi-backend wrappers, false for single-backend.
   */
  prefixed?: boolean;
}

async function fetchToolsList(url: string): Promise<unknown[]> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json, text/event-stream",
    },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/list" }),
  });
  if (!res.ok) {
    throw new Error(
      `${url} tools/list HTTP ${res.status}: ${await res.text()}`,
    );
  }
  const json = (await res.json()) as JsonRpcResponse;
  if (json.error) {
    throw new Error(`${url} tools/list error: ${json.error.message}`);
  }
  return json.result?.tools ?? [];
}

async function fetchScopes(url: string): Promise<string[]> {
  const u = new URL(url);
  const prmUrl = `${u.origin}/.well-known/oauth-protected-resource${u.pathname}`;
  const res = await fetch(prmUrl, { headers: { Accept: "application/json" } });
  if (!res.ok) {
    throw new Error(`${prmUrl} HTTP ${res.status}: ${await res.text()}`);
  }
  const prm = (await res.json()) as ProtectedResourceMetadata;
  return prm.scopes_supported ?? [];
}

function renderMarkdown(
  title: string,
  snapshots: Record<
    string,
    { url: string; scopes: string[]; tools: BackendTool[] }
  >,
  prefixed: boolean,
): string {
  const services = Object.keys(snapshots);
  const total = services.reduce((acc, svc) => {
    const seen = new Set(snapshots[svc].tools.map((t) => t.name));
    return acc + seen.size;
  }, 0);
  const allScopes = Array.from(
    new Set(services.flatMap((svc) => snapshots[svc].scopes)),
  ).sort();

  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push("");
  lines.push(
    "_Auto-generated by `bun run generate-tools`. Do not edit by hand._",
  );
  lines.push("");
  lines.push(
    `${total} tool${total === 1 ? "" : "s"} across ${services.length} backend${services.length === 1 ? "" : "s"}, gated behind ${allScopes.length} OAuth scope${allScopes.length === 1 ? "" : "s"}.`,
  );
  lines.push("");

  if (prefixed) {
    lines.push(
      "Tool names below are listed without the service prefix. The MCP exposes them as `<service>_<name>`.",
    );
    lines.push("");
  }

  for (const service of services) {
    const snap = snapshots[service];
    const seen = new Set<string>();
    const unique = snap.tools.filter((t) => {
      if (seen.has(t.name)) return false;
      seen.add(t.name);
      return true;
    });

    if (services.length > 1) {
      lines.push(`## ${service}`);
      lines.push("");
    }
    lines.push(`**Endpoint:** \`${snap.url}\``);
    lines.push("");
    lines.push("**Scopes:**");
    for (const scope of snap.scopes) lines.push(`- \`${scope}\``);
    lines.push("");
    lines.push(`**Tools (${unique.length}):**`);
    for (const tool of unique) {
      const firstLine = (tool.description ?? "").split("\n")[0].trim();
      lines.push(`- \`${tool.name}\`${firstLine ? ` — ${firstLine}` : ""}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export async function generateSnapshots(
  opts: GenerateSnapshotsOptions,
): Promise<void> {
  await mkdir(opts.outDir, { recursive: true });

  const indexEntries: Record<
    string,
    { scopes: string[]; toolNames: string[] }
  > = {};
  const snapshotsForMarkdown: Record<
    string,
    { url: string; scopes: string[]; tools: BackendTool[] }
  > = {};

  for (const backend of opts.backends) {
    process.stdout.write(`fetching ${backend.service} (${backend.url})... `);
    const [tools, scopes] = await Promise.all([
      fetchToolsList(backend.url),
      fetchScopes(backend.url),
    ]);
    const snap = { service: backend.service, url: backend.url, scopes, tools };
    await writeFile(
      join(opts.outDir, `${backend.service}.json`),
      JSON.stringify(snap, null, 2) + "\n",
    );
    indexEntries[backend.service] = {
      scopes,
      toolNames: tools.map((t) => (t as { name: string }).name),
    };
    snapshotsForMarkdown[backend.service] = {
      url: backend.url,
      scopes,
      tools: tools as BackendTool[],
    };
    console.log(`${tools.length} tools, ${scopes.length} scopes`);
  }

  await writeFile(
    join(opts.outDir, "_index.json"),
    JSON.stringify(indexEntries, null, 2) + "\n",
  );

  await writeFile(
    opts.toolsMarkdownPath,
    renderMarkdown(opts.title, snapshotsForMarkdown, opts.prefixed ?? false),
  );

  console.log(`\nWrote ${opts.backends.length} snapshot(s) to ${opts.outDir}`);
  console.log(`Wrote tool catalog to ${opts.toolsMarkdownPath}`);
}
