// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type Number = number;
export type Array = Object[];

export interface CONTRACT_AUTHORIZEInput {
  clauses: Array;
}
export interface Object {
  clauseId: String;
  amount: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type String_2 = string;
export type Number_1 = number;

export interface CONTRACT_AUTHORIZEOutput {
  transactionId: String_1;
  totalAmount: String_2;
  timestamp: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CONTRACT_GETInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type StringNumber = String_6 | Number_2;
export type String_6 = string;
export type Number_2 = number;
export type String_7 = string;
export type String_8 = string;
export type Array_2 = String_8[];
export type Array_1 = Object_2[];

export interface CONTRACT_GETOutput {
  appName?: String_3;
  contract: Object_1;
}
export interface Object_1 {
  body?: String_4;
  clauses?: Array_1;
}
export interface Object_2 {
  id: String_5;
  price: StringNumber;
  description?: String_7;
  usedByTools?: Array_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_9 = string;
export type String_10 = string;
export type Number_3 = number;
export type Array_3 = Object_3[];
export type Number_4 = number;
export type String_11 = string;

export interface CONTRACT_SETTLEInput {
  transactionId: String_9;
  clauses?: Array_3;
  amount?: Number_4;
  vendorId: String_11;
}
export interface Object_3 {
  clauseId: String_10;
  amount: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_12 = string;

export interface CONTRACT_SETTLEOutput {
  transactionId: String_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_13 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_14 = string;
export type Array_4 = String_14[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_15 = string;

export interface DECO_CHAT_OAUTH_STARTInput_1 {
  returnUrl: String_15;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_16 = string;
export type Array_5 = String_16[];

export interface DECO_CHAT_OAUTH_STARTOutput_1 {
  stateSchema?: unknown;
  scopes?: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_17 = string;
export type String_18 = string;
export type String_19 = string;
export type String_20 = string;
export type String_21 = string;
export type String_22 = string;
export type String_23 = string;
export type String_24 = string;
export type String_25 = string;
export type Array_7 = String_25[];
export type String_26 = string;
export type String_27 = "none" | "open" | "autoPin";
export type Array_6 = Object_4[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_6;
}
export interface Object_4 {
  id?: String_17;
  name?: String_18;
  title: String_19;
  description?: String_20;
  icon: String_21;
  url?: String_22;
  mimeTypePattern?: String_23;
  resourceName?: String_24;
  tools?: Array_7;
  prompt?: String_26;
  installBehavior?: String_27;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_28 = string;
export type StringNull = String_29 | Null;
export type String_29 = string;
export type Null = null;
export type StringNull_1 = String_30 | Null_1;
export type String_30 = string;
export type Null_1 = null;
export type String_31 = string;

export interface GET_USEROutput {
  id: String_28;
  name: StringNull;
  avatar: StringNull_1;
  email: String_31;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * URL of the audio file to transcribe
 */
export type String_32 = string;
/**
 * Language code (e.g., 'en', 'pt', 'es'). Auto-detected if not provided
 */
export type String_33 = string;
/**
 * Optional prompt to guide the transcription style
 */
export type String_34 = string;
/**
 * Format of the transcription response
 */
export type String_35 = "json" | "text" | "srt" | "verbose_json" | "vtt";
/**
 * Sampling temperature between 0 and 1
 */
export type Number_5 = number;
export type String_36 = "word" | "segment";
/**
 * Timestamp granularities for verbose_json format
 */
export type Array_8 = String_36[];

export interface TRANSCRIBE_AUDIOInput {
  audioUrl: String_32;
  language?: String_33;
  prompt?: String_34;
  responseFormat?: String_35;
  temperature?: Number_5;
  timestampGranularities?: Array_8;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The transcribed text
 */
export type String_37 = string;
/**
 * Detected language
 */
export type String_38 = string;
/**
 * Audio duration in seconds
 */
export type Number_6 = number;
export type Number_7 = number;
export type Number_8 = number;
export type Number_9 = number;
export type String_39 = string;
/**
 * Transcription segments with timestamps
 */
export type Array_9 = Object_5[];
export type String_40 = string;
export type Number_10 = number;
export type Number_11 = number;
/**
 * Individual words with timestamps
 */
export type Array_10 = Object_6[];
/**
 * Whether the request failed
 */
export type Boolean_1 = boolean;
/**
 * Native finish reason
 */
export type String_41 = string;

export interface TRANSCRIBE_AUDIOOutput {
  text?: String_37;
  language?: String_38;
  duration?: Number_6;
  segments?: Array_9;
  words?: Array_10;
  error?: Boolean_1;
  finishReason?: String_41;
}
export interface Object_5 {
  id: Number_7;
  start: Number_8;
  end: Number_9;
  text: String_39;
}
export interface Object_6 {
  word: String_40;
  start: Number_10;
  end: Number_11;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  WHISPER_CONTRACT: z.object({
    value: z.string(),
    __type: z
      .literal("@deco/whisper-6662d891dfbed6addfec1bce9f6ef48c")
      .default("@deco/whisper-6662d891dfbed6addfec1bce9f6ef48c"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  WHISPER_CONTRACT: Mcp<{
    /**
     * Authorize a charge for a contract clause. Creates a single authorization with transactionId.
     */
    CONTRACT_AUTHORIZE: (
      input: CONTRACT_AUTHORIZEInput,
    ) => Promise<CONTRACT_AUTHORIZEOutput>;
    /**
     * Get the current contract state.
     */
    CONTRACT_GET: (input: CONTRACT_GETInput) => Promise<CONTRACT_GETOutput>;
    /**
     * Settle the current authorized charge. Processes the payment for the current authorization.
     */
    CONTRACT_SETTLE: (
      input: CONTRACT_SETTLEInput,
    ) => Promise<CONTRACT_SETTLEOutput>;
    /**
     * Start the OAuth flow for the contract app.
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
  }>;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * Transcribe audio to text using OpenAI Whisper
     */
    TRANSCRIBE_AUDIO: (
      input: TRANSCRIBE_AUDIOInput,
    ) => Promise<TRANSCRIBE_AUDIOOutput>;
  }>;
}

export const Scopes = {
  WHISPER_CONTRACT: {
    CONTRACT_AUTHORIZE: "WHISPER_CONTRACT::CONTRACT_AUTHORIZE",
    CONTRACT_GET: "WHISPER_CONTRACT::CONTRACT_GET",
    CONTRACT_SETTLE: "WHISPER_CONTRACT::CONTRACT_SETTLE",
    DECO_CHAT_OAUTH_START: "WHISPER_CONTRACT::DECO_CHAT_OAUTH_START",
  },
};
