/**
 * Skills Tools
 *
 * Tools to access documentation skills for LLMs.
 * Skills are embedded directly in the code to work in serverless/edge environments.
 */

import { z } from "zod";
import { createPrivateTool } from "@decocms/runtime/tools";
import type { Env } from "../types/env.ts";

/**
 * Embedded skill content - stored directly in code to avoid filesystem issues in production
 */
const WEEKLY_REPORT_PUBLISHING_SKILL = `# Weekly Report Publishing Skill

Skill for publishing Weekly Reports to the \`deco_weekly_report\` database table.

## Overview

This skill teaches how to insert a new Weekly Report into the database using the MCP API. The report is a curated weekly summary of content, generated by an LLM.

## Table Schema

\`\`\`sql
CREATE TABLE "deco_weekly_report" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE,                -- Unique post URL (required)
  title TEXT,                     -- Report title
  source_title TEXT,              -- Source/origin title
  status TEXT,                    -- Status: 'draft', 'published', 'archived'
  created_at TEXT,                -- Creation date (ISO 8601)
  content TEXT,                   -- Full report content (Markdown/HTML)
  slug TEXT,                      -- URL-friendly slug
  summary TEXT,                   -- Short report summary
  key_points TEXT,                -- Key points (stringified JSON array)
  meta_title TEXT,                -- SEO title
  meta_description TEXT,          -- SEO description
  keywords TEXT,                  -- Comma-separated keywords
  category TEXT,                  -- Report category
  tags TEXT,                      -- Comma-separated tags
  author TEXT,                    -- Author name
  reading_time INTEGER,           -- Reading time in minutes
  published_at DATETIME,          -- Publication date
  image_url TEXT,                 -- Cover image URL
  image_alt_text TEXT,            -- Image alt text
  UNIQUE (url)
)
\`\`\`

## Required Fields

| Field | Type | Description |
|-------|------|-------------|
| \`url\` | TEXT | Unique URL identifying the report. Use format: \`https://deco.news/weekly-digest/YYYY-wWW\` |
| \`title\` | TEXT | Report title |
| \`content\` | TEXT | Full report content |
| \`status\` | TEXT | Report status: \`draft\`, \`published\`, or \`archived\` |

## Recommended Fields

| Field | Type | Description |
|-------|------|-------------|
| \`slug\` | TEXT | Friendly slug, e.g., \`weekly-digest-2026-w05\` |
| \`summary\` | TEXT | 1-2 sentence summary |
| \`created_at\` | TEXT | ISO 8601 date, e.g., \`2026-02-02T10:00:00Z\` |
| \`published_at\` | DATETIME | Publication date |
| \`author\` | TEXT | Author name, default: \`deco.news\` |
| \`reading_time\` | INTEGER | Estimated reading time in minutes |
| \`meta_title\` | TEXT | SEO title (max 60 characters) |
| \`meta_description\` | TEXT | SEO description (max 160 characters) |

## How to Publish a Weekly Report

### Step 1: Prepare the Data

Build the object with report data:

\`\`\`json
{
  "url": "https://deco.news/weekly-digest/2026-w05",
  "title": "Weekly Digest: MCP Ecosystem Growth and AI Integration Trends",
  "slug": "weekly-digest-2026-w05",
  "status": "published",
  "created_at": "2026-02-02T10:00:00Z",
  "published_at": "2026-02-02T10:00:00Z",
  "content": "# Weekly Digest - Week 05/2026\\n\\n## Highlights\\n\\n...",
  "summary": "This week we explore the rapid growth of the MCP ecosystem and emerging AI integration patterns.",
  "key_points": "[\\"MCP adoption grew 40%\\", \\"New tools for AI agents\\", \\"Community contributions doubled\\"]",
  "meta_title": "Weekly Digest W05/2026 - MCP Ecosystem Growth",
  "meta_description": "Explore this week's highlights: MCP ecosystem growth, AI integration trends, and community contributions.",
  "keywords": "MCP, AI, weekly digest, deco, agents",
  "category": "Weekly Digest",
  "tags": "mcp,ai,weekly,digest",
  "author": "deco.news",
  "reading_time": 8,
  "image_url": "https://example.com/images/weekly-w05.png",
  "image_alt_text": "Weekly Digest Week 05 2026 cover image"
}
\`\`\`

### Step 2: Build the SQL Query

Use an INSERT with SQLite syntax:

\`\`\`sql
INSERT INTO deco_weekly_report (
  url,
  title,
  slug,
  status,
  created_at,
  published_at,
  content,
  summary,
  key_points,
  meta_title,
  meta_description,
  keywords,
  category,
  tags,
  author,
  reading_time,
  image_url,
  image_alt_text
) VALUES (
  'https://deco.news/weekly-digest/2026-w05',
  'Weekly Digest: MCP Ecosystem Growth and AI Integration Trends',
  'weekly-digest-2026-w05',
  'published',
  '2026-02-02T10:00:00Z',
  '2026-02-02T10:00:00Z',
  '# Weekly Digest - Week 05/2026\\n\\n## Highlights\\n\\n...',
  'This week we explore the rapid growth of the MCP ecosystem.',
  '["MCP adoption grew 40%", "New tools for AI agents"]',
  'Weekly Digest W05/2026 - MCP Ecosystem Growth',
  'Explore this week''s highlights on MCP ecosystem growth.',
  'MCP, AI, weekly digest, deco, agents',
  'Weekly Digest',
  'mcp,ai,weekly,digest',
  'deco.news',
  8,
  'https://example.com/images/weekly-w05.png',
  'Weekly Digest Week 05 2026 cover image'
);
\`\`\`

### Step 3: Execute via MCP API

Make a POST request to the MCP API:

\`\`\`bash
curl -X POST "https://api.decocms.com/org/project/mcp/tool/DATABASES_RUN_SQL" \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -d '{
    "method": "tools/call",
    "params": {
      "name": "DATABASES_RUN_SQL",
      "arguments": {
        "sql": "INSERT INTO deco_weekly_report (...) VALUES (...)"
      }
    },
    "jsonrpc": "2.0",
    "id": 1
  }'
\`\`\`

## Updating an Existing Report

To update an existing report, use UPDATE:

\`\`\`sql
UPDATE deco_weekly_report 
SET 
  status = 'published',
  published_at = '2026-02-02T12:00:00Z',
  content = 'Updated content...'
WHERE url = 'https://deco.news/weekly-digest/2026-w05';
\`\`\`

## Checking if a Report Already Exists

Before inserting, check if a report already exists for the same week:

\`\`\`sql
SELECT id, url, title, status, created_at 
FROM deco_weekly_report 
WHERE slug = 'weekly-digest-2026-w05';
\`\`\`

## Listing Reports

### List all published reports:

\`\`\`sql
SELECT id, url, title, summary, published_at, reading_time
FROM deco_weekly_report
WHERE status = 'published'
ORDER BY published_at DESC
LIMIT 10;
\`\`\`

### List reports by category:

\`\`\`sql
SELECT id, url, title, published_at
FROM deco_weekly_report
WHERE category = 'Weekly Digest'
ORDER BY published_at DESC;
\`\`\`

## Handling Special Characters

**IMPORTANT**: When inserting content with single quotes, escape them by doubling:

\`\`\`sql
-- Wrong
INSERT INTO deco_weekly_report (title) VALUES ('John's Report');

-- Correct
INSERT INTO deco_weekly_report (title) VALUES ('John''s Report');
\`\`\`

## Content Format

The \`content\` field accepts Markdown or HTML. Recommendations:

1. **Use Markdown** for easier editing and reading
2. **Structure with headings** (##, ###) to organize sections
3. **Include links** to original content sources
4. **Use lists** for key points and highlights

Example content structure:

\`\`\`markdown
# Weekly Digest - Week 05/2026

## Highlights

This week was marked by significant advances in the MCP ecosystem...

## Trending Topics

### 1. MCP Ecosystem Growth
The MCP ecosystem continues to grow rapidly...

### 2. AI Integration Patterns
New integration patterns are emerging...

## Community Voices

> "The MCP protocol is revolutionizing how we build AI agents."
> — @developer on Twitter

## What's Next

Next week, keep an eye on...

---

*Curated by deco.news*
\`\`\`

## key_points Format

The \`key_points\` field should be a stringified JSON array:

\`\`\`json
["Point 1", "Point 2", "Point 3"]
\`\`\`

Insertion example:

\`\`\`sql
INSERT INTO deco_weekly_report (url, title, key_points)
VALUES (
  'https://deco.news/weekly-digest/2026-w05',
  'Weekly Digest W05',
  '["MCP adoption grew 40%", "10 new integrations released", "Community doubled in size"]'
);
\`\`\`

## Report Status

| Status | Description |
|--------|-------------|
| \`draft\` | Draft, not published |
| \`published\` | Published and visible |
| \`archived\` | Archived, no longer visible |

## URL Pattern

Use a consistent pattern for URLs:

\`\`\`
https://deco.news/weekly-digest/YYYY-wWW
\`\`\`

Where:
- \`YYYY\` = 4-digit year
- \`wWW\` = 2-digit week prefixed with 'w'

Examples:
- \`https://deco.news/weekly-digest/2026-w05\`
- \`https://deco.news/weekly-digest/2026-w12\`

## Slug Pattern

Use the same pattern for slugs:

\`\`\`
weekly-digest-YYYY-wWW
\`\`\`

Examples:
- \`weekly-digest-2026-w05\`
- \`weekly-digest-2026-w12\`

## Expected Response

After a successful insertion, the API returns:

\`\`\`json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "content": [
      {
        "type": "text",
        "text": "{\\"result\\": [], \\"rowCount\\": 0}"
      }
    ]
  }
}
\`\`\`

To verify the insertion worked, do a SELECT:

\`\`\`sql
SELECT * FROM deco_weekly_report WHERE slug = 'weekly-digest-2026-w05';
\`\`\`

## Common Errors

### 1. Duplicate URL

\`\`\`
UNIQUE constraint failed: deco_weekly_report.url
\`\`\`

**Solution**: Use UPDATE instead of INSERT, or check if the report already exists.

### 2. Unescaped Quotes

\`\`\`
near "s": syntax error
\`\`\`

**Solution**: Double single quotes in content (\`'\` → \`''\`).

### 3. Missing Required Field

Always include at least: \`url\`, \`title\`, \`content\`, \`status\`.

## Publishing Checklist

- [ ] Unique URL in correct format
- [ ] Descriptive title
- [ ] Complete and formatted content
- [ ] Status defined (\`draft\` or \`published\`)
- [ ] Slug consistent with URL
- [ ] \`created_at\` with current date in ISO 8601
- [ ] \`published_at\` defined (if status = published)
- [ ] Summary filled in
- [ ] Meta title and description for SEO
- [ ] Author defined
- [ ] Estimated reading time
`;

/**
 * Available skills registry
 */
const SKILLS_REGISTRY = [
  {
    id: "weekly-report-publishing",
    name: "Weekly Report Publishing",
    description:
      "Teaches how to publish weekly digest reports to the deco_weekly_report database table. Includes schema, SQL examples, URL patterns, and best practices.",
    tool_to_access: "GET_WEEKLY_REPORT_PUBLISHING_SKILL",
  },
] as const;

/**
 * Get skill content by id
 */
function getSkillContent(skillId: string): string | null {
  if (skillId === "weekly-report-publishing") {
    return WEEKLY_REPORT_PUBLISHING_SKILL;
  }
  return null;
}

// =============================================================================
// GET_WEEKLY_REPORT_PUBLISHING_SKILL Tool
// =============================================================================

export const getWeeklyReportPublishingSkillTool = (_env: Env) =>
  createPrivateTool({
    id: "GET_WEEKLY_REPORT_PUBLISHING_SKILL",
    description:
      "Returns the Weekly Report Publishing skill documentation. This skill teaches how to publish weekly digest reports to the deco_weekly_report database table, including schema, SQL examples, and best practices.",
    inputSchema: z.object({}),
    outputSchema: z.object({
      success: z.boolean(),
      skill: z
        .string()
        .describe("The complete skill documentation in Markdown"),
      skill_name: z.string().describe("Name of the skill"),
      summary: z.string().describe("Brief summary of what the skill teaches"),
      error: z.string().optional(),
    }),
    execute: async () => {
      const skillContent = getSkillContent("weekly-report-publishing");

      if (!skillContent) {
        return {
          success: false,
          skill: "",
          skill_name: "Weekly Report Publishing",
          summary: "",
          error: "Skill not found",
        };
      }

      return {
        success: true,
        skill: skillContent,
        skill_name: "Weekly Report Publishing",
        summary:
          "This skill teaches how to publish Weekly Digest reports to the deco_weekly_report database table. It includes the complete table schema, required and recommended fields, SQL INSERT/UPDATE examples, URL and slug patterns, special character handling, and a publishing checklist.",
      };
    },
  });

// =============================================================================
// LIST_AVAILABLE_SKILLS Tool
// =============================================================================

export const listAvailableSkillsTool = (_env: Env) =>
  createPrivateTool({
    id: "LIST_AVAILABLE_SKILLS",
    description:
      "Lists all available skills/documentation that can be retrieved.",
    inputSchema: z.object({}),
    outputSchema: z.object({
      success: z.boolean(),
      skills: z.array(
        z.object({
          id: z.string(),
          name: z.string(),
          description: z.string(),
          tool_to_access: z.string(),
        }),
      ),
    }),
    execute: async () => {
      return {
        success: true,
        skills: SKILLS_REGISTRY.map(
          ({ id, name, description, tool_to_access }) => ({
            id,
            name,
            description,
            tool_to_access,
          }),
        ),
      };
    },
  });

/**
 * Export all skills tools
 */
export const skillsTools = [
  getWeeklyReportPublishingSkillTool,
  listAvailableSkillsTool,
];
