// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;

export interface FS_DELETEInput {
  path: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_DELETEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The root directory to list files from
 */
export type String_1 = string;

export interface FS_LISTInput {
  prefix: String_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Array = unknown[];

export interface FS_LISTOutput {
  items: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_2 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number = number;

export interface FS_READInput {
  path: String_2;
  expiresIn?: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to read the file from
 */
export type String_3 = string;

export interface FS_READOutput {
  url: String_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_4 = string;

export interface FS_READ_METADATAInput {
  path: String_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_READ_METADATAOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_5 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number_1 = number;
/**
 * Content-Type for the file. This is required.
 */
export type String_6 = string;

export interface FS_WRITEInput {
  path: String_5;
  expiresIn?: Number_1;
  contentType: String_6;
  metadata?: Object;
}
/**
 * Metadata to be added to the file
 */
export interface Object {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to upload the file to
 */
export type String_7 = string;

export interface FS_WRITEOutput {
  url: String_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The question or prompt to ask the AI
 */
export type String_8 = string;
/**
 * The AI model to use
 */
export type String_9 = string;
/**
 * Maximum number of tokens in the response
 */
export type Number_2 = number;
/**
 * Controls randomness (0-2). Lower is more focused
 */
export type Number_3 = number;
/**
 * Controls diversity via nucleus sampling (0-1)
 */
export type Number_4 = number;
export type String_10 = string;
/**
 * Limit search to specific domains
 */
export type Array_1 = String_10[];
/**
 * Filter by time (e.g., 'week', 'day', 'month')
 */
export type String_11 = string;
/**
 * Amount of web search context to include
 */
export type String_12 = "low" | "medium" | "high" | "maximum";
/**
 * Include images in search results
 */
export type Boolean = boolean;
/**
 * Return related questions
 */
export type Boolean_1 = boolean;

export interface ASKInput {
  prompt: String_8;
  model?: String_9;
  max_tokens?: Number_2;
  temperature?: Number_3;
  top_p?: Number_4;
  search_domain_filter?: Array_1;
  search_recency_filter?: String_11;
  search_context_size?: String_12;
  return_images?: Boolean;
  return_related_questions?: Boolean_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AI-generated answer
 */
export type String_13 = string;
/**
 * The model used
 */
export type String_14 = string;
/**
 * Reason for completion
 */
export type String_15 = string;
export type Number_5 = number;
export type Number_6 = number;
export type Number_7 = number;
export type String_16 = string;
export type String_17 = string;
export type String_18 = string;
/**
 * Source URLs used for the answer
 */
export type Array_2 = Object_2[];
export type String_19 = string;
/**
 * Related questions suggested by the AI
 */
export type Array_3 = String_19[];
export type String_20 = string;
export type String_21 = string;
/**
 * Images related to the search
 */
export type Array_4 = Object_3[];

export interface ASKOutput {
  answer: String_13;
  model?: String_14;
  finish_reason?: String_15;
  usage?: Object_1;
  sources?: Array_2;
  related_questions?: Array_3;
  images?: Array_4;
}
/**
 * Token usage information
 */
export interface Object_1 {
  prompt_tokens: Number_5;
  completion_tokens: Number_6;
  total_tokens: Number_7;
}
export interface Object_2 {
  title?: String_16;
  url: String_17;
  snippet?: String_18;
}
export interface Object_3 {
  url: String_20;
  description?: String_21;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Array of conversation messages
 *
 * @minItems 1
 */
export type Array_5 = [Object_4, ...Object_4[]];
/**
 * The role of the message sender
 */
export type String_22 = "system" | "user" | "assistant";
/**
 * The content of the message
 */
export type String_23 = string;
/**
 * The AI model to use
 */
export type String_24 = string;
/**
 * Maximum number of tokens in the response
 */
export type Number_8 = number;
/**
 * Controls randomness (0-2). Lower is more focused
 */
export type Number_9 = number;
/**
 * Controls diversity via nucleus sampling (0-1)
 */
export type Number_10 = number;
export type String_25 = string;
/**
 * Limit search to specific domains
 */
export type Array_6 = String_25[];
/**
 * Filter by time (e.g., 'week', 'day', 'month')
 */
export type String_26 = string;
/**
 * Amount of web search context to include
 */
export type String_27 = "low" | "medium" | "high" | "maximum";
/**
 * Include images in search results
 */
export type Boolean_2 = boolean;
/**
 * Return related questions
 */
export type Boolean_3 = boolean;

export interface CHATInput {
  messages: Array_5;
  model?: String_24;
  max_tokens?: Number_8;
  temperature?: Number_9;
  top_p?: Number_10;
  search_domain_filter?: Array_6;
  search_recency_filter?: String_26;
  search_context_size?: String_27;
  return_images?: Boolean_2;
  return_related_questions?: Boolean_3;
}
export interface Object_4 {
  role: String_22;
  content: String_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AI-generated answer
 */
export type String_28 = string;
/**
 * The model used
 */
export type String_29 = string;
/**
 * Reason for completion
 */
export type String_30 = string;
export type Number_11 = number;
export type Number_12 = number;
export type Number_13 = number;
export type String_31 = string;
export type String_32 = string;
export type String_33 = string;
/**
 * Source URLs used for the answer
 */
export type Array_7 = Object_6[];
export type String_34 = string;
/**
 * Related questions suggested by the AI
 */
export type Array_8 = String_34[];
export type String_35 = string;
export type String_36 = string;
/**
 * Images related to the search
 */
export type Array_9 = Object_7[];

export interface CHATOutput {
  answer: String_28;
  model?: String_29;
  finish_reason?: String_30;
  usage?: Object_5;
  sources?: Array_7;
  related_questions?: Array_8;
  images?: Array_9;
}
/**
 * Token usage information
 */
export interface Object_5 {
  prompt_tokens: Number_11;
  completion_tokens: Number_12;
  total_tokens: Number_13;
}
export interface Object_6 {
  title?: String_31;
  url: String_32;
  snippet?: String_33;
}
export interface Object_7 {
  url: String_35;
  description?: String_36;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_37 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_37;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_38 = string;
export type Array_10 = String_38[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_10;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_4 = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_39 = string;
export type String_40 = string;
export type String_41 = string;
export type String_42 = string;
export type String_43 = string;
export type String_44 = string;
export type String_45 = string;
export type String_46 = string;
export type String_47 = string;
export type Array_12 = String_47[];
export type String_48 = string;
export type String_49 = "none" | "open" | "autoPin";
export type Array_11 = Object_8[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_11;
}
export interface Object_8 {
  id?: String_39;
  name?: String_40;
  title: String_41;
  description?: String_42;
  icon: String_43;
  url?: String_44;
  mimeTypePattern?: String_45;
  resourceName?: String_46;
  tools?: Array_12;
  prompt?: String_48;
  installBehavior?: String_49;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_50 = string;
export type StringNull = String_51 | Null;
export type String_51 = string;
export type Null = null;
export type StringNull_1 = String_52 | Null_1;
export type String_52 = string;
export type Null_1 = null;
export type String_53 = string;

export interface GET_USEROutput {
  id: String_50;
  name: StringNull;
  avatar: StringNull_1;
  email: String_53;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  FILE_SYSTEM: z.object({
    value: z.string(),
    __type: z.literal("@deco/file-system").default("@deco/file-system"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  FILE_SYSTEM: Mcp<{
    /**
     * Delete a file
     */
    FS_DELETE: (input: FS_DELETEInput) => Promise<FS_DELETEOutput>;
    /**
     * List files from a given bucket given a prefix
     */
    FS_LIST: (input: FS_LISTInput) => Promise<FS_LISTOutput>;
    /**
     * Get a secure temporary link to read a file
     */
    FS_READ: (input: FS_READInput) => Promise<FS_READOutput>;
    /**
     * Get metadata about a file
     */
    FS_READ_METADATA: (
      input: FS_READ_METADATAInput,
    ) => Promise<FS_READ_METADATAOutput>;
    /**
     * Get a secure temporary link to upload a file
     */
    FS_WRITE: (input: FS_WRITEInput) => Promise<FS_WRITEOutput>;
  }>;
  SELF: Mcp<{
    /**
     * Ask questions to Perplexity AI and get web-backed answers with real-time search
     */
    ASK: (input: ASKInput) => Promise<ASKOutput>;
    /**
     * Have a multi-turn conversation with Perplexity AI. This allows you to provide message history for more contextual responses.
     */
    CHAT: (input: CHATInput) => Promise<CHATOutput>;
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
  }>;
}

export const Scopes = {
  FILE_SYSTEM: {
    FS_DELETE: "FILE_SYSTEM::FS_DELETE",
    FS_LIST: "FILE_SYSTEM::FS_LIST",
    FS_READ: "FILE_SYSTEM::FS_READ",
    FS_READ_METADATA: "FILE_SYSTEM::FS_READ_METADATA",
    FS_WRITE: "FILE_SYSTEM::FS_WRITE",
  },
};
