// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;

export interface FS_DELETEInput {
  path: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_DELETEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The root directory to list files from
 */
export type String_1 = string;

export interface FS_LISTInput {
  prefix: String_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Array = unknown[];

export interface FS_LISTOutput {
  items: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_2 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number = number;

export interface FS_READInput {
  path: String_2;
  expiresIn?: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to read the file from
 */
export type String_3 = string;

export interface FS_READOutput {
  url: String_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_4 = string;

export interface FS_READ_METADATAInput {
  path: String_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_READ_METADATAOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_5 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number_1 = number;
/**
 * Content-Type for the file. This is required.
 */
export type String_6 = string;

export interface FS_WRITEInput {
  path: String_5;
  expiresIn?: Number_1;
  contentType: String_6;
  metadata?: Object;
}
/**
 * Metadata to be added to the file
 */
export interface Object {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to upload the file to
 */
export type String_7 = string;

export interface FS_WRITEOutput {
  url: String_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_8 = string;
export type Number_2 = number;
export type Array_1 = Object_1[];

export interface CONTRACT_AUTHORIZEInput {
  clauses: Array_1;
}
export interface Object_1 {
  clauseId: String_8;
  amount: Number_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_9 = string;
export type String_10 = string;
export type Number_3 = number;

export interface CONTRACT_AUTHORIZEOutput {
  transactionId: String_9;
  totalAmount: String_10;
  timestamp: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CONTRACT_GETInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_11 = string;
export type String_12 = string;
export type String_13 = string;
export type StringNumber = String_14 | Number_4;
export type String_14 = string;
export type Number_4 = number;
export type String_15 = string;
export type String_16 = string;
export type Array_3 = String_16[];
export type Array_2 = Object_3[];

export interface CONTRACT_GETOutput {
  appName?: String_11;
  contract: Object_2;
}
export interface Object_2 {
  body?: String_12;
  clauses?: Array_2;
}
export interface Object_3 {
  id: String_13;
  price: StringNumber;
  description?: String_15;
  usedByTools?: Array_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_17 = string;
export type String_18 = string;
export type Number_5 = number;
export type Array_4 = Object_4[];
export type Number_6 = number;
export type String_19 = string;

export interface CONTRACT_SETTLEInput {
  transactionId: String_17;
  clauses?: Array_4;
  amount?: Number_6;
  vendorId: String_19;
}
export interface Object_4 {
  clauseId: String_18;
  amount: Number_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_20 = string;

export interface CONTRACT_SETTLEOutput {
  transactionId: String_20;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_21 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_21;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_22 = string;
export type Array_5 = String_22[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_5;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  PERPLEXITY_CONTRACT: z.object({
    value: z.string(),
    __type: z
      .literal("@deco/perplexity-2f621471d46f1ff92decfc950028d881")
      .default("@deco/perplexity-2f621471d46f1ff92decfc950028d881"),
  }),
  FILE_SYSTEM: z.object({
    value: z.string(),
    __type: z.literal("@deco/file-system").default("@deco/file-system"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  PERPLEXITY_CONTRACT: Mcp<{
    /**
     * Authorize a charge for a contract clause. Creates a single authorization with transactionId.
     */
    CONTRACT_AUTHORIZE: (
      input: CONTRACT_AUTHORIZEInput,
    ) => Promise<CONTRACT_AUTHORIZEOutput>;
    /**
     * Get the current contract state.
     */
    CONTRACT_GET: (input: CONTRACT_GETInput) => Promise<CONTRACT_GETOutput>;
    /**
     * Settle the current authorized charge. Processes the payment for the current authorization.
     */
    CONTRACT_SETTLE: (
      input: CONTRACT_SETTLEInput,
    ) => Promise<CONTRACT_SETTLEOutput>;
    /**
     * Start the OAuth flow for the contract app.
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
  }>;
  FILE_SYSTEM: Mcp<{
    /**
     * Delete a file
     */
    FS_DELETE: (input: FS_DELETEInput) => Promise<FS_DELETEOutput>;
    /**
     * List files from a given bucket given a prefix
     */
    FS_LIST: (input: FS_LISTInput) => Promise<FS_LISTOutput>;
    /**
     * Get a secure temporary link to read a file
     */
    FS_READ: (input: FS_READInput) => Promise<FS_READOutput>;
    /**
     * Get metadata about a file
     */
    FS_READ_METADATA: (
      input: FS_READ_METADATAInput,
    ) => Promise<FS_READ_METADATAOutput>;
    /**
     * Get a secure temporary link to upload a file
     */
    FS_WRITE: (input: FS_WRITEInput) => Promise<FS_WRITEOutput>;
  }>;
}

export const Scopes = {
  FILE_SYSTEM: {
    FS_DELETE: "FILE_SYSTEM::FS_DELETE",
    FS_LIST: "FILE_SYSTEM::FS_LIST",
    FS_READ: "FILE_SYSTEM::FS_READ",
    FS_READ_METADATA: "FILE_SYSTEM::FS_READ_METADATA",
    FS_WRITE: "FILE_SYSTEM::FS_WRITE",
  },
  PERPLEXITY_CONTRACT: {
    CONTRACT_AUTHORIZE: "PERPLEXITY_CONTRACT::CONTRACT_AUTHORIZE",
    CONTRACT_GET: "PERPLEXITY_CONTRACT::CONTRACT_GET",
    CONTRACT_SETTLE: "PERPLEXITY_CONTRACT::CONTRACT_SETTLE",
    DECO_CHAT_OAUTH_START: "PERPLEXITY_CONTRACT::DECO_CHAT_OAUTH_START",
  },
};
