/**
 * Central export point for all VTEX tools.
 *
 * Registry tools are auto-generated from OpenAPI specs via hey-api.
 * Custom tools handle complex multi-step operations.
 */
import type { Env } from "../types/env.ts";
import {
  brandTools,
  categoryTools,
  warehouseTools,
  inventoryTools,
  priceTools,
  productTools,
  skuTools,
  orderTools,
  collectionTools,
  adsTools,
  antifraudProviderTools,
  audienceTools,
  b2bBuyerDataTools,
  b2bContactInformationTools,
  b2bContractsTools,
  budgetsTools,
  buyerOrganizationsTools,
  buyingPoliciesTools,
  cardTokenVaultTools,
  catalogSellerPortalTools,
  checkoutTools,
  customFieldsTools,
  customerCreditTools,
  checkoutCustomCardPaymentTools,
  dataSubjectRightsTools,
  defaultValuesTools,
  deliveryPromiseNotificationTools,
  giftcardTools,
  giftcardHubTools,
  giftcardProviderProtocolTools,
  headlessCmsTools,
  intelligentSearchTools,
  intelligentSearchEventsTools,
  legacyCmsPortalTools,
  licenseManagerTools,
  marketplaceTools,
  marketplaceSentOffersTools,
  marketplaceSuggestionsTools,
  marketplaceProtocolMapperTools,
  marketplaceProtocolOrdersTools,
  marketplaceProtocolSellerFulfillmentTools,
  marketplaceProtocolSellerMarketplaceTools,
  masterDataV2Tools,
  masterDataV1Tools,
  messageCenterTools,
  mtlsTools,
  operationalCapacityTools,
  ordersPiiTools,
  organizationUnitsTools,
  paymentProviderProtocolTools,
  paymentsGatewayTools,
  pickAndPackTools,
  pickAndPackLastMileTools,
  pickAndPackOrderChangesTools,
  policiesSystemTools,
  pricingHubTools,
  profileSystemTools,
  promotionsAndTaxesTools,
  promotionsAndTaxesV2Tools,
  punchoutTools,
  recommendationsBffTools,
  reviewsAndRatingsTools,
  searchTools,
  sessionManagerTools,
  skuBindingsTools,
  sslCertificatesTools,
  storefrontPermissionsTools,
  subscriptionsV3Tools,
  trackingTools,
  vtexDoTools,
  vtexIdTools,
  vtexShippingNetworkTools,
} from "./registry.ts";

// ── Custom tools ──────────────────────────────────────────────────────────────
import { searchCollections } from "./custom/search-collections.ts";

// ── Tool registry factories (env: Env) => Tool ────────────────────────────────
const registryFactories = [
  ...brandTools,
  ...categoryTools,
  ...warehouseTools,
  ...inventoryTools,
  ...priceTools,
  ...productTools,
  ...skuTools,
  ...orderTools,
  ...collectionTools,
  ...adsTools,
  ...antifraudProviderTools,
  ...audienceTools,
  ...b2bBuyerDataTools,
  ...b2bContactInformationTools,
  ...b2bContractsTools,
  ...budgetsTools,
  ...buyerOrganizationsTools,
  ...buyingPoliciesTools,
  ...cardTokenVaultTools,
  ...catalogSellerPortalTools,
  ...checkoutTools,
  ...customFieldsTools,
  ...customerCreditTools,
  ...checkoutCustomCardPaymentTools,
  ...dataSubjectRightsTools,
  ...defaultValuesTools,
  ...deliveryPromiseNotificationTools,
  ...giftcardTools,
  ...giftcardHubTools,
  ...giftcardProviderProtocolTools,
  ...headlessCmsTools,
  ...intelligentSearchTools,
  ...intelligentSearchEventsTools,
  ...legacyCmsPortalTools,
  ...licenseManagerTools,
  ...marketplaceTools,
  ...marketplaceSentOffersTools,
  ...marketplaceSuggestionsTools,
  ...marketplaceProtocolMapperTools,
  ...marketplaceProtocolOrdersTools,
  ...marketplaceProtocolSellerFulfillmentTools,
  ...marketplaceProtocolSellerMarketplaceTools,
  ...masterDataV2Tools,
  ...masterDataV1Tools,
  ...messageCenterTools,
  ...mtlsTools,
  ...operationalCapacityTools,
  ...ordersPiiTools,
  ...organizationUnitsTools,
  ...paymentProviderProtocolTools,
  ...paymentsGatewayTools,
  ...pickAndPackTools,
  ...pickAndPackLastMileTools,
  ...pickAndPackOrderChangesTools,
  ...policiesSystemTools,
  ...pricingHubTools,
  ...profileSystemTools,
  ...promotionsAndTaxesTools,
  ...promotionsAndTaxesV2Tools,
  ...punchoutTools,
  ...recommendationsBffTools,
  ...reviewsAndRatingsTools,
  ...searchTools,
  ...sessionManagerTools,
  ...skuBindingsTools,
  ...sslCertificatesTools,
  ...storefrontPermissionsTools,
  ...subscriptionsV3Tools,
  ...trackingTools,
  ...vtexDoTools,
  ...vtexIdTools,
  ...vtexShippingNetworkTools,
];

const customFactories = [
  // Collection search (endpoint absent from generated SDKs)
  searchCollections,
];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const tools = [...registryFactories, ...customFactories] as any[];
