// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type Number = number;
export type Array = Object[];

export interface CONTRACT_AUTHORIZEInput {
  clauses: Array;
}
export interface Object {
  clauseId: String;
  amount: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type String_2 = string;
export type Number_1 = number;

export interface CONTRACT_AUTHORIZEOutput {
  transactionId: String_1;
  totalAmount: String_2;
  timestamp: Number_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CONTRACT_GETInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type StringNumber = String_6 | Number_2;
export type String_6 = string;
export type Number_2 = number;
export type String_7 = string;
export type String_8 = string;
export type Array_2 = String_8[];
export type Array_1 = Object_2[];

export interface CONTRACT_GETOutput {
  appName?: String_3;
  contract: Object_1;
}
export interface Object_1 {
  body?: String_4;
  clauses?: Array_1;
}
export interface Object_2 {
  id: String_5;
  price: StringNumber;
  description?: String_7;
  usedByTools?: Array_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_9 = string;
export type String_10 = string;
export type Number_3 = number;
export type Array_3 = Object_3[];
export type Number_4 = number;
export type String_11 = string;

export interface CONTRACT_SETTLEInput {
  transactionId: String_9;
  clauses?: Array_3;
  amount?: Number_4;
  vendorId: String_11;
}
export interface Object_3 {
  clauseId: String_10;
  amount: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_12 = string;

export interface CONTRACT_SETTLEOutput {
  transactionId: String_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_13 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_14 = string;
export type Array_4 = String_14[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_4;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  OPENROUTER_CHAT_CONTRACT: z.object({
    value: z.string(),
    __type: z
      .literal("@deco/openrouter-68cfdea5555177d9155f913ecdbafa38")
      .default("@deco/openrouter-68cfdea5555177d9155f913ecdbafa38"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  OPENROUTER_CHAT_CONTRACT: Mcp<{
    /**
     * Authorize a charge for a contract clause. Creates a single authorization with transactionId.
     */
    CONTRACT_AUTHORIZE: (
      input: CONTRACT_AUTHORIZEInput,
    ) => Promise<CONTRACT_AUTHORIZEOutput>;
    /**
     * Get the current contract state.
     */
    CONTRACT_GET: (input: CONTRACT_GETInput) => Promise<CONTRACT_GETOutput>;
    /**
     * Settle the current authorized charge. Processes the payment for the current authorization.
     */
    CONTRACT_SETTLE: (
      input: CONTRACT_SETTLEInput,
    ) => Promise<CONTRACT_SETTLEOutput>;
    /**
     * Start the OAuth flow for the contract app.
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
  }>;
}

export const Scopes = {
  OPENROUTER_CHAT_CONTRACT: {
    CONTRACT_AUTHORIZE: "OPENROUTER_CHAT_CONTRACT::CONTRACT_AUTHORIZE",
    CONTRACT_GET: "OPENROUTER_CHAT_CONTRACT::CONTRACT_GET",
    CONTRACT_SETTLE: "OPENROUTER_CHAT_CONTRACT::CONTRACT_SETTLE",
    DECO_CHAT_OAUTH_START: "OPENROUTER_CHAT_CONTRACT::DECO_CHAT_OAUTH_START",
  },
};
