// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;

export interface DECO_GET_APP_SCHEMAInput {
  appName: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_1 = string;
export type Array = String_1[];

export interface DECO_GET_APP_SCHEMAOutput {
  schema?: unknown;
  scopes?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The id of the integration to install. To know the available ids, use the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_2 = string;
/**
 * The provider of the integration to install. To know the available providers, use the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_3 = string;
/**
 * The id of the app to install the integration for. To know the available app ids, use the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_4 = string;

export interface DECO_INTEGRATION_INSTALLInput {
  id: String_2;
  provider?: String_3;
  appId?: String_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The id of the installation. Use this id to enable the integration using the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_5 = string;

export interface DECO_INTEGRATION_INSTALLOutput {
  installationId: String_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The id of the integration to start the OAuth flow for
 */
export type String_6 = string;
/**
 * The return URL for the OAuth flow. Will come with a query param including the mcp URL.
 */
export type String_7 = string;
/**
 * The install id of the integration to start the OAuth flow for
 */
export type String_8 = string;
/**
 * The provider of the integration to start the OAuth flow for
 */
export type String_9 = string;

export interface DECO_INTEGRATION_OAUTH_STARTInput {
  appName: String_6;
  returnUrl: String_7;
  installId: String_8;
  provider?: String_9;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_INTEGRATION_OAUTH_STARTOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The query to search for
 */
export type String_10 = string;
/**
 * Whether to show contracts
 */
export type Boolean = boolean;

export interface DECO_INTEGRATIONS_SEARCHInput {
  query?: String_10;
  showContracts?: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_11 = string;
export type String_12 = string;
export type String_13 = string;
export type String_14 = string;
export type String_15 = string;
export type Null = null;
export type String_16 = string;
export type Null_1 = null;
export type String_17 = string;
export type Null_2 = null;
export type Boolean_1 = boolean;
export type Null_3 = null;
export type String_18 = "HTTP";
export type String_19 = string;
export type String_20 = string;
export type String_21 = "SSE";
export type String_22 = string;
export type String_23 = string;
export type String_24 = string;
export type String_25 = "Websocket";
export type String_26 = string;
export type String_27 = string;
export type String_28 = "Deco";
export type String_29 = string;
export type String_30 = string;
export type String_31 = "INNATE";
export type String_32 = string;
export type String_33 = string;
export type Null_4 = null;
export type String_34 = string;
export type Null_5 = null;
/**
 * The name of the tool
 */
export type String_35 = string;
/**
 * The description of the tool
 */
export type String_36 = string;
export type Array_2 = (Object_8 & Object_10)[];
export type Null_6 = null;
export type String_37 = string;
export type String_38 = string;
/**
 * The Integrations that match the query
 */
export type Array_1 = (Object & Object_12)[];

export interface DECO_INTEGRATIONS_SEARCHOutput {
  integrations: Array_1;
}
export interface Object {
  id: String_11;
  name: String_12;
  description?: String_13;
  icon?: String_14;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_15
      )
    | Null;
  appName?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_16
      )
    | Null_1;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_17
      )
    | Null_2;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_1
      )
    | Null_3;
  connection: Object_1 | Object_2 | Object_4 | Object_5 | Object_6;
  metadata?: Object_7 | Null_4;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_34
      )
    | Null_5;
  tools?: Array_2 | Null_6;
}
export interface Object_1 {
  type: String_18;
  url: String_19;
  token?: String_20;
}
export interface Object_2 {
  type: String_21;
  url: String_22;
  token?: String_23;
  headers?: Object_3;
}
export interface Object_3 {
  [k: string]: String_24;
}
export interface Object_4 {
  type: String_25;
  url: String_26;
  token?: String_27;
}
export interface Object_5 {
  type: String_28;
  tenant: String_29;
  token?: String_30;
}
export interface Object_6 {
  type: String_31;
  name: String_32;
  workspace?: String_33;
}
export interface Object_7 {
  [k: string]: unknown;
}
export interface Object_8 {
  name: String_35;
  inputSchema: Object_9;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_9 {
  [k: string]: unknown;
}
export interface Object_10 {
  description?: String_36;
  outputSchema?: Object_11;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_11 {
  [k: string]: unknown;
}
export interface Object_12 {
  provider: String_37;
  friendlyName?: String_38;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_39 = string;
export type String_40 = "HTTP";
export type String_41 = string;
export type String_42 = string;
export type String_43 = "SSE";
export type String_44 = string;
export type String_45 = string;
export type String_46 = string;
export type String_47 = "Websocket";
export type String_48 = string;
export type String_49 = string;
export type String_50 = "Deco";
export type String_51 = string;
export type String_52 = string;
export type String_53 = "INNATE";
export type String_54 = string;
export type String_55 = string;
export type String_56 = string;
export type Integer = number;
export type String_57 = string;

export interface INTEGRATIONS_CALL_TOOLInput {
  id?: String_39;
  connection?: Object_13 | Object_14 | Object_16 | Object_17 | Object_18;
  params: Object_19;
}
export interface Object_13 {
  type: String_40;
  url: String_41;
  token?: String_42;
}
export interface Object_14 {
  type: String_43;
  url: String_44;
  token?: String_45;
  headers?: Object_15;
}
export interface Object_15 {
  [k: string]: String_46;
}
export interface Object_16 {
  type: String_47;
  url: String_48;
  token?: String_49;
}
export interface Object_17 {
  type: String_50;
  tenant: String_51;
  token?: String_52;
}
export interface Object_18 {
  type: String_53;
  name: String_54;
  workspace?: String_55;
}
export interface Object_19 {
  _meta?: Object_20;
  name: String_57;
  arguments?: Object_21;
  [k: string]: unknown;
}
export interface Object_20 {
  progressToken?: String_56 | Integer;
  [k: string]: unknown;
}
export interface Object_21 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_CALL_TOOLOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_58 = string;
export type String_59 = string;
export type String_60 = string;
export type String_61 = string;
export type String_62 = string;
export type Null_7 = null;
export type String_63 = string;
export type Null_8 = null;
export type Boolean_2 = boolean;
export type Null_9 = null;
export type String_64 = "HTTP";
export type String_65 = string;
export type String_66 = string;
export type String_67 = "SSE";
export type String_68 = string;
export type String_69 = string;
export type String_70 = string;
export type String_71 = "Websocket";
export type String_72 = string;
export type String_73 = string;
export type String_74 = "Deco";
export type String_75 = string;
export type String_76 = string;
export type String_77 = "INNATE";
export type String_78 = string;
export type String_79 = string;
export type Null_10 = null;
export type String_80 = string;
export type Null_11 = null;
/**
 * The name of the tool
 */
export type String_81 = string;
/**
 * The description of the tool
 */
export type String_82 = string;
export type Array_3 = (Object_29 & Object_31)[];
export type Null_12 = null;
export type String_83 = string;

export interface INTEGRATIONS_CREATEInput {
  id?: String_58;
  name?: String_59;
  description?: String_60;
  icon?: String_61;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_62
      )
    | Null_7;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_63
      )
    | Null_8;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_2
      )
    | Null_9;
  connection?: Object_22 | Object_23 | Object_25 | Object_26 | Object_27;
  metadata?: Object_28 | Null_10;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_80
      )
    | Null_11;
  tools?: Array_3 | Null_12;
  clientIdFromApp?: String_83;
}
export interface Object_22 {
  type: String_64;
  url: String_65;
  token?: String_66;
}
export interface Object_23 {
  type: String_67;
  url: String_68;
  token?: String_69;
  headers?: Object_24;
}
export interface Object_24 {
  [k: string]: String_70;
}
export interface Object_25 {
  type: String_71;
  url: String_72;
  token?: String_73;
}
export interface Object_26 {
  type: String_74;
  tenant: String_75;
  token?: String_76;
}
export interface Object_27 {
  type: String_77;
  name: String_78;
  workspace?: String_79;
}
export interface Object_28 {
  [k: string]: unknown;
}
export interface Object_29 {
  name: String_81;
  inputSchema: Object_30;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_30 {
  [k: string]: unknown;
}
export interface Object_31 {
  description?: String_82;
  outputSchema?: Object_32;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_32 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_CREATEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_84 = string;

export interface INTEGRATIONS_DELETEInput {
  id: String_84;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_DELETEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_85 = string;

export interface INTEGRATIONS_GETInput {
  id: String_85;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_GETOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_86 = string;

export interface INTEGRATIONS_GET_API_KEYInput {
  integrationId: String_86;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_GET_API_KEYOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_87 = "Channel" | "View";
export type Boolean_3 = boolean;

export interface INTEGRATIONS_LISTInput {
  binder?: String_87;
  hideVirtual?: Boolean_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_88 = string;
export type String_89 = string;
export type String_90 = string;
export type String_91 = string;
export type String_92 = string;
export type Null_13 = null;
export type String_93 = string;
export type Null_14 = null;
export type String_94 = string;
export type Null_15 = null;
export type Boolean_4 = boolean;
export type Null_16 = null;
export type String_95 = "HTTP";
export type String_96 = string;
export type String_97 = string;
export type String_98 = "SSE";
export type String_99 = string;
export type String_100 = string;
export type String_101 = string;
export type String_102 = "Websocket";
export type String_103 = string;
export type String_104 = string;
export type String_105 = "Deco";
export type String_106 = string;
export type String_107 = string;
export type String_108 = "INNATE";
export type String_109 = string;
export type String_110 = string;
export type Null_17 = null;
export type String_111 = string;
export type Null_18 = null;
/**
 * The name of the tool
 */
export type String_112 = string;
/**
 * The description of the tool
 */
export type String_113 = string;
export type Array_5 = (Object_41 & Object_43)[];
export type Null_19 = null;
export type Array_4 = Object_33[];

export interface INTEGRATIONS_LISTOutput {
  items: Array_4;
}
export interface Object_33 {
  id: String_88;
  name: String_89;
  description?: String_90;
  icon?: String_91;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_92
      )
    | Null_13;
  appName?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_93
      )
    | Null_14;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_94
      )
    | Null_15;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_4
      )
    | Null_16;
  connection: Object_34 | Object_35 | Object_37 | Object_38 | Object_39;
  metadata?: Object_40 | Null_17;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_111
      )
    | Null_18;
  tools?: Array_5 | Null_19;
}
export interface Object_34 {
  type: String_95;
  url: String_96;
  token?: String_97;
}
export interface Object_35 {
  type: String_98;
  url: String_99;
  token?: String_100;
  headers?: Object_36;
}
export interface Object_36 {
  [k: string]: String_101;
}
export interface Object_37 {
  type: String_102;
  url: String_103;
  token?: String_104;
}
export interface Object_38 {
  type: String_105;
  tenant: String_106;
  token?: String_107;
}
export interface Object_39 {
  type: String_108;
  name: String_109;
  workspace?: String_110;
}
export interface Object_40 {
  [k: string]: unknown;
}
export interface Object_41 {
  name: String_112;
  inputSchema: Object_42;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_42 {
  [k: string]: unknown;
}
export interface Object_43 {
  description?: String_113;
  outputSchema?: Object_44;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_44 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_114 = string;
export type String_115 = string;
export type String_116 = string;
export type String_117 = string;
export type String_118 = string;
export type String_119 = string;
export type Null_20 = null;
export type String_120 = string;
export type Null_21 = null;
export type String_121 = string;
export type Null_22 = null;
export type Boolean_5 = boolean;
export type Null_23 = null;
export type String_122 = "HTTP";
export type String_123 = string;
export type String_124 = string;
export type String_125 = "SSE";
export type String_126 = string;
export type String_127 = string;
export type String_128 = string;
export type String_129 = "Websocket";
export type String_130 = string;
export type String_131 = string;
export type String_132 = "Deco";
export type String_133 = string;
export type String_134 = string;
export type String_135 = "INNATE";
export type String_136 = string;
export type String_137 = string;
export type Null_24 = null;
export type String_138 = string;
export type Null_25 = null;
/**
 * The name of the tool
 */
export type String_139 = string;
/**
 * The description of the tool
 */
export type String_140 = string;
export type Array_6 = (Object_53 & Object_55)[];
export type Null_26 = null;

export interface INTEGRATIONS_UPDATEInput {
  id: String_114;
  integration: Object_45;
}
export interface Object_45 {
  id: String_115;
  name: String_116;
  description?: String_117;
  icon?: String_118;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_119
      )
    | Null_20;
  appName?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_120
      )
    | Null_21;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_121
      )
    | Null_22;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_5
      )
    | Null_23;
  connection: Object_46 | Object_47 | Object_49 | Object_50 | Object_51;
  metadata?: Object_52 | Null_24;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_138
      )
    | Null_25;
  tools?: Array_6 | Null_26;
}
export interface Object_46 {
  type: String_122;
  url: String_123;
  token?: String_124;
}
export interface Object_47 {
  type: String_125;
  url: String_126;
  token?: String_127;
  headers?: Object_48;
}
export interface Object_48 {
  [k: string]: String_128;
}
export interface Object_49 {
  type: String_129;
  url: String_130;
  token?: String_131;
}
export interface Object_50 {
  type: String_132;
  tenant: String_133;
  token?: String_134;
}
export interface Object_51 {
  type: String_135;
  name: String_136;
  workspace?: String_137;
}
export interface Object_52 {
  [k: string]: unknown;
}
export interface Object_53 {
  name: String_139;
  inputSchema: Object_54;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_54 {
  [k: string]: unknown;
}
export interface Object_55 {
  description?: String_140;
  outputSchema?: Object_56;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_56 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_UPDATEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATABASES_GET_METAInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Number = number;

export interface DATABASES_GET_METAOutput {
  bytes?: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date to recover to
 */
export type String_141 = string;

export interface DATABASES_RECOVERYInput {
  date: String_141;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_6 = boolean;

export interface DATABASES_RECOVERYOutput {
  success: Boolean_6;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The SQL query to run
 */
export type String_142 = string;
/**
 * The parameters to pass to the SQL query
 */
export type Array_7 = unknown[];

export interface DATABASES_RUN_SQLInput {
  sql: String_142;
  params?: Array_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_7 = boolean;
export type Number_1 = number;
export type Number_2 = number;
export type Number_3 = number;
export type Number_4 = number;
export type Number_5 = number;
export type Boolean_8 = boolean;
export type String_143 = "WNAM" | "ENAM" | "WEUR" | "EEUR" | "APAC" | "OC";
export type Number_6 = number;
export type Number_7 = number;
export type Array_9 = unknown[];
export type Boolean_9 = boolean;
export type Array_8 = Object_57[];

export interface DATABASES_RUN_SQLOutput {
  result: Array_8;
}
export interface Object_57 {
  meta?: Object_58;
  results?: Array_9;
  success?: Boolean_9;
}
export interface Object_58 {
  changed_db?: Boolean_7;
  changes?: Number_1;
  duration?: Number_2;
  last_row_id?: Number_3;
  rows_read?: Number_4;
  rows_written?: Number_5;
  served_by_primary?: Boolean_8;
  served_by_region?: String_143;
  size_after?: Number_6;
  timings?: Object_59;
}
export interface Object_59 {
  sql_duration_ms?: Number_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_144 = string;
export type String_145 = string;
export type String_146 = string;
export type String_147 = string;
export type String_148 = string;
export type String_149 = string;
export type String_150 = string;
export type String_151 = string;
export type String_152 = string;
export type Array_11 = String_152[];
export type String_153 = string;
export type String_154 = "none" | "open" | "autoPin";
export type Array_10 = Object_60[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_10;
}
export interface Object_60 {
  id?: String_144;
  name?: String_145;
  title: String_146;
  description?: String_147;
  icon: String_148;
  url?: String_149;
  mimeTypePattern?: String_150;
  resourceName?: String_151;
  tools?: Array_11;
  prompt?: String_153;
  installBehavior?: String_154;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_155 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_155;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_156 = string;
export type Array_12 = String_156[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_12;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_10 = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean_10;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput_1 {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_157 = string;
export type String_158 = string;
export type String_159 = string;
export type String_160 = string;
export type String_161 = string;
export type String_162 = string;
export type String_163 = string;
export type String_164 = string;
export type String_165 = string;
export type Array_14 = String_165[];
export type String_166 = string;
export type String_167 = "none" | "open" | "autoPin";
export type Array_13 = Object_61[];

export interface DECO_CHAT_VIEWS_LISTOutput_1 {
  views: Array_13;
}
export interface Object_61 {
  id?: String_157;
  name?: String_158;
  title: String_159;
  description?: String_160;
  icon: String_161;
  url?: String_162;
  mimeTypePattern?: String_163;
  resourceName?: String_164;
  tools?: Array_14;
  prompt?: String_166;
  installBehavior?: String_167;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to delete
 */
export type String_168 = string;

export interface DECO_COLLECTION_AGENTS_DELETEInput {
  id: String_168;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the deletion was successful
 */
export type Boolean_11 = boolean;
/**
 * ID of the deleted entity
 */
export type String_169 = string;

export interface DECO_COLLECTION_AGENTS_DELETEOutput {
  success: Boolean_11;
  id: String_169;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to retrieve
 */
export type String_170 = string;

export interface DECO_COLLECTION_AGENTS_GETInput {
  id: String_170;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_171 = string;
/**
 * Human-readable title for the entity
 */
export type String_172 = string;
export type String_173 = string;
export type String_174 = string;
export type String_175 = string;
export type String_176 = string;
export type String_177 = string;
export type String_178 = string;
export type String_179 = string;
export type Array_15 = String_179[];
export type Null_27 = null;

export interface DECO_COLLECTION_AGENTS_GETOutput {
  /**
   * The retrieved item, or null if not found
   */
  item: Object_62 | Null_27;
}
export interface Object_62 {
  id: String_171;
  title: String_172;
  created_at: String_173;
  updated_at: String_174;
  created_by?: String_175;
  updated_by?: String_176;
  description: String_177;
  instructions: String_178;
  tool_set: Object_63;
}
export interface Object_63 {
  [k: string]: Array_15;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_180 = string;
/**
 * Human-readable title for the entity
 */
export type String_181 = string;
export type String_182 = string;
export type String_183 = string;
export type String_184 = string;
export type String_185 = string;
export type String_186 = string;
export type String_187 = string;
export type String_188 = string;
export type Array_16 = String_188[];

export interface DECO_COLLECTION_AGENTS_INSERTInput {
  data: Object_64;
}
/**
 * Data for the new entity (id may be auto-generated)
 */
export interface Object_64 {
  id: String_180;
  title: String_181;
  created_at: String_182;
  updated_at: String_183;
  created_by?: String_184;
  updated_by?: String_185;
  description: String_186;
  instructions: String_187;
  tool_set: Object_65;
}
export interface Object_65 {
  [k: string]: Array_16;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_189 = string;
/**
 * Human-readable title for the entity
 */
export type String_190 = string;
export type String_191 = string;
export type String_192 = string;
export type String_193 = string;
export type String_194 = string;
export type String_195 = string;
export type String_196 = string;
export type String_197 = string;
export type Array_17 = String_197[];

export interface DECO_COLLECTION_AGENTS_INSERTOutput {
  item: Object_66;
}
/**
 * The created entity with generated id
 */
export interface Object_66 {
  id: String_189;
  title: String_190;
  created_at: String_191;
  updated_at: String_192;
  created_by?: String_193;
  updated_by?: String_194;
  description: String_195;
  instructions: String_196;
  tool_set: Object_67;
}
export interface Object_67 {
  [k: string]: Array_17;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_198 = string;
export type Array_18 = String_198[];
export type String_199 =
  | "eq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "like"
  | "contains";
export type String_200 = "and" | "or" | "not";
export type Array_19 = Object_68[];
export type String_201 = string;
export type Array_21 = String_201[];
export type String_202 = "asc" | "desc";
export type String_203 = "first" | "last";
/**
 * Sort expressions
 */
export type Array_20 = Object_70[];
/**
 * Maximum number of items to return
 */
export type Integer_1 = number;
/**
 * Number of items to skip
 */
export type Integer_2 = number;

export interface DECO_COLLECTION_AGENTS_LISTInput {
  /**
   * Filter expression
   */
  where?: Object_68 | Object_69;
  orderBy?: Array_20;
  limit?: Integer_1;
  offset?: Integer_2;
}
export interface Object_68 {
  field: Array_18;
  operator: String_199;
  value?: unknown;
}
export interface Object_69 {
  operator: String_200;
  conditions: Array_19;
}
export interface Object_70 {
  field: Array_21;
  direction: String_202;
  nulls?: String_203;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_204 = string;
/**
 * Human-readable title for the entity
 */
export type String_205 = string;
export type String_206 = string;
export type String_207 = string;
export type String_208 = string;
export type String_209 = string;
export type String_210 = string;
export type String_211 = string;
export type String_212 = string;
export type Array_23 = String_212[];
/**
 * Array of collection items
 */
export type Array_22 = Object_71[];
/**
 * Total number of matching items (if available)
 */
export type Integer_3 = number;
/**
 * Whether there are more items available
 */
export type Boolean_12 = boolean;

export interface DECO_COLLECTION_AGENTS_LISTOutput {
  items: Array_22;
  totalCount?: Integer_3;
  hasMore?: Boolean_12;
}
export interface Object_71 {
  id: String_204;
  title: String_205;
  created_at: String_206;
  updated_at: String_207;
  created_by?: String_208;
  updated_by?: String_209;
  description: String_210;
  instructions: String_211;
  tool_set: Object_72;
}
export interface Object_72 {
  [k: string]: Array_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to update
 */
export type String_213 = string;
/**
 * Unique identifier for the entity
 */
export type String_214 = string;
/**
 * Human-readable title for the entity
 */
export type String_215 = string;
export type String_216 = string;
export type String_217 = string;
export type String_218 = string;
export type String_219 = string;
export type String_220 = string;
export type String_221 = string;
export type String_222 = string;
export type Array_24 = String_222[];

export interface DECO_COLLECTION_AGENTS_UPDATEInput {
  id: String_213;
  data: Object_73;
}
/**
 * Partial entity data to update
 */
export interface Object_73 {
  id?: String_214;
  title?: String_215;
  created_at?: String_216;
  updated_at?: String_217;
  created_by?: String_218;
  updated_by?: String_219;
  description?: String_220;
  instructions?: String_221;
  tool_set?: Object_74;
}
export interface Object_74 {
  [k: string]: Array_24;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_223 = string;
/**
 * Human-readable title for the entity
 */
export type String_224 = string;
export type String_225 = string;
export type String_226 = string;
export type String_227 = string;
export type String_228 = string;
export type String_229 = string;
export type String_230 = string;
export type String_231 = string;
export type Array_25 = String_231[];

export interface DECO_COLLECTION_AGENTS_UPDATEOutput {
  item: Object_75;
}
/**
 * The updated entity
 */
export interface Object_75 {
  id: String_223;
  title: String_224;
  created_at: String_225;
  updated_at: String_226;
  created_by?: String_227;
  updated_by?: String_228;
  description: String_229;
  instructions: String_230;
  tool_set: Object_76;
}
export interface Object_76 {
  [k: string]: Array_25;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to retrieve
 */
export type String_232 = string;
export type String_233 = string;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_GETInput {
  id: String_232;
  step_id: String_233;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_234 = string;
export type String_235 = string;
export type Null_28 = null;
export type StringNull = String_236 | Null_29;
export type String_236 = string;
export type Null_29 = null;
export type StringNull_1 = String_237 | Null_30;
export type String_237 = string;
export type Null_30 = null;
export type NumberNull = Number_8 | Null_31;
export type Number_8 = number;
export type Null_31 = null;
export type NumberNull_1 = Number_9 | Null_32;
export type Number_9 = number;
export type Null_32 = null;
export type Null_33 = null;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_GETOutput {
  /**
   * The retrieved item, or null if not found
   */
  item: Object_77 | Null_33;
}
export interface Object_77 {
  execution_id: String_234;
  step_id: String_235;
  output?: Object_78 | Null_28;
  error?: StringNull;
  child_workflow_id?: StringNull_1;
  started_at_epoch_ms?: NumberNull;
  completed_at_epoch_ms?: NumberNull_1;
}
export interface Object_78 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to retrieve
 */
export type String_238 = string;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_GET_ALLInput {
  id: String_238;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_239 = string;
export type String_240 = string;
export type Null_34 = null;
export type StringNull_2 = String_241 | Null_35;
export type String_241 = string;
export type Null_35 = null;
export type StringNull_3 = String_242 | Null_36;
export type String_242 = string;
export type Null_36 = null;
export type NumberNull_2 = Number_10 | Null_37;
export type Number_10 = number;
export type Null_37 = null;
export type NumberNull_3 = Number_11 | Null_38;
export type Number_11 = number;
export type Null_38 = null;
/**
 * Array of collection items
 */
export type Array_26 = Object_79[];
/**
 * Total number of matching items (if available)
 */
export type Integer_4 = number;
/**
 * Whether there are more items available
 */
export type Boolean_13 = boolean;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_GET_ALLOutput {
  items: Array_26;
  totalCount?: Integer_4;
  hasMore?: Boolean_13;
}
export interface Object_79 {
  execution_id: String_239;
  step_id: String_240;
  output?: Object_80 | Null_34;
  error?: StringNull_2;
  child_workflow_id?: StringNull_3;
  started_at_epoch_ms?: NumberNull_2;
  completed_at_epoch_ms?: NumberNull_3;
}
export interface Object_80 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_243 = string;
export type String_244 = string;
export type Null_39 = null;
export type StringNull_4 = String_245 | Null_40;
export type String_245 = string;
export type Null_40 = null;
export type StringNull_5 = String_246 | Null_41;
export type String_246 = string;
export type Null_41 = null;
export type NumberNull_4 = Number_12 | Null_42;
export type Number_12 = number;
export type Null_42 = null;
export type NumberNull_5 = Number_13 | Null_43;
export type Number_13 = number;
export type Null_43 = null;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_INSERTInput {
  data: Object_81;
}
/**
 * Data for the new entity (id may be auto-generated)
 */
export interface Object_81 {
  execution_id: String_243;
  step_id: String_244;
  output?: Object_82 | Null_39;
  error?: StringNull_4;
  child_workflow_id?: StringNull_5;
  started_at_epoch_ms?: NumberNull_4;
  completed_at_epoch_ms?: NumberNull_5;
}
export interface Object_82 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_247 = string;
export type String_248 = string;
export type Null_44 = null;
export type StringNull_6 = String_249 | Null_45;
export type String_249 = string;
export type Null_45 = null;
export type StringNull_7 = String_250 | Null_46;
export type String_250 = string;
export type Null_46 = null;
export type NumberNull_6 = Number_14 | Null_47;
export type Number_14 = number;
export type Null_47 = null;
export type NumberNull_7 = Number_15 | Null_48;
export type Number_15 = number;
export type Null_48 = null;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_INSERTOutput {
  item: Object_83;
}
/**
 * The created entity with generated id
 */
export interface Object_83 {
  execution_id: String_247;
  step_id: String_248;
  output?: Object_84 | Null_44;
  error?: StringNull_6;
  child_workflow_id?: StringNull_7;
  started_at_epoch_ms?: NumberNull_6;
  completed_at_epoch_ms?: NumberNull_7;
}
export interface Object_84 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_251 = string;
export type String_252 = string;
export type Null_49 = null;
export type StringNull_8 = String_253 | Null_50;
export type String_253 = string;
export type Null_50 = null;
export type StringNull_9 = String_254 | Null_51;
export type String_254 = string;
export type Null_51 = null;
export type NumberNull_8 = Number_16 | Null_52;
export type Number_16 = number;
export type Null_52 = null;
export type NumberNull_9 = Number_17 | Null_53;
export type Number_17 = number;
export type Null_53 = null;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_UPDATEInput {
  data: Object_85;
}
/**
 * Partial entity data to update
 */
export interface Object_85 {
  execution_id?: String_251;
  step_id?: String_252;
  output?: Object_86 | Null_49;
  error?: StringNull_8;
  child_workflow_id?: StringNull_9;
  started_at_epoch_ms?: NumberNull_8;
  completed_at_epoch_ms?: NumberNull_9;
}
export interface Object_86 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_255 = string;
export type String_256 = string;
export type Null_54 = null;
export type StringNull_10 = String_257 | Null_55;
export type String_257 = string;
export type Null_55 = null;
export type StringNull_11 = String_258 | Null_56;
export type String_258 = string;
export type Null_56 = null;
export type NumberNull_10 = Number_18 | Null_57;
export type Number_18 = number;
export type Null_57 = null;
export type NumberNull_11 = Number_19 | Null_58;
export type Number_19 = number;
export type Null_58 = null;

export interface DECO_COLLECTION_EXECUTION_STEP_RESULTS_UPDATEOutput {
  item: Object_87;
}
/**
 * The updated entity
 */
export interface Object_87 {
  execution_id: String_255;
  step_id: String_256;
  output?: Object_88 | Null_54;
  error?: StringNull_10;
  child_workflow_id?: StringNull_11;
  started_at_epoch_ms?: NumberNull_10;
  completed_at_epoch_ms?: NumberNull_11;
}
export interface Object_88 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to retrieve
 */
export type String_259 = string;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_GETInput {
  id: String_259;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_260 = string;
export type String_261 = string;
export type String_262 = string;
export type String_263 = string;
export type String_264 = string;
export type String_265 = string;
export type String_266 = "pending" | "running" | "completed" | "failed";
export type StringNull_12 = String_267 | Null_59;
export type String_267 = string;
export type Null_59 = null;
export type NumberNull_12 = Number_20 | Null_60;
export type Number_20 = number;
export type Null_60 = null;
export type NumberNull_13 = Number_21 | Null_61;
export type Number_21 = number;
export type Null_61 = null;
export type NumberNull_14 = Number_22 | Null_62;
export type Number_22 = number;
export type Null_62 = null;
export type NumberNull_15 = Number_23 | Null_63;
export type Number_23 = number;
export type Null_63 = null;
export type Null_64 = null;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_GETOutput {
  /**
   * The retrieved item, or null if not found
   */
  item: Object_89 | Null_64;
}
export interface Object_89 {
  id: String_260;
  created_at: String_261;
  updated_at: String_262;
  created_by?: String_263;
  updated_by?: String_264;
  workflow_id: String_265;
  status: String_266;
  output?: Object_90;
  error?: StringNull_12;
  recovery_attempts?: NumberNull_12;
  workflow_timeout_ms?: NumberNull_13;
  workflow_deadline_epoch_ms?: NumberNull_14;
  inputs?: Object_91;
  started_at_epoch_ms?: NumberNull_15;
}
export interface Object_90 {
  [k: string]: unknown;
}
export interface Object_91 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_268 = string;
export type String_269 = string;
export type String_270 = string;
export type String_271 = string;
export type String_272 = string;
export type String_273 = string;
export type String_274 = "pending" | "running" | "completed" | "failed";
export type StringNull_13 = String_275 | Null_65;
export type String_275 = string;
export type Null_65 = null;
export type NumberNull_16 = Number_24 | Null_66;
export type Number_24 = number;
export type Null_66 = null;
export type NumberNull_17 = Number_25 | Null_67;
export type Number_25 = number;
export type Null_67 = null;
export type NumberNull_18 = Number_26 | Null_68;
export type Number_26 = number;
export type Null_68 = null;
export type NumberNull_19 = Number_27 | Null_69;
export type Number_27 = number;
export type Null_69 = null;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_INSERTInput {
  data: Object_92;
}
/**
 * Data for the new entity (id may be auto-generated)
 */
export interface Object_92 {
  id: String_268;
  created_at: String_269;
  updated_at: String_270;
  created_by?: String_271;
  updated_by?: String_272;
  workflow_id: String_273;
  status: String_274;
  output?: Object_93;
  error?: StringNull_13;
  recovery_attempts?: NumberNull_16;
  workflow_timeout_ms?: NumberNull_17;
  workflow_deadline_epoch_ms?: NumberNull_18;
  inputs?: Object_94;
  started_at_epoch_ms?: NumberNull_19;
}
export interface Object_93 {
  [k: string]: unknown;
}
export interface Object_94 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_276 = string;
export type String_277 = string;
export type String_278 = string;
export type String_279 = string;
export type String_280 = string;
export type String_281 = string;
export type String_282 = "pending" | "running" | "completed" | "failed";
export type StringNull_14 = String_283 | Null_70;
export type String_283 = string;
export type Null_70 = null;
export type NumberNull_20 = Number_28 | Null_71;
export type Number_28 = number;
export type Null_71 = null;
export type NumberNull_21 = Number_29 | Null_72;
export type Number_29 = number;
export type Null_72 = null;
export type NumberNull_22 = Number_30 | Null_73;
export type Number_30 = number;
export type Null_73 = null;
export type NumberNull_23 = Number_31 | Null_74;
export type Number_31 = number;
export type Null_74 = null;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_INSERTOutput {
  item: Object_95;
}
/**
 * The created entity with generated id
 */
export interface Object_95 {
  id: String_276;
  created_at: String_277;
  updated_at: String_278;
  created_by?: String_279;
  updated_by?: String_280;
  workflow_id: String_281;
  status: String_282;
  output?: Object_96;
  error?: StringNull_14;
  recovery_attempts?: NumberNull_20;
  workflow_timeout_ms?: NumberNull_21;
  workflow_deadline_epoch_ms?: NumberNull_22;
  inputs?: Object_97;
  started_at_epoch_ms?: NumberNull_23;
}
export interface Object_96 {
  [k: string]: unknown;
}
export interface Object_97 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_284 = string;
export type Array_27 = String_284[];
export type String_285 =
  | "eq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "like"
  | "contains";
export type String_286 = "and" | "or" | "not";
export type Array_28 = Object_98[];
export type String_287 = string;
export type Array_30 = String_287[];
export type String_288 = "asc" | "desc";
export type String_289 = "first" | "last";
/**
 * Sort expressions
 */
export type Array_29 = Object_100[];
/**
 * Maximum number of items to return
 */
export type Integer_5 = number;
/**
 * Number of items to skip
 */
export type Integer_6 = number;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_LISTInput {
  /**
   * Filter expression
   */
  where?: Object_98 | Object_99;
  orderBy?: Array_29;
  limit?: Integer_5;
  offset?: Integer_6;
}
export interface Object_98 {
  field: Array_27;
  operator: String_285;
  value?: unknown;
}
export interface Object_99 {
  operator: String_286;
  conditions: Array_28;
}
export interface Object_100 {
  field: Array_30;
  direction: String_288;
  nulls?: String_289;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_290 = string;
export type String_291 = string;
export type String_292 = string;
export type String_293 = string;
export type String_294 = string;
export type String_295 = string;
export type String_296 = "pending" | "running" | "completed" | "failed";
export type StringNull_15 = String_297 | Null_75;
export type String_297 = string;
export type Null_75 = null;
export type NumberNull_24 = Number_32 | Null_76;
export type Number_32 = number;
export type Null_76 = null;
export type NumberNull_25 = Number_33 | Null_77;
export type Number_33 = number;
export type Null_77 = null;
export type NumberNull_26 = Number_34 | Null_78;
export type Number_34 = number;
export type Null_78 = null;
export type NumberNull_27 = Number_35 | Null_79;
export type Number_35 = number;
export type Null_79 = null;
/**
 * Array of collection items
 */
export type Array_31 = Object_101[];
/**
 * Total number of matching items (if available)
 */
export type Integer_7 = number;
/**
 * Whether there are more items available
 */
export type Boolean_14 = boolean;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_LISTOutput {
  items: Array_31;
  totalCount?: Integer_7;
  hasMore?: Boolean_14;
}
export interface Object_101 {
  id: String_290;
  created_at: String_291;
  updated_at: String_292;
  created_by?: String_293;
  updated_by?: String_294;
  workflow_id: String_295;
  status: String_296;
  output?: Object_102;
  error?: StringNull_15;
  recovery_attempts?: NumberNull_24;
  workflow_timeout_ms?: NumberNull_25;
  workflow_deadline_epoch_ms?: NumberNull_26;
  inputs?: Object_103;
  started_at_epoch_ms?: NumberNull_27;
}
export interface Object_102 {
  [k: string]: unknown;
}
export interface Object_103 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to update
 */
export type String_298 = string;
/**
 * Unique identifier for the entity
 */
export type String_299 = string;
export type String_300 = string;
export type String_301 = string;
export type String_302 = string;
export type String_303 = string;
export type String_304 = string;
export type String_305 = "pending" | "running" | "completed" | "failed";
export type StringNull_16 = String_306 | Null_80;
export type String_306 = string;
export type Null_80 = null;
export type NumberNull_28 = Number_36 | Null_81;
export type Number_36 = number;
export type Null_81 = null;
export type NumberNull_29 = Number_37 | Null_82;
export type Number_37 = number;
export type Null_82 = null;
export type NumberNull_30 = Number_38 | Null_83;
export type Number_38 = number;
export type Null_83 = null;
export type NumberNull_31 = Number_39 | Null_84;
export type Number_39 = number;
export type Null_84 = null;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_UPDATEInput {
  id: String_298;
  data: Object_104;
}
/**
 * Partial entity data to update
 */
export interface Object_104 {
  id?: String_299;
  created_at?: String_300;
  updated_at?: String_301;
  created_by?: String_302;
  updated_by?: String_303;
  workflow_id?: String_304;
  status?: String_305;
  output?: Object_105;
  error?: StringNull_16;
  recovery_attempts?: NumberNull_28;
  workflow_timeout_ms?: NumberNull_29;
  workflow_deadline_epoch_ms?: NumberNull_30;
  inputs?: Object_106;
  started_at_epoch_ms?: NumberNull_31;
}
export interface Object_105 {
  [k: string]: unknown;
}
export interface Object_106 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_307 = string;
export type String_308 = string;
export type String_309 = string;
export type String_310 = string;
export type String_311 = string;
export type String_312 = string;
export type String_313 = "pending" | "running" | "completed" | "failed";
export type StringNull_17 = String_314 | Null_85;
export type String_314 = string;
export type Null_85 = null;
export type NumberNull_32 = Number_40 | Null_86;
export type Number_40 = number;
export type Null_86 = null;
export type NumberNull_33 = Number_41 | Null_87;
export type Number_41 = number;
export type Null_87 = null;
export type NumberNull_34 = Number_42 | Null_88;
export type Number_42 = number;
export type Null_88 = null;
export type NumberNull_35 = Number_43 | Null_89;
export type Number_43 = number;
export type Null_89 = null;

export interface DECO_COLLECTION_WORKFLOW_EXECUTIONS_UPDATEOutput {
  item: Object_107;
}
/**
 * The updated entity
 */
export interface Object_107 {
  id: String_307;
  created_at: String_308;
  updated_at: String_309;
  created_by?: String_310;
  updated_by?: String_311;
  workflow_id: String_312;
  status: String_313;
  output?: Object_108;
  error?: StringNull_17;
  recovery_attempts?: NumberNull_32;
  workflow_timeout_ms?: NumberNull_33;
  workflow_deadline_epoch_ms?: NumberNull_34;
  inputs?: Object_109;
  started_at_epoch_ms?: NumberNull_35;
}
export interface Object_108 {
  [k: string]: unknown;
}
export interface Object_109 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to delete
 */
export type String_315 = string;

export interface DECO_COLLECTION_WORKFLOWS_DELETEInput {
  id: String_315;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the deletion was successful
 */
export type Boolean_15 = boolean;
/**
 * ID of the deleted entity
 */
export type String_316 = string;

export interface DECO_COLLECTION_WORKFLOWS_DELETEOutput {
  success: Boolean_15;
  id: String_316;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to retrieve
 */
export type String_317 = string;

export interface DECO_COLLECTION_WORKFLOWS_GETInput {
  id: String_317;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_318 = string;
/**
 * Human-readable title for the entity
 */
export type String_319 = string;
export type String_320 = string;
export type String_321 = string;
export type String_322 = string;
export type String_323 = string;
export type String_324 = string;
export type String_325 = string;
export type String_326 = string;
export type String_327 = string;
export type String_328 = string;
export type String_329 = string;
export type String_330 = "pending" | "running" | "completed" | "failed";
export type String_331 = string;
export type String_332 = string;
export type Array_33 = String_332[];
export type Array_32 = Object_111[];
export type Null_90 = null;

export interface DECO_COLLECTION_WORKFLOWS_GETOutput {
  /**
   * The retrieved item, or null if not found
   */
  item: Object_110 | Null_90;
}
export interface Object_110 {
  id: String_318;
  title: String_319;
  created_at: String_320;
  updated_at: String_321;
  created_by?: String_322;
  updated_by?: String_323;
  name: String_324;
  description: String_325;
  steps: Array_32;
}
export interface Object_111 {
  name: String_326;
  inputSchema: Object_112;
  outputSchema: Object_113;
  execute: Object_114 | String_329;
  status?: String_330;
  error?: String_331;
  logs?: Array_33;
}
export interface Object_112 {
  [k: string]: unknown;
}
export interface Object_113 {
  [k: string]: unknown;
}
export interface Object_114 {
  connectionId: String_327;
  toolName: String_328;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_333 = string;
/**
 * Human-readable title for the entity
 */
export type String_334 = string;
export type String_335 = string;
export type String_336 = string;
export type String_337 = string;
export type String_338 = string;
export type String_339 = string;
export type String_340 = string;
export type String_341 = string;
export type String_342 = string;
export type String_343 = string;
export type String_344 = string;
export type String_345 = "pending" | "running" | "completed" | "failed";
export type String_346 = string;
export type String_347 = string;
export type Array_35 = String_347[];
export type Array_34 = Object_116[];

export interface DECO_COLLECTION_WORKFLOWS_INSERTInput {
  data: Object_115;
}
/**
 * Data for the new entity (id may be auto-generated)
 */
export interface Object_115 {
  id: String_333;
  title: String_334;
  created_at: String_335;
  updated_at: String_336;
  created_by?: String_337;
  updated_by?: String_338;
  name: String_339;
  description: String_340;
  steps: Array_34;
}
export interface Object_116 {
  name: String_341;
  inputSchema: Object_117;
  outputSchema: Object_118;
  execute: Object_119 | String_344;
  status?: String_345;
  error?: String_346;
  logs?: Array_35;
}
export interface Object_117 {
  [k: string]: unknown;
}
export interface Object_118 {
  [k: string]: unknown;
}
export interface Object_119 {
  connectionId: String_342;
  toolName: String_343;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_348 = string;
/**
 * Human-readable title for the entity
 */
export type String_349 = string;
export type String_350 = string;
export type String_351 = string;
export type String_352 = string;
export type String_353 = string;
export type String_354 = string;
export type String_355 = string;
export type String_356 = string;
export type String_357 = string;
export type String_358 = string;
export type String_359 = string;
export type String_360 = "pending" | "running" | "completed" | "failed";
export type String_361 = string;
export type String_362 = string;
export type Array_37 = String_362[];
export type Array_36 = Object_121[];

export interface DECO_COLLECTION_WORKFLOWS_INSERTOutput {
  item: Object_120;
}
/**
 * The created entity with generated id
 */
export interface Object_120 {
  id: String_348;
  title: String_349;
  created_at: String_350;
  updated_at: String_351;
  created_by?: String_352;
  updated_by?: String_353;
  name: String_354;
  description: String_355;
  steps: Array_36;
}
export interface Object_121 {
  name: String_356;
  inputSchema: Object_122;
  outputSchema: Object_123;
  execute: Object_124 | String_359;
  status?: String_360;
  error?: String_361;
  logs?: Array_37;
}
export interface Object_122 {
  [k: string]: unknown;
}
export interface Object_123 {
  [k: string]: unknown;
}
export interface Object_124 {
  connectionId: String_357;
  toolName: String_358;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_363 = string;
export type Array_38 = String_363[];
export type String_364 =
  | "eq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "like"
  | "contains";
export type String_365 = "and" | "or" | "not";
export type Array_39 = Object_125[];
export type String_366 = string;
export type Array_41 = String_366[];
export type String_367 = "asc" | "desc";
export type String_368 = "first" | "last";
/**
 * Sort expressions
 */
export type Array_40 = Object_127[];
/**
 * Maximum number of items to return
 */
export type Integer_8 = number;
/**
 * Number of items to skip
 */
export type Integer_9 = number;

export interface DECO_COLLECTION_WORKFLOWS_LISTInput {
  /**
   * Filter expression
   */
  where?: Object_125 | Object_126;
  orderBy?: Array_40;
  limit?: Integer_8;
  offset?: Integer_9;
}
export interface Object_125 {
  field: Array_38;
  operator: String_364;
  value?: unknown;
}
export interface Object_126 {
  operator: String_365;
  conditions: Array_39;
}
export interface Object_127 {
  field: Array_41;
  direction: String_367;
  nulls?: String_368;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_369 = string;
/**
 * Human-readable title for the entity
 */
export type String_370 = string;
export type String_371 = string;
export type String_372 = string;
export type String_373 = string;
export type String_374 = string;
export type String_375 = string;
export type String_376 = string;
export type String_377 = string;
export type String_378 = string;
export type String_379 = string;
export type String_380 = string;
export type String_381 = "pending" | "running" | "completed" | "failed";
export type String_382 = string;
export type String_383 = string;
export type Array_44 = String_383[];
export type Array_43 = Object_129[];
/**
 * Array of collection items
 */
export type Array_42 = Object_128[];
/**
 * Total number of matching items (if available)
 */
export type Integer_10 = number;
/**
 * Whether there are more items available
 */
export type Boolean_16 = boolean;

export interface DECO_COLLECTION_WORKFLOWS_LISTOutput {
  items: Array_42;
  totalCount?: Integer_10;
  hasMore?: Boolean_16;
}
export interface Object_128 {
  id: String_369;
  title: String_370;
  created_at: String_371;
  updated_at: String_372;
  created_by?: String_373;
  updated_by?: String_374;
  name: String_375;
  description: String_376;
  steps: Array_43;
}
export interface Object_129 {
  name: String_377;
  inputSchema: Object_130;
  outputSchema: Object_131;
  execute: Object_132 | String_380;
  status?: String_381;
  error?: String_382;
  logs?: Array_44;
}
export interface Object_130 {
  [k: string]: unknown;
}
export interface Object_131 {
  [k: string]: unknown;
}
export interface Object_132 {
  connectionId: String_378;
  toolName: String_379;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to update
 */
export type String_384 = string;
/**
 * Unique identifier for the entity
 */
export type String_385 = string;
/**
 * Human-readable title for the entity
 */
export type String_386 = string;
export type String_387 = string;
export type String_388 = string;
export type String_389 = string;
export type String_390 = string;
export type String_391 = string;
export type String_392 = string;
export type String_393 = string;
export type String_394 = string;
export type String_395 = string;
export type String_396 = string;
export type String_397 = "pending" | "running" | "completed" | "failed";
export type String_398 = string;
export type String_399 = string;
export type Array_46 = String_399[];
export type Array_45 = Object_134[];

export interface DECO_COLLECTION_WORKFLOWS_UPDATEInput {
  id: String_384;
  data: Object_133;
}
/**
 * Partial entity data to update
 */
export interface Object_133 {
  id?: String_385;
  title?: String_386;
  created_at?: String_387;
  updated_at?: String_388;
  created_by?: String_389;
  updated_by?: String_390;
  name?: String_391;
  description?: String_392;
  steps?: Array_45;
}
export interface Object_134 {
  name: String_393;
  inputSchema: Object_135;
  outputSchema: Object_136;
  execute: Object_137 | String_396;
  status?: String_397;
  error?: String_398;
  logs?: Array_46;
}
export interface Object_135 {
  [k: string]: unknown;
}
export interface Object_136 {
  [k: string]: unknown;
}
export interface Object_137 {
  connectionId: String_394;
  toolName: String_395;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_400 = string;
/**
 * Human-readable title for the entity
 */
export type String_401 = string;
export type String_402 = string;
export type String_403 = string;
export type String_404 = string;
export type String_405 = string;
export type String_406 = string;
export type String_407 = string;
export type String_408 = string;
export type String_409 = string;
export type String_410 = string;
export type String_411 = string;
export type String_412 = "pending" | "running" | "completed" | "failed";
export type String_413 = string;
export type String_414 = string;
export type Array_48 = String_414[];
export type Array_47 = Object_139[];

export interface DECO_COLLECTION_WORKFLOWS_UPDATEOutput {
  item: Object_138;
}
/**
 * The updated entity
 */
export interface Object_138 {
  id: String_400;
  title: String_401;
  created_at: String_402;
  updated_at: String_403;
  created_by?: String_404;
  updated_by?: String_405;
  name: String_406;
  description: String_407;
  steps: Array_47;
}
export interface Object_139 {
  name: String_408;
  inputSchema: Object_140;
  outputSchema: Object_141;
  execute: Object_142 | String_411;
  status?: String_412;
  error?: String_413;
  logs?: Array_48;
}
export interface Object_140 {
  [k: string]: unknown;
}
export interface Object_141 {
  [k: string]: unknown;
}
export interface Object_142 {
  connectionId: String_409;
  toolName: String_410;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_415 = string;
export type StringNull_18 = String_416 | Null_91;
export type String_416 = string;
export type Null_91 = null;
export type StringNull_19 = String_417 | Null_92;
export type String_417 = string;
export type Null_92 = null;
export type String_418 = string;

export interface GET_USEROutput {
  id: String_415;
  name: StringNull_18;
  avatar: StringNull_19;
  email: String_418;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_419 = string;

export interface START_EXECUTIONInput {
  executionId: String_419;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_17 = boolean;

export interface START_EXECUTIONOutput {
  success: Boolean_17;
  result?: unknown;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  INTEGRATIONS: z.object({
    value: z.string(),
    __type: z.literal("@deco/integrations").default("@deco/integrations"),
  }),
  DATABASE: z.object({
    value: z.string(),
    __type: z.literal("@deco/database").default("@deco/database"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  INTEGRATIONS: Mcp<{
    /**
     * Get the schema for a marketplace app
     */
    DECO_GET_APP_SCHEMA: (
      input: DECO_GET_APP_SCHEMAInput,
    ) => Promise<DECO_GET_APP_SCHEMAOutput>;
    /**
     * Install an integration. To know the available ids, use the DECO_INTEGRATIONS_SEARCH tool. Also, after installing, enable the integration using the INTEGRATION_ENABLE tool.
     */
    DECO_INTEGRATION_INSTALL: (
      input: DECO_INTEGRATION_INSTALLInput,
    ) => Promise<DECO_INTEGRATION_INSTALLOutput>;
    /**
     * Start the OAuth flow for an integration
     */
    DECO_INTEGRATION_OAUTH_START: (
      input: DECO_INTEGRATION_OAUTH_STARTInput,
    ) => Promise<DECO_INTEGRATION_OAUTH_STARTOutput>;
    /**
     * Search for integrations in both marketplace and installed.
     * If no query is provided, it will return all installed integrations. For better results, try searching for the service name, i.e. GoogleSheets, GoogleCalendar, Notion, etc.
     * It's always handy to search for installed integrations with no query, since all integrations will be returned. Also, some integrations are handy agents that may help you with common tasks.
     */
    DECO_INTEGRATIONS_SEARCH: (
      input: DECO_INTEGRATIONS_SEARCHInput,
    ) => Promise<DECO_INTEGRATIONS_SEARCHOutput>;
    /**
     * Call a tool from an integration. If you have the integration ID (from INTEGRATIONS_LIST or INTEGRATIONS_GET), prefer using 'id' over 'connection'. The ID ensures you're calling the correct configured integration. Use 'connection' only when you need to call a tool from a new or unconfigured integration.
     */
    INTEGRATIONS_CALL_TOOL: (
      input: INTEGRATIONS_CALL_TOOLInput,
    ) => Promise<INTEGRATIONS_CALL_TOOLOutput>;
    /**
     * Create a new integration
     */
    INTEGRATIONS_CREATE: (
      input: INTEGRATIONS_CREATEInput,
    ) => Promise<INTEGRATIONS_CREATEOutput>;
    /**
     * Delete an integration by id
     */
    INTEGRATIONS_DELETE: (
      input: INTEGRATIONS_DELETEInput,
    ) => Promise<INTEGRATIONS_DELETEOutput>;
    /**
     * Get an integration by id with tools
     */
    INTEGRATIONS_GET: (
      input: INTEGRATIONS_GETInput,
    ) => Promise<INTEGRATIONS_GETOutput>;
    /**
     * Get the API key for an integration
     */
    INTEGRATIONS_GET_API_KEY: (
      input: INTEGRATIONS_GET_API_KEYInput,
    ) => Promise<INTEGRATIONS_GET_API_KEYOutput>;
    /**
     * List all integrations with their tools
     */
    INTEGRATIONS_LIST: (
      input: INTEGRATIONS_LISTInput,
    ) => Promise<INTEGRATIONS_LISTOutput>;
    /**
     * Update an existing integration
     */
    INTEGRATIONS_UPDATE: (
      input: INTEGRATIONS_UPDATEInput,
    ) => Promise<INTEGRATIONS_UPDATEOutput>;
  }>;
  DATABASE: Mcp<{
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_GET_META: (
      input: DATABASES_GET_METAInput,
    ) => Promise<DATABASES_GET_METAOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RECOVERY: (
      input: DATABASES_RECOVERYInput,
    ) => Promise<DATABASES_RECOVERYOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RUN_SQL: (
      input: DATABASES_RUN_SQLInput,
    ) => Promise<DATABASES_RUN_SQLOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
  }>;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Delete an agent by ID
     */
    DECO_COLLECTION_AGENTS_DELETE: (
      input: DECO_COLLECTION_AGENTS_DELETEInput,
    ) => Promise<DECO_COLLECTION_AGENTS_DELETEOutput>;
    /**
     * Get a single agent by ID
     */
    DECO_COLLECTION_AGENTS_GET: (
      input: DECO_COLLECTION_AGENTS_GETInput,
    ) => Promise<DECO_COLLECTION_AGENTS_GETOutput>;
    /**
     * Create a new agent
     */
    DECO_COLLECTION_AGENTS_INSERT: (
      input: DECO_COLLECTION_AGENTS_INSERTInput,
    ) => Promise<DECO_COLLECTION_AGENTS_INSERTOutput>;
    /**
     * List agents with filtering, sorting, and pagination
     */
    DECO_COLLECTION_AGENTS_LIST: (
      input: DECO_COLLECTION_AGENTS_LISTInput,
    ) => Promise<DECO_COLLECTION_AGENTS_LISTOutput>;
    /**
     * Update an existing agent
     */
    DECO_COLLECTION_AGENTS_UPDATE: (
      input: DECO_COLLECTION_AGENTS_UPDATEInput,
    ) => Promise<DECO_COLLECTION_AGENTS_UPDATEOutput>;
    /**
     * Get an execution step result by execution and step IDs
     */
    DECO_COLLECTION_EXECUTION_STEP_RESULTS_GET: (
      input: DECO_COLLECTION_EXECUTION_STEP_RESULTS_GETInput,
    ) => Promise<DECO_COLLECTION_EXECUTION_STEP_RESULTS_GETOutput>;
    /**
     * Get all execution step results for an execution
     */
    DECO_COLLECTION_EXECUTION_STEP_RESULTS_GET_ALL: (
      input: DECO_COLLECTION_EXECUTION_STEP_RESULTS_GET_ALLInput,
    ) => Promise<DECO_COLLECTION_EXECUTION_STEP_RESULTS_GET_ALLOutput>;
    /**
     * Create a new execution step result
     */
    DECO_COLLECTION_EXECUTION_STEP_RESULTS_INSERT: (
      input: DECO_COLLECTION_EXECUTION_STEP_RESULTS_INSERTInput,
    ) => Promise<DECO_COLLECTION_EXECUTION_STEP_RESULTS_INSERTOutput>;
    /**
     * Update an existing execution step result
     */
    DECO_COLLECTION_EXECUTION_STEP_RESULTS_UPDATE: (
      input: DECO_COLLECTION_EXECUTION_STEP_RESULTS_UPDATEInput,
    ) => Promise<DECO_COLLECTION_EXECUTION_STEP_RESULTS_UPDATEOutput>;
    /**
     * Get a single execution by ID
     */
    DECO_COLLECTION_WORKFLOW_EXECUTIONS_GET: (
      input: DECO_COLLECTION_WORKFLOW_EXECUTIONS_GETInput,
    ) => Promise<DECO_COLLECTION_WORKFLOW_EXECUTIONS_GETOutput>;
    /**
     * Create a new execution
     */
    DECO_COLLECTION_WORKFLOW_EXECUTIONS_INSERT: (
      input: DECO_COLLECTION_WORKFLOW_EXECUTIONS_INSERTInput,
    ) => Promise<DECO_COLLECTION_WORKFLOW_EXECUTIONS_INSERTOutput>;
    /**
     * List workflow_executions with filtering, sorting, and pagination
     */
    DECO_COLLECTION_WORKFLOW_EXECUTIONS_LIST: (
      input: DECO_COLLECTION_WORKFLOW_EXECUTIONS_LISTInput,
    ) => Promise<DECO_COLLECTION_WORKFLOW_EXECUTIONS_LISTOutput>;
    /**
     * Update an existing execution
     */
    DECO_COLLECTION_WORKFLOW_EXECUTIONS_UPDATE: (
      input: DECO_COLLECTION_WORKFLOW_EXECUTIONS_UPDATEInput,
    ) => Promise<DECO_COLLECTION_WORKFLOW_EXECUTIONS_UPDATEOutput>;
    /**
     * Delete a workflow by ID
     */
    DECO_COLLECTION_WORKFLOWS_DELETE: (
      input: DECO_COLLECTION_WORKFLOWS_DELETEInput,
    ) => Promise<DECO_COLLECTION_WORKFLOWS_DELETEOutput>;
    /**
     * Get a single workflow by ID
     */
    DECO_COLLECTION_WORKFLOWS_GET: (
      input: DECO_COLLECTION_WORKFLOWS_GETInput,
    ) => Promise<DECO_COLLECTION_WORKFLOWS_GETOutput>;
    /**
     * Create a new workflow
     */
    DECO_COLLECTION_WORKFLOWS_INSERT: (
      input: DECO_COLLECTION_WORKFLOWS_INSERTInput,
    ) => Promise<DECO_COLLECTION_WORKFLOWS_INSERTOutput>;
    /**
     * List workflows with filtering, sorting, and pagination
     */
    DECO_COLLECTION_WORKFLOWS_LIST: (
      input: DECO_COLLECTION_WORKFLOWS_LISTInput,
    ) => Promise<DECO_COLLECTION_WORKFLOWS_LISTOutput>;
    /**
     * Update an existing workflow
     */
    DECO_COLLECTION_WORKFLOWS_UPDATE: (
      input: DECO_COLLECTION_WORKFLOWS_UPDATEInput,
    ) => Promise<DECO_COLLECTION_WORKFLOWS_UPDATEOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * Run one or more MCP tools with durable execution
     */
    START_EXECUTION: (
      input: START_EXECUTIONInput,
    ) => Promise<START_EXECUTIONOutput>;
  }>;
}

export const Scopes = {
  INTEGRATIONS: {
    DECO_GET_APP_SCHEMA: "INTEGRATIONS::DECO_GET_APP_SCHEMA",
    DECO_INTEGRATION_INSTALL: "INTEGRATIONS::DECO_INTEGRATION_INSTALL",
    DECO_INTEGRATION_OAUTH_START: "INTEGRATIONS::DECO_INTEGRATION_OAUTH_START",
    DECO_INTEGRATIONS_SEARCH: "INTEGRATIONS::DECO_INTEGRATIONS_SEARCH",
    INTEGRATIONS_CALL_TOOL: "INTEGRATIONS::INTEGRATIONS_CALL_TOOL",
    INTEGRATIONS_CREATE: "INTEGRATIONS::INTEGRATIONS_CREATE",
    INTEGRATIONS_DELETE: "INTEGRATIONS::INTEGRATIONS_DELETE",
    INTEGRATIONS_GET: "INTEGRATIONS::INTEGRATIONS_GET",
    INTEGRATIONS_GET_API_KEY: "INTEGRATIONS::INTEGRATIONS_GET_API_KEY",
    INTEGRATIONS_LIST: "INTEGRATIONS::INTEGRATIONS_LIST",
    INTEGRATIONS_UPDATE: "INTEGRATIONS::INTEGRATIONS_UPDATE",
  },
  DATABASE: {
    DATABASES_GET_META: "DATABASE::DATABASES_GET_META",
    DATABASES_RECOVERY: "DATABASE::DATABASES_RECOVERY",
    DATABASES_RUN_SQL: "DATABASE::DATABASES_RUN_SQL",
    DECO_CHAT_VIEWS_LIST: "DATABASE::DECO_CHAT_VIEWS_LIST",
  },
};
