// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATABASES_GET_METAInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Number = number;

export interface DATABASES_GET_METAOutput {
  bytes?: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date to recover to
 */
export type String = string;

export interface DATABASES_RECOVERYInput {
  date: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DATABASES_RECOVERYOutput {
  success: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The SQL query to run
 */
export type String_1 = string;
/**
 * The parameters to pass to the SQL query
 */
export type Array = unknown[];

export interface DATABASES_RUN_SQLInput {
  sql: String_1;
  params?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_1 = boolean;
export type Number_1 = number;
export type Number_2 = number;
export type Number_3 = number;
export type Number_4 = number;
export type Number_5 = number;
export type Boolean_2 = boolean;
export type String_2 = "WNAM" | "ENAM" | "WEUR" | "EEUR" | "APAC" | "OC";
export type Number_6 = number;
export type Number_7 = number;
export type Array_2 = unknown[];
export type Boolean_3 = boolean;
export type Array_1 = Object[];

export interface DATABASES_RUN_SQLOutput {
  result: Array_1;
}
export interface Object {
  meta?: Object_1;
  results?: Array_2;
  success?: Boolean_3;
}
export interface Object_1 {
  changed_db?: Boolean_1;
  changes?: Number_1;
  duration?: Number_2;
  last_row_id?: Number_3;
  rows_read?: Number_4;
  rows_written?: Number_5;
  served_by_primary?: Boolean_2;
  served_by_region?: String_2;
  size_after?: Number_6;
  timings?: Object_2;
}
export interface Object_2 {
  sql_duration_ms?: Number_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type String_6 = string;
export type String_7 = string;
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;
export type String_11 = string;
export type Array_4 = String_11[];
export type String_12 = string;
export type String_13 = "none" | "open" | "autoPin";
export type Array_3 = Object_3[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_3;
}
export interface Object_3 {
  id?: String_3;
  name?: String_4;
  title: String_5;
  description?: String_6;
  icon: String_7;
  url?: String_8;
  mimeTypePattern?: String_9;
  resourceName?: String_10;
  tools?: Array_4;
  prompt?: String_12;
  installBehavior?: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_14 = string;

export interface DECO_GET_APP_SCHEMAInput {
  appName: String_14;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_15 = string;
export type Array_5 = String_15[];

export interface DECO_GET_APP_SCHEMAOutput {
  schema?: unknown;
  scopes?: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The id of the integration to install. To know the available ids, use the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_16 = string;
/**
 * The provider of the integration to install. To know the available providers, use the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_17 = string;
/**
 * The id of the app to install the integration for. To know the available app ids, use the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_18 = string;

export interface DECO_INTEGRATION_INSTALLInput {
  id: String_16;
  provider?: String_17;
  appId?: String_18;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The id of the installation. Use this id to enable the integration using the DECO_INTEGRATIONS_SEARCH tool
 */
export type String_19 = string;

export interface DECO_INTEGRATION_INSTALLOutput {
  installationId: String_19;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The id of the integration to start the OAuth flow for
 */
export type String_20 = string;
/**
 * The return URL for the OAuth flow. Will come with a query param including the mcp URL.
 */
export type String_21 = string;
/**
 * The install id of the integration to start the OAuth flow for
 */
export type String_22 = string;
/**
 * The provider of the integration to start the OAuth flow for
 */
export type String_23 = string;

export interface DECO_INTEGRATION_OAUTH_STARTInput {
  appName: String_20;
  returnUrl: String_21;
  installId: String_22;
  provider?: String_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_INTEGRATION_OAUTH_STARTOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The query to search for
 */
export type String_24 = string;
/**
 * Whether to show contracts
 */
export type Boolean_4 = boolean;

export interface DECO_INTEGRATIONS_SEARCHInput {
  query?: String_24;
  showContracts?: Boolean_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_25 = string;
export type String_26 = string;
export type String_27 = string;
export type String_28 = string;
export type String_29 = string;
export type Null = null;
export type String_30 = string;
export type Null_1 = null;
export type String_31 = string;
export type Null_2 = null;
export type Boolean_5 = boolean;
export type Null_3 = null;
export type String_32 = "HTTP";
export type String_33 = string;
export type String_34 = string;
export type String_35 = "SSE";
export type String_36 = string;
export type String_37 = string;
export type String_38 = string;
export type String_39 = "Websocket";
export type String_40 = string;
export type String_41 = string;
export type String_42 = "Deco";
export type String_43 = string;
export type String_44 = string;
export type String_45 = "INNATE";
export type String_46 = string;
export type String_47 = string;
export type Null_4 = null;
export type String_48 = string;
export type Null_5 = null;
/**
 * The name of the tool
 */
export type String_49 = string;
/**
 * The description of the tool
 */
export type String_50 = string;
export type Array_7 = (Object_12 & Object_14)[];
export type Null_6 = null;
export type String_51 = string;
export type String_52 = string;
/**
 * The Integrations that match the query
 */
export type Array_6 = (Object_4 & Object_16)[];

export interface DECO_INTEGRATIONS_SEARCHOutput {
  integrations: Array_6;
}
export interface Object_4 {
  id: String_25;
  name: String_26;
  description?: String_27;
  icon?: String_28;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_29
      )
    | Null;
  appName?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_30
      )
    | Null_1;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_31
      )
    | Null_2;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_5
      )
    | Null_3;
  connection: Object_5 | Object_6 | Object_8 | Object_9 | Object_10;
  metadata?: Object_11 | Null_4;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_48
      )
    | Null_5;
  tools?: Array_7 | Null_6;
}
export interface Object_5 {
  type: String_32;
  url: String_33;
  token?: String_34;
}
export interface Object_6 {
  type: String_35;
  url: String_36;
  token?: String_37;
  headers?: Object_7;
}
export interface Object_7 {
  [k: string]: String_38;
}
export interface Object_8 {
  type: String_39;
  url: String_40;
  token?: String_41;
}
export interface Object_9 {
  type: String_42;
  tenant: String_43;
  token?: String_44;
}
export interface Object_10 {
  type: String_45;
  name: String_46;
  workspace?: String_47;
}
export interface Object_11 {
  [k: string]: unknown;
}
export interface Object_12 {
  name: String_49;
  inputSchema: Object_13;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_13 {
  [k: string]: unknown;
}
export interface Object_14 {
  description?: String_50;
  outputSchema?: Object_15;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_15 {
  [k: string]: unknown;
}
export interface Object_16 {
  provider: String_51;
  friendlyName?: String_52;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_53 = string;
export type String_54 = "HTTP";
export type String_55 = string;
export type String_56 = string;
export type String_57 = "SSE";
export type String_58 = string;
export type String_59 = string;
export type String_60 = string;
export type String_61 = "Websocket";
export type String_62 = string;
export type String_63 = string;
export type String_64 = "Deco";
export type String_65 = string;
export type String_66 = string;
export type String_67 = "INNATE";
export type String_68 = string;
export type String_69 = string;
export type String_70 = string;
export type Integer = number;
export type String_71 = string;

export interface INTEGRATIONS_CALL_TOOLInput {
  id?: String_53;
  connection?: Object_17 | Object_18 | Object_20 | Object_21 | Object_22;
  params: Object_23;
}
export interface Object_17 {
  type: String_54;
  url: String_55;
  token?: String_56;
}
export interface Object_18 {
  type: String_57;
  url: String_58;
  token?: String_59;
  headers?: Object_19;
}
export interface Object_19 {
  [k: string]: String_60;
}
export interface Object_20 {
  type: String_61;
  url: String_62;
  token?: String_63;
}
export interface Object_21 {
  type: String_64;
  tenant: String_65;
  token?: String_66;
}
export interface Object_22 {
  type: String_67;
  name: String_68;
  workspace?: String_69;
}
export interface Object_23 {
  _meta?: Object_24;
  name: String_71;
  arguments?: Object_25;
  [k: string]: unknown;
}
export interface Object_24 {
  progressToken?: String_70 | Integer;
  [k: string]: unknown;
}
export interface Object_25 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_CALL_TOOLOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_72 = string;
export type String_73 = string;
export type String_74 = string;
export type String_75 = string;
export type String_76 = string;
export type Null_7 = null;
export type String_77 = string;
export type Null_8 = null;
export type Boolean_6 = boolean;
export type Null_9 = null;
export type String_78 = "HTTP";
export type String_79 = string;
export type String_80 = string;
export type String_81 = "SSE";
export type String_82 = string;
export type String_83 = string;
export type String_84 = string;
export type String_85 = "Websocket";
export type String_86 = string;
export type String_87 = string;
export type String_88 = "Deco";
export type String_89 = string;
export type String_90 = string;
export type String_91 = "INNATE";
export type String_92 = string;
export type String_93 = string;
export type Null_10 = null;
export type String_94 = string;
export type Null_11 = null;
/**
 * The name of the tool
 */
export type String_95 = string;
/**
 * The description of the tool
 */
export type String_96 = string;
export type Array_8 = (Object_33 & Object_35)[];
export type Null_12 = null;
export type String_97 = string;

export interface INTEGRATIONS_CREATEInput {
  id?: String_72;
  name?: String_73;
  description?: String_74;
  icon?: String_75;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_76
      )
    | Null_7;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_77
      )
    | Null_8;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_6
      )
    | Null_9;
  connection?: Object_26 | Object_27 | Object_29 | Object_30 | Object_31;
  metadata?: Object_32 | Null_10;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_94
      )
    | Null_11;
  tools?: Array_8 | Null_12;
  clientIdFromApp?: String_97;
}
export interface Object_26 {
  type: String_78;
  url: String_79;
  token?: String_80;
}
export interface Object_27 {
  type: String_81;
  url: String_82;
  token?: String_83;
  headers?: Object_28;
}
export interface Object_28 {
  [k: string]: String_84;
}
export interface Object_29 {
  type: String_85;
  url: String_86;
  token?: String_87;
}
export interface Object_30 {
  type: String_88;
  tenant: String_89;
  token?: String_90;
}
export interface Object_31 {
  type: String_91;
  name: String_92;
  workspace?: String_93;
}
export interface Object_32 {
  [k: string]: unknown;
}
export interface Object_33 {
  name: String_95;
  inputSchema: Object_34;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_34 {
  [k: string]: unknown;
}
export interface Object_35 {
  description?: String_96;
  outputSchema?: Object_36;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_36 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_CREATEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_98 = string;

export interface INTEGRATIONS_DELETEInput {
  id: String_98;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_DELETEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_99 = string;

export interface INTEGRATIONS_GETInput {
  id: String_99;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_GETOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_100 = string;

export interface INTEGRATIONS_GET_API_KEYInput {
  integrationId: String_100;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_GET_API_KEYOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_101 = "Channel" | "View";
export type Boolean_7 = boolean;

export interface INTEGRATIONS_LISTInput {
  binder?: String_101;
  hideVirtual?: Boolean_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_102 = string;
export type String_103 = string;
export type String_104 = string;
export type String_105 = string;
export type String_106 = string;
export type Null_13 = null;
export type String_107 = string;
export type Null_14 = null;
export type String_108 = string;
export type Null_15 = null;
export type Boolean_8 = boolean;
export type Null_16 = null;
export type String_109 = "HTTP";
export type String_110 = string;
export type String_111 = string;
export type String_112 = "SSE";
export type String_113 = string;
export type String_114 = string;
export type String_115 = string;
export type String_116 = "Websocket";
export type String_117 = string;
export type String_118 = string;
export type String_119 = "Deco";
export type String_120 = string;
export type String_121 = string;
export type String_122 = "INNATE";
export type String_123 = string;
export type String_124 = string;
export type Null_17 = null;
export type String_125 = string;
export type Null_18 = null;
/**
 * The name of the tool
 */
export type String_126 = string;
/**
 * The description of the tool
 */
export type String_127 = string;
export type Array_10 = (Object_45 & Object_47)[];
export type Null_19 = null;
export type Array_9 = Object_37[];

export interface INTEGRATIONS_LISTOutput {
  items: Array_9;
}
export interface Object_37 {
  id: String_102;
  name: String_103;
  description?: String_104;
  icon?: String_105;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_106
      )
    | Null_13;
  appName?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_107
      )
    | Null_14;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_108
      )
    | Null_15;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_8
      )
    | Null_16;
  connection: Object_38 | Object_39 | Object_41 | Object_42 | Object_43;
  metadata?: Object_44 | Null_17;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_125
      )
    | Null_18;
  tools?: Array_10 | Null_19;
}
export interface Object_38 {
  type: String_109;
  url: String_110;
  token?: String_111;
}
export interface Object_39 {
  type: String_112;
  url: String_113;
  token?: String_114;
  headers?: Object_40;
}
export interface Object_40 {
  [k: string]: String_115;
}
export interface Object_41 {
  type: String_116;
  url: String_117;
  token?: String_118;
}
export interface Object_42 {
  type: String_119;
  tenant: String_120;
  token?: String_121;
}
export interface Object_43 {
  type: String_122;
  name: String_123;
  workspace?: String_124;
}
export interface Object_44 {
  [k: string]: unknown;
}
export interface Object_45 {
  name: String_126;
  inputSchema: Object_46;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_46 {
  [k: string]: unknown;
}
export interface Object_47 {
  description?: String_127;
  outputSchema?: Object_48;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_48 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_128 = string;
export type String_129 = string;
export type String_130 = string;
export type String_131 = string;
export type String_132 = string;
export type String_133 = string;
export type Null_20 = null;
export type String_134 = string;
export type Null_21 = null;
export type String_135 = string;
export type Null_22 = null;
export type Boolean_9 = boolean;
export type Null_23 = null;
export type String_136 = "HTTP";
export type String_137 = string;
export type String_138 = string;
export type String_139 = "SSE";
export type String_140 = string;
export type String_141 = string;
export type String_142 = string;
export type String_143 = "Websocket";
export type String_144 = string;
export type String_145 = string;
export type String_146 = "Deco";
export type String_147 = string;
export type String_148 = string;
export type String_149 = "INNATE";
export type String_150 = string;
export type String_151 = string;
export type Null_24 = null;
export type String_152 = string;
export type Null_25 = null;
/**
 * The name of the tool
 */
export type String_153 = string;
/**
 * The description of the tool
 */
export type String_154 = string;
export type Array_11 = (Object_57 & Object_59)[];
export type Null_26 = null;

export interface INTEGRATIONS_UPDATEInput {
  id: String_128;
  integration: Object_49;
}
export interface Object_49 {
  id: String_129;
  name: String_130;
  description?: String_131;
  icon?: String_132;
  access?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_133
      )
    | Null_20;
  appName?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_134
      )
    | Null_21;
  appId?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_135
      )
    | Null_22;
  verified?:
    | (
        | {
            [k: string]: unknown;
          }
        | Boolean_9
      )
    | Null_23;
  connection: Object_50 | Object_51 | Object_53 | Object_54 | Object_55;
  metadata?: Object_56 | Null_24;
  createdAt?:
    | (
        | {
            [k: string]: unknown;
          }
        | String_152
      )
    | Null_25;
  tools?: Array_11 | Null_26;
}
export interface Object_50 {
  type: String_136;
  url: String_137;
  token?: String_138;
}
export interface Object_51 {
  type: String_139;
  url: String_140;
  token?: String_141;
  headers?: Object_52;
}
export interface Object_52 {
  [k: string]: String_142;
}
export interface Object_53 {
  type: String_143;
  url: String_144;
  token?: String_145;
}
export interface Object_54 {
  type: String_146;
  tenant: String_147;
  token?: String_148;
}
export interface Object_55 {
  type: String_149;
  name: String_150;
  workspace?: String_151;
}
export interface Object_56 {
  [k: string]: unknown;
}
export interface Object_57 {
  name: String_153;
  inputSchema: Object_58;
}
/**
 * The JSON schema of the input of the tool
 */
export interface Object_58 {
  [k: string]: unknown;
}
export interface Object_59 {
  description?: String_154;
  outputSchema?: Object_60;
}
/**
 * The JSON schema of the output of the tool
 */
export interface Object_60 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface INTEGRATIONS_UPDATEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the entity to retrieve
 */
export type String_155 = string;

export interface COLLECTION_LLM_GETInput {
  id: String_155;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_156 = string;
/**
 * Human-readable title for the entity
 */
export type String_157 = string;
export type String_158 = string;
export type String_159 = string;
export type String_160 = string;
export type String_161 = string;
export type StringNull = String_162 | Null_27;
export type String_162 = string;
export type Null_27 = null;
export type StringNull_1 = String_163 | Null_28;
export type String_163 = string;
export type Null_28 = null;
export type String_164 = string;
export type Array_12 = String_164[];
export type Number_8 = number;
export type Number_9 = number;
export type Null_29 = null;
export type Number_10 = number;
export type Number_11 = number;
export type Null_30 = null;
export type String_165 =
  | "openai"
  | "anthropic"
  | "google"
  | "xai"
  | "deepseek"
  | "openai-compatible"
  | "openrouter";
export type Null_31 = null;
export type Null_32 = null;

export interface COLLECTION_LLM_GETOutput {
  /**
   * The retrieved item, or null if not found
   */
  item: Object_61 | Null_32;
}
export interface Object_61 {
  id: String_156;
  title: String_157;
  created_at: String_158;
  updated_at: String_159;
  created_by?: String_160;
  updated_by?: String_161;
  logo: StringNull;
  description: StringNull_1;
  capabilities: Array_12;
  limits: Object_62 | Null_29;
  costs: Object_63 | Null_30;
  provider: String_165 | Null_31;
}
export interface Object_62 {
  contextWindow: Number_8;
  maxOutputTokens: Number_9;
}
export interface Object_63 {
  input: Number_10;
  output: Number_11;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_166 = string;
export type Array_13 = String_166[];
export type String_167 =
  | "eq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "like"
  | "contains";
export type String_168 = "and" | "or" | "not";
export type Array_14 = Object_64[];
export type String_169 = string;
export type Array_16 = String_169[];
export type String_170 = "asc" | "desc";
export type String_171 = "first" | "last";
/**
 * Sort expressions
 */
export type Array_15 = Object_66[];
/**
 * Maximum number of items to return
 */
export type Integer_1 = number;
/**
 * Number of items to skip
 */
export type Integer_2 = number;

export interface COLLECTION_LLM_LISTInput {
  /**
   * Filter expression
   */
  where?: Object_64 | Object_65;
  orderBy?: Array_15;
  limit?: Integer_1;
  offset?: Integer_2;
}
export interface Object_64 {
  field: Array_13;
  operator: String_167;
  value?: unknown;
}
export interface Object_65 {
  operator: String_168;
  conditions: Array_14;
}
export interface Object_66 {
  field: Array_16;
  direction: String_170;
  nulls?: String_171;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the entity
 */
export type String_172 = string;
/**
 * Human-readable title for the entity
 */
export type String_173 = string;
export type String_174 = string;
export type String_175 = string;
export type String_176 = string;
export type String_177 = string;
export type StringNull_2 = String_178 | Null_33;
export type String_178 = string;
export type Null_33 = null;
export type StringNull_3 = String_179 | Null_34;
export type String_179 = string;
export type Null_34 = null;
export type String_180 = string;
export type Array_18 = String_180[];
export type Number_12 = number;
export type Number_13 = number;
export type Null_35 = null;
export type Number_14 = number;
export type Number_15 = number;
export type Null_36 = null;
export type String_181 =
  | "openai"
  | "anthropic"
  | "google"
  | "xai"
  | "deepseek"
  | "openai-compatible"
  | "openrouter";
export type Null_37 = null;
/**
 * Array of collection items
 */
export type Array_17 = Object_67[];
/**
 * Total number of matching items (if available)
 */
export type Integer_3 = number;
/**
 * Whether there are more items available
 */
export type Boolean_10 = boolean;

export interface COLLECTION_LLM_LISTOutput {
  items: Array_17;
  totalCount?: Integer_3;
  hasMore?: Boolean_10;
}
export interface Object_67 {
  id: String_172;
  title: String_173;
  created_at: String_174;
  updated_at: String_175;
  created_by?: String_176;
  updated_by?: String_177;
  logo: StringNull_2;
  description: StringNull_3;
  capabilities: Array_18;
  limits: Object_68 | Null_35;
  costs: Object_69 | Null_36;
  provider: String_181 | Null_37;
}
export interface Object_68 {
  contextWindow: Number_12;
  maxOutputTokens: Number_13;
}
export interface Object_69 {
  input: Number_14;
  output: Number_15;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Array of 2-5 model IDs to compare (e.g., ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'google/gemini-2.0-flash-exp'])
 *
 * @minItems 2
 * @maxItems 5
 */
export type Array_19 =
  | [String_182, String_182]
  | [String_182, String_182, String_182]
  | [String_182, String_182, String_182, String_182]
  | [String_182, String_182, String_182, String_182, String_182];
export type String_182 = string;
export type String_183 = "price" | "context_length" | "modality" | "moderation";
/**
 * Specific criteria to focus on in comparison. If not specified, all criteria are included.
 */
export type Array_20 = String_183[];

export interface COMPARE_MODELSInput {
  modelIds: Array_19;
  criteria?: Array_20;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_184 = string;
export type String_185 = string;
export type Array_21 = Object_70[];
/**
 * Automated recommendation based on comparison
 */
export type String_186 = string;

export interface COMPARE_MODELSOutput {
  comparison: Array_21;
  recommendation?: String_186;
}
export interface Object_70 {
  modelId: String_184;
  name: String_185;
  metrics: Object_71;
}
/**
 * Model metrics based on selected criteria
 */
export interface Object_71 {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_187 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_187;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_188 = string;
export type Array_22 = String_188[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_22;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_11 = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean_11;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput_1 {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_189 = string;
export type String_190 = string;
export type String_191 = string;
export type String_192 = string;
export type String_193 = string;
export type String_194 = string;
export type String_195 = string;
export type String_196 = string;
export type String_197 = string;
export type Array_24 = String_197[];
export type String_198 = string;
export type String_199 = "none" | "open" | "autoPin";
export type Array_23 = Object_72[];

export interface DECO_CHAT_VIEWS_LISTOutput_1 {
  views: Array_23;
}
export interface Object_72 {
  id?: String_189;
  name?: String_190;
  title: String_191;
  description?: String_192;
  icon: String_193;
  url?: String_194;
  mimeTypePattern?: String_195;
  resourceName?: String_196;
  tools?: Array_24;
  prompt?: String_198;
  installBehavior?: String_199;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_200 = string;
export type StringNull_4 = String_201 | Null_38;
export type String_201 = string;
export type Null_38 = null;
export type StringNull_5 = String_202 | Null_39;
export type String_202 = string;
export type Null_39 = null;
export type String_203 = string;

export interface GET_USEROutput {
  id: String_200;
  name: StringNull_4;
  avatar: StringNull_5;
  email: String_203;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the model
 */
export type String_204 = string;
/**
 * Maximum number of tokens to generate
 */
export type Number_16 = number;
/**
 * Temperature setting. The range depends on the provider and model
 */
export type Number_17 = number;
/**
 * Nucleus sampling parameter
 */
export type Number_18 = number;
/**
 * Only sample from the top K options for each subsequent token. Used to remove long tail low probability responses
 */
export type Number_19 = number;
/**
 * Presence penalty setting. It affects the likelihood of the model to repeat information that is already in the prompt
 */
export type Number_20 = number;
/**
 * Frequency penalty setting. It affects the likelihood of the model to repeatedly use the same words or phrases
 */
export type Number_21 = number;
/**
 * The seed (integer) to use for random sampling. If set and supported by the model, calls will generate deterministic results
 */
export type Number_22 = number;
export type String_205 = string;
/**
 * Stop sequences. If set, the model will stop generating text when one of the stop sequences is generated
 */
export type Array_25 = String_205[];
export type String_206 = "text";
export type String_207 = "json";
/**
 * Name of output that should be generated
 */
export type String_208 = string;
/**
 * Description of the output that should be generated
 */
export type String_209 = string;
/**
 * The tools that are available for the model
 */
export type Array_26 = unknown[];
/**
 * Include raw chunks in the stream. Only applicable for streaming calls
 */
export type Boolean_12 = boolean;
export type String_210 = string;

export interface LLM_DO_GENERATEInput {
  modelId: String_204;
  callOptions: Object_73;
}
export interface Object_73 {
  /**
   * A language mode prompt is a standardized prompt type (messages, system, etc.)
   */
  prompt?: {
    [k: string]: unknown;
  };
  maxOutputTokens?: Number_16;
  temperature?: Number_17;
  topP?: Number_18;
  topK?: Number_19;
  presencePenalty?: Number_20;
  frequencyPenalty?: Number_21;
  seed?: Number_22;
  stopSequences?: Array_25;
  /**
   * Response format. The output can either be text or JSON. Default is text
   */
  responseFormat?: Object_74 | Object_75;
  tools?: Array_26;
  /**
   * Specifies how the tool should be selected. Defaults to 'auto'
   */
  toolChoice?: {
    [k: string]: unknown;
  };
  includeRawChunks?: Boolean_12;
  /**
   * Abort signal for cancelling the operation
   */
  abortSignal?: {
    [k: string]: unknown;
  };
  headers?: Object_76;
  /**
   * Additional provider-specific options
   */
  providerOptions?: {
    [k: string]: unknown;
  };
}
export interface Object_74 {
  type: String_206;
}
export interface Object_75 {
  type: String_207;
  /**
   * JSON schema that the generated output should conform to
   */
  schema?: {
    [k: string]: unknown;
  };
  name?: String_208;
  description?: String_209;
}
/**
 * Additional HTTP headers to be sent with the request
 */
export interface Object_76 {
  [k: string]:
    | String_210
    | {
        [k: string]: unknown;
      };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Ordered content that the model has generated (text, tool-calls, reasoning, files, sources)
 */
export type Array_27 = unknown[];
/**
 * Reason why generation stopped
 */
export type String_211 =
  | "stop"
  | "length"
  | "content-filter"
  | "tool-calls"
  | "error"
  | "other"
  | "unknown";
export type Number_23 = number;
export type Number_24 = number;
export type Number_25 = number;
export type Number_26 = number;
/**
 * ID for the generated response
 */
export type String_212 = string;
/**
 * Timestamp for the start of the generated response
 */
export type String_213 = string;
/**
 * The ID of the response model that was used
 */
export type String_214 = string;
export type String_215 = string;
/**
 * Warnings for the call, e.g. unsupported settings
 */
export type Array_28 = unknown[];

export interface LLM_DO_GENERATEOutput {
  content: Array_27;
  finishReason: String_211;
  usage: Object_77;
  /**
   * Additional provider-specific metadata
   */
  providerMetadata?: {
    [k: string]: unknown;
  };
  request?: Object_78;
  response?: Object_79;
  warnings: Array_28;
}
/**
 * Usage information for the language model call
 */
export interface Object_77 {
  inputTokens?: Number_23;
  outputTokens?: Number_24;
  totalTokens?: Number_25;
  reasoningTokens?: Number_26;
  [k: string]: unknown;
}
/**
 * Optional request information for telemetry and debugging
 */
export interface Object_78 {
  /**
   * Request HTTP body sent to the provider API
   */
  body?: {
    [k: string]: unknown;
  };
}
/**
 * Optional response information for telemetry and debugging
 */
export interface Object_79 {
  id?: String_212;
  timestamp?: String_213;
  modelId?: String_214;
  headers?: Object_80;
  /**
   * Response HTTP body
   */
  body?: {
    [k: string]: unknown;
  };
}
/**
 * Response headers
 */
export interface Object_80 {
  [k: string]: String_215;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the model
 */
export type String_216 = string;
/**
 * Maximum number of tokens to generate
 */
export type Number_27 = number;
/**
 * Temperature setting. The range depends on the provider and model
 */
export type Number_28 = number;
/**
 * Nucleus sampling parameter
 */
export type Number_29 = number;
/**
 * Only sample from the top K options for each subsequent token. Used to remove long tail low probability responses
 */
export type Number_30 = number;
/**
 * Presence penalty setting. It affects the likelihood of the model to repeat information that is already in the prompt
 */
export type Number_31 = number;
/**
 * Frequency penalty setting. It affects the likelihood of the model to repeatedly use the same words or phrases
 */
export type Number_32 = number;
/**
 * The seed (integer) to use for random sampling. If set and supported by the model, calls will generate deterministic results
 */
export type Number_33 = number;
export type String_217 = string;
/**
 * Stop sequences. If set, the model will stop generating text when one of the stop sequences is generated
 */
export type Array_29 = String_217[];
export type String_218 = "text";
export type String_219 = "json";
/**
 * Name of output that should be generated
 */
export type String_220 = string;
/**
 * Description of the output that should be generated
 */
export type String_221 = string;
/**
 * The tools that are available for the model
 */
export type Array_30 = unknown[];
/**
 * Include raw chunks in the stream. Only applicable for streaming calls
 */
export type Boolean_13 = boolean;
export type String_222 = string;

export interface LLM_DO_STREAMInput {
  modelId: String_216;
  callOptions: Object_81;
}
export interface Object_81 {
  /**
   * A language mode prompt is a standardized prompt type (messages, system, etc.)
   */
  prompt?: {
    [k: string]: unknown;
  };
  maxOutputTokens?: Number_27;
  temperature?: Number_28;
  topP?: Number_29;
  topK?: Number_30;
  presencePenalty?: Number_31;
  frequencyPenalty?: Number_32;
  seed?: Number_33;
  stopSequences?: Array_29;
  /**
   * Response format. The output can either be text or JSON. Default is text
   */
  responseFormat?: Object_82 | Object_83;
  tools?: Array_30;
  /**
   * Specifies how the tool should be selected. Defaults to 'auto'
   */
  toolChoice?: {
    [k: string]: unknown;
  };
  includeRawChunks?: Boolean_13;
  /**
   * Abort signal for cancelling the operation
   */
  abortSignal?: {
    [k: string]: unknown;
  };
  headers?: Object_84;
  /**
   * Additional provider-specific options
   */
  providerOptions?: {
    [k: string]: unknown;
  };
}
export interface Object_82 {
  type: String_218;
}
export interface Object_83 {
  type: String_219;
  /**
   * JSON schema that the generated output should conform to
   */
  schema?: {
    [k: string]: unknown;
  };
  name?: String_220;
  description?: String_221;
}
/**
 * Additional HTTP headers to be sent with the request
 */
export interface Object_84 {
  [k: string]:
    | String_222
    | {
        [k: string]: unknown;
      };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LLM_DO_STREAMOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the model
 */
export type String_223 = string;

export interface LLM_METADATAInput {
  modelId: String_223;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_224 = string;
export type Array_31 = String_224[];

export interface LLM_METADATAOutput {
  supportedUrls: Object_85;
}
/**
 * Supported URL patterns by media type for the provider
 */
export interface Object_85 {
  [k: string]: Array_31;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Description of your task (e.g., 'generate Python code', 'write creative stories', 'analyze large documents', 'answer questions with images')
 */
export type String_225 = string;
/**
 * Maximum budget per 1M tokens in dollars (e.g., 5 for $5)
 */
export type Number_34 = number;
/**
 * Minimum required context length in tokens (e.g., 100000 for 100k)
 */
export type Number_35 = number;
/**
 * Required model capability: 'text->text' for text-only, 'text+image->text' for vision, 'text->image' for image generation
 */
export type String_226 = "text->text" | "text+image->text" | "text->image";
/**
 * What to prioritize: 'cost' for cheapest models, 'quality' for best performance, 'speed' for fastest models
 */
export type String_227 = "cost" | "quality" | "speed";

export interface RECOMMEND_MODELInput {
  taskDescription: String_225;
  requirements?: Object_86;
}
/**
 * Optional requirements and constraints for model selection
 */
export interface Object_86 {
  maxCostPer1MTokens?: Number_34;
  minContextLength?: Number_35;
  requiredModality?: String_226;
  prioritize?: String_227;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Model identifier to use for API calls
 */
export type String_228 = string;
/**
 * Human-readable model name
 */
export type String_229 = string;
/**
 * Explanation of why this model is recommended for your task
 */
export type String_230 = string;
/**
 * Recommendation score (higher is better, 0-100 scale)
 */
export type Number_36 = number;
/**
 * Cost per 1M prompt tokens
 */
export type String_231 = string;
/**
 * Cost per 1M completion tokens
 */
export type String_232 = string;
/**
 * Maximum context length in tokens
 */
export type Number_37 = number;
/**
 * Model capability
 */
export type String_233 = string;
/**
 * Top recommended models ordered by score
 */
export type Array_32 = Object_87[];

export interface RECOMMEND_MODELOutput {
  recommendations: Array_32;
}
export interface Object_87 {
  modelId: String_228;
  name: String_229;
  reasoning: String_230;
  score: Number_36;
  pricing: Object_88;
  contextLength: Number_37;
  modality: String_233;
}
export interface Object_88 {
  promptPrice: String_231;
  completionPrice: String_232;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  INTEGRATIONS: z.object({
    value: z.string(),
    __type: z.literal("@deco/integrations").default("@deco/integrations"),
  }),
  DATABASE: z.object({
    value: z.string(),
    __type: z.literal("@deco/database").default("@deco/database"),
  }),
  OPENROUTER: z.object({
    value: z.string(),
    __type: z.literal("@deco/openrouter").default("@deco/openrouter"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  INTEGRATIONS: Mcp<{
    /**
     * Get the schema for a marketplace app
     */
    DECO_GET_APP_SCHEMA: (
      input: DECO_GET_APP_SCHEMAInput,
    ) => Promise<DECO_GET_APP_SCHEMAOutput>;
    /**
     * Install an integration. To know the available ids, use the DECO_INTEGRATIONS_SEARCH tool. Also, after installing, enable the integration using the INTEGRATION_ENABLE tool.
     */
    DECO_INTEGRATION_INSTALL: (
      input: DECO_INTEGRATION_INSTALLInput,
    ) => Promise<DECO_INTEGRATION_INSTALLOutput>;
    /**
     * Start the OAuth flow for an integration
     */
    DECO_INTEGRATION_OAUTH_START: (
      input: DECO_INTEGRATION_OAUTH_STARTInput,
    ) => Promise<DECO_INTEGRATION_OAUTH_STARTOutput>;
    /**
     * Search for integrations in both marketplace and installed.
     * If no query is provided, it will return all installed integrations. For better results, try searching for the service name, i.e. GoogleSheets, GoogleCalendar, Notion, etc.
     * It's always handy to search for installed integrations with no query, since all integrations will be returned. Also, some integrations are handy agents that may help you with common tasks.
     */
    DECO_INTEGRATIONS_SEARCH: (
      input: DECO_INTEGRATIONS_SEARCHInput,
    ) => Promise<DECO_INTEGRATIONS_SEARCHOutput>;
    /**
     * Call a tool from an integration. If you have the integration ID (from INTEGRATIONS_LIST or INTEGRATIONS_GET), prefer using 'id' over 'connection'. The ID ensures you're calling the correct configured integration. Use 'connection' only when you need to call a tool from a new or unconfigured integration.
     */
    INTEGRATIONS_CALL_TOOL: (
      input: INTEGRATIONS_CALL_TOOLInput,
    ) => Promise<INTEGRATIONS_CALL_TOOLOutput>;
    /**
     * Create a new integration
     */
    INTEGRATIONS_CREATE: (
      input: INTEGRATIONS_CREATEInput,
    ) => Promise<INTEGRATIONS_CREATEOutput>;
    /**
     * Delete an integration by id
     */
    INTEGRATIONS_DELETE: (
      input: INTEGRATIONS_DELETEInput,
    ) => Promise<INTEGRATIONS_DELETEOutput>;
    /**
     * Get an integration by id with tools
     */
    INTEGRATIONS_GET: (
      input: INTEGRATIONS_GETInput,
    ) => Promise<INTEGRATIONS_GETOutput>;
    /**
     * Get the API key for an integration
     */
    INTEGRATIONS_GET_API_KEY: (
      input: INTEGRATIONS_GET_API_KEYInput,
    ) => Promise<INTEGRATIONS_GET_API_KEYOutput>;
    /**
     * List all integrations with their tools
     */
    INTEGRATIONS_LIST: (
      input: INTEGRATIONS_LISTInput,
    ) => Promise<INTEGRATIONS_LISTOutput>;
    /**
     * Update an existing integration
     */
    INTEGRATIONS_UPDATE: (
      input: INTEGRATIONS_UPDATEInput,
    ) => Promise<INTEGRATIONS_UPDATEOutput>;
  }>;
  DATABASE: Mcp<{
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_GET_META: (
      input: DATABASES_GET_METAInput,
    ) => Promise<DATABASES_GET_METAOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RECOVERY: (
      input: DATABASES_RECOVERYInput,
    ) => Promise<DATABASES_RECOVERYOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RUN_SQL: (
      input: DATABASES_RUN_SQLInput,
    ) => Promise<DATABASES_RUN_SQLOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
  }>;
  OPENROUTER: Mcp<{
    /**
     * Get detailed information about a specific OpenRouter model including pricing, capabilities, context length, and provider information.
     */
    COLLECTION_LLM_GET: (
      input: COLLECTION_LLM_GETInput,
    ) => Promise<COLLECTION_LLM_GETOutput>;
    /**
     * List all available models from OpenRouter with filtering and pagination support. Returns comprehensive information about each model including capabilities, pricing, and limits.
     */
    COLLECTION_LLM_LIST: (
      input: COLLECTION_LLM_LISTInput,
    ) => Promise<COLLECTION_LLM_LISTOutput>;
    /**
     * Compare multiple OpenRouter models side-by-side to help choose the best model for a specific use case. Compares pricing (prompt and completion costs), context length, capabilities (modality), and performance characteristics. Returns a detailed comparison table and an automatic recommendation. Useful when deciding between multiple models for a task.
     */
    COMPARE_MODELS: (
      input: COMPARE_MODELSInput,
    ) => Promise<COMPARE_MODELSOutput>;
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
    /**
     * Generate a complete language model response using OpenRouter (non-streaming). Returns the full response with usage statistics and cost information.
     */
    LLM_DO_GENERATE: (
      input: LLM_DO_GENERATEInput,
    ) => Promise<LLM_DO_GENERATEOutput>;
    /**
     * Stream a language model response in real-time using OpenRouter. Returns a streaming response for interactive chat experiences.
     */
    LLM_DO_STREAM: (input: LLM_DO_STREAMInput) => Promise<LLM_DO_STREAMOutput>;
    /**
     * Get metadata about a specific model's capabilities including supported URL patterns for different media types (images, files, etc.).
     */
    LLM_METADATA: (input: LLM_METADATAInput) => Promise<LLM_METADATAOutput>;
    /**
     * Get intelligent model recommendations based on your task description and requirements. The system analyzes your task (e.g., 'code generation', 'creative writing', 'data analysis') and suggests the most suitable models considering cost, quality, context length, and capabilities. Each recommendation includes detailed reasoning explaining why the model is suitable. Perfect for discovering the right model when you're not sure which to use.
     */
    RECOMMEND_MODEL: (
      input: RECOMMEND_MODELInput,
    ) => Promise<RECOMMEND_MODELOutput>;
  }>;
}

export const Scopes = {
  DATABASE: {
    DATABASES_GET_META: "DATABASE::DATABASES_GET_META",
    DATABASES_RECOVERY: "DATABASE::DATABASES_RECOVERY",
    DATABASES_RUN_SQL: "DATABASE::DATABASES_RUN_SQL",
    DECO_CHAT_VIEWS_LIST: "DATABASE::DECO_CHAT_VIEWS_LIST",
  },
  INTEGRATIONS: {
    DECO_GET_APP_SCHEMA: "INTEGRATIONS::DECO_GET_APP_SCHEMA",
    DECO_INTEGRATION_INSTALL: "INTEGRATIONS::DECO_INTEGRATION_INSTALL",
    DECO_INTEGRATION_OAUTH_START: "INTEGRATIONS::DECO_INTEGRATION_OAUTH_START",
    DECO_INTEGRATIONS_SEARCH: "INTEGRATIONS::DECO_INTEGRATIONS_SEARCH",
    INTEGRATIONS_CALL_TOOL: "INTEGRATIONS::INTEGRATIONS_CALL_TOOL",
    INTEGRATIONS_CREATE: "INTEGRATIONS::INTEGRATIONS_CREATE",
    INTEGRATIONS_DELETE: "INTEGRATIONS::INTEGRATIONS_DELETE",
    INTEGRATIONS_GET: "INTEGRATIONS::INTEGRATIONS_GET",
    INTEGRATIONS_GET_API_KEY: "INTEGRATIONS::INTEGRATIONS_GET_API_KEY",
    INTEGRATIONS_LIST: "INTEGRATIONS::INTEGRATIONS_LIST",
    INTEGRATIONS_UPDATE: "INTEGRATIONS::INTEGRATIONS_UPDATE",
  },
  OPENROUTER: {
    COLLECTION_LLM_GET: "OPENROUTER::COLLECTION_LLM_GET",
    COLLECTION_LLM_LIST: "OPENROUTER::COLLECTION_LLM_LIST",
    COMPARE_MODELS: "OPENROUTER::COMPARE_MODELS",
    DECO_CHAT_OAUTH_START: "OPENROUTER::DECO_CHAT_OAUTH_START",
    DECO_CHAT_STATE_VALIDATION: "OPENROUTER::DECO_CHAT_STATE_VALIDATION",
    DECO_CHAT_VIEWS_LIST: "OPENROUTER::DECO_CHAT_VIEWS_LIST",
    GET_USER: "OPENROUTER::GET_USER",
    LLM_DO_GENERATE: "OPENROUTER::LLM_DO_GENERATE",
    LLM_DO_STREAM: "OPENROUTER::LLM_DO_STREAM",
    LLM_METADATA: "OPENROUTER::LLM_METADATA",
    RECOMMEND_MODEL: "OPENROUTER::RECOMMEND_MODEL",
  },
};
