// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATABASES_GET_METAInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Number = number;

export interface DATABASES_GET_METAOutput {
  bytes?: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date to recover to
 */
export type String = string;

export interface DATABASES_RECOVERYInput {
  date: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DATABASES_RECOVERYOutput {
  success: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The SQL query to run
 */
export type String_1 = string;
/**
 * The parameters to pass to the SQL query
 */
export type Array = unknown[];

export interface DATABASES_RUN_SQLInput {
  sql: String_1;
  params?: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_1 = boolean;
export type Number_1 = number;
export type Number_2 = number;
export type Number_3 = number;
export type Number_4 = number;
export type Number_5 = number;
export type Boolean_2 = boolean;
export type String_2 = "WNAM" | "ENAM" | "WEUR" | "EEUR" | "APAC" | "OC";
export type Number_6 = number;
export type Number_7 = number;
export type Array_2 = unknown[];
export type Boolean_3 = boolean;
export type Array_1 = Object[];

export interface DATABASES_RUN_SQLOutput {
  result: Array_1;
}
export interface Object {
  meta?: Object_1;
  results?: Array_2;
  success?: Boolean_3;
}
export interface Object_1 {
  changed_db?: Boolean_1;
  changes?: Number_1;
  duration?: Number_2;
  last_row_id?: Number_3;
  rows_read?: Number_4;
  rows_written?: Number_5;
  served_by_primary?: Boolean_2;
  served_by_region?: String_2;
  size_after?: Number_6;
  timings?: Object_2;
}
export interface Object_2 {
  sql_duration_ms?: Number_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_3 = string;
export type String_4 = string;
export type String_5 = string;
export type String_6 = string;
export type String_7 = string;
export type String_8 = string;
export type String_9 = string;
export type String_10 = string;
export type String_11 = string;
export type Array_4 = String_11[];
export type String_12 = string;
export type String_13 = "none" | "open" | "autoPin";
export type Array_3 = Object_3[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_3;
}
export interface Object_3 {
  id?: String_3;
  name?: String_4;
  title: String_5;
  description?: String_6;
  icon: String_7;
  url?: String_8;
  mimeTypePattern?: String_9;
  resourceName?: String_10;
  tools?: Array_4;
  prompt?: String_12;
  installBehavior?: String_13;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_14 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_14;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_15 = string;
export type Array_5 = String_15[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_4 = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput_1 {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_16 = string;
export type String_17 = string;
export type String_18 = string;
export type String_19 = string;
export type String_20 = string;
export type String_21 = string;
export type String_22 = string;
export type String_23 = string;
export type String_24 = string;
export type Array_7 = String_24[];
export type String_25 = string;
export type String_26 = "none" | "open" | "autoPin";
export type Array_6 = Object_4[];

export interface DECO_CHAT_VIEWS_LISTOutput_1 {
  views: Array_6;
}
export interface Object_4 {
  id?: String_16;
  name?: String_17;
  title: String_18;
  description?: String_19;
  icon: String_20;
  url?: String_21;
  mimeTypePattern?: String_22;
  resourceName?: String_23;
  tools?: Array_7;
  prompt?: String_25;
  installBehavior?: String_26;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USEROutput {}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  DATABASE: z.object({
    value: z.string(),
    __type: z.literal("@deco/database").default("@deco/database"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  DATABASE: Mcp<{
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_GET_META: (
      input: DATABASES_GET_METAInput,
    ) => Promise<DATABASES_GET_METAOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RECOVERY: (
      input: DATABASES_RECOVERYInput,
    ) => Promise<DATABASES_RECOVERYOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RUN_SQL: (
      input: DATABASES_RUN_SQLInput,
    ) => Promise<DATABASES_RUN_SQLOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
  }>;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
  }>;
}

export const Scopes = {
  DATABASE: {
    DATABASES_GET_META: "DATABASE::DATABASES_GET_META",
    DATABASES_RECOVERY: "DATABASE::DATABASES_RECOVERY",
    DATABASES_RUN_SQL: "DATABASE::DATABASES_RUN_SQL",
    DECO_CHAT_VIEWS_LIST: "DATABASE::DECO_CHAT_VIEWS_LIST",
  },
};
