import { createPrivateTool } from "@decocms/runtime/tools";
import { z } from "zod";
import { dataApi } from "../lib/yt-client.ts";
import { fetchTimedTextTranscript } from "../lib/transcript-fallback.ts";
import type { Env } from "../types/env.ts";

interface CaptionListResponse {
  items?: Array<{
    id: string;
    snippet?: {
      language?: string;
      name?: string;
      trackKind?: string;
      isAutoSynced?: boolean;
      isDraft?: boolean;
      lastUpdated?: string;
    };
  }>;
}

export const createListMyCaptionsTool = (env: Env) =>
  createPrivateTool({
    id: "YOUTUBE_ADMIN_LIST_MY_CAPTIONS",
    description:
      'List caption tracks of one of the channel\'s videos. trackKind "ASR" = YouTube auto-generated captions, "standard" = uploaded/owned tracks.',
    inputSchema: z.object({
      videoId: z.string().describe("Id of a video owned by the channel"),
    }),
    outputSchema: z.object({
      videoId: z.string(),
      tracks: z.array(
        z.object({
          captionId: z.string(),
          language: z.string().optional(),
          name: z.string().optional(),
          trackKind: z.string().optional(),
          isAutoSynced: z.boolean().optional(),
          isDraft: z.boolean().optional(),
          lastUpdated: z.string().optional(),
        }),
      ),
    }),
    execute: async ({ context }) => {
      const data = await dataApi<CaptionListResponse>(env, "/captions", {
        params: { part: "snippet", videoId: context.videoId },
      });
      return {
        videoId: context.videoId,
        tracks: (data.items ?? []).map((item) => ({
          captionId: item.id,
          language: item.snippet?.language,
          name: item.snippet?.name,
          trackKind: item.snippet?.trackKind,
          isAutoSynced: item.snippet?.isAutoSynced,
          isDraft: item.snippet?.isDraft,
          lastUpdated: item.snippet?.lastUpdated,
        })),
      };
    },
  });

export const createGetMyVideoTranscriptTool = (env: Env) =>
  createPrivateTool({
    id: "YOUTUBE_ADMIN_GET_MY_VIDEO_TRANSCRIPT",
    description:
      "Get the transcript of one of the channel's videos. Owned (standard) tracks are downloaded via the official captions API (200 quota units). Auto-generated (ASR) tracks are NOT downloadable via the official API — those are fetched keyless via YouTube's timedtext endpoint, which works for public/unlisted videos only (temporarily set a private video to unlisted if needed).",
    inputSchema: z.object({
      videoId: z.string().describe("Id of a video owned by the channel"),
      language: z
        .string()
        .optional()
        .describe('Preferred language code (e.g. "en", "pt")'),
      format: z
        .enum(["text", "srt", "vtt"])
        .default("text")
        .describe("Output format (default plain text)"),
    }),
    outputSchema: z.object({
      videoId: z.string(),
      source: z.enum(["captions_api", "timedtext"]),
      language: z.string().optional(),
      isAutoGenerated: z.boolean(),
      format: z.string(),
      transcript: z.string(),
    }),
    execute: async ({ context }) => {
      const data = await dataApi<CaptionListResponse>(env, "/captions", {
        params: { part: "snippet", videoId: context.videoId },
      });
      const tracks = data.items ?? [];

      const wanted = context.language?.toLowerCase();
      const byLanguage = (kind: string) =>
        tracks.find(
          (track) =>
            track.snippet?.trackKind === kind &&
            (!wanted ||
              (track.snippet?.language ?? "").toLowerCase().startsWith(wanted)),
        );
      const standard = byLanguage("standard");

      if (standard) {
        // Official download only works for tracks the channel owns.
        const tfmt = context.format === "text" ? "srt" : context.format;
        const raw = await dataApi<string>(
          env,
          `/captions/${encodeURIComponent(standard.id)}`,
          { params: { tfmt } },
        );
        return {
          videoId: context.videoId,
          source: "captions_api" as const,
          language: standard.snippet?.language,
          isAutoGenerated: false,
          format: context.format,
          transcript: context.format === "text" ? srtToPlainText(raw) : raw,
        };
      }

      // ASR fallback: keyless timedtext (same path youtube-search uses).
      const result = await fetchTimedTextTranscript(
        context.videoId,
        context.language,
        context.format,
      );
      return {
        videoId: context.videoId,
        source: "timedtext" as const,
        language: result.language,
        isAutoGenerated: result.isAutoGenerated,
        format: context.format,
        transcript: result.transcript,
      };
    },
  });

export const createUploadCaptionTool = (env: Env) =>
  createPrivateTool({
    id: "YOUTUBE_ADMIN_UPLOAD_CAPTION",
    description:
      "Upload a new caption track (SRT or VTT) to one of the channel's videos. Quota: 400 units. The track becomes immediately available for the video.",
    inputSchema: z.object({
      videoId: z.string().describe("Id of a video owned by the channel"),
      language: z
        .string()
        .describe('BCP-47 language code (e.g. "pt", "en", "es")'),
      name: z
        .string()
        .optional()
        .describe('Display name for the track (e.g. "Português")'),
      content: z
        .string()
        .describe("Full SRT or VTT caption content as a string"),
      format: z
        .enum(["srt", "vtt"])
        .default("srt")
        .describe("Format of the content string"),
      isDraft: z
        .boolean()
        .default(false)
        .describe("Upload as draft (not visible to viewers yet)"),
    }),
    outputSchema: z.object({
      captionId: z.string(),
      videoId: z.string(),
      language: z.string(),
      name: z.string().optional(),
      trackKind: z.string().optional(),
      isDraft: z.boolean().optional(),
    }),
    execute: async ({ context }) => {
      const { getAccessToken } = await import("../lib/auth.ts");
      const token = getAccessToken(env);

      const snippet = {
        videoId: context.videoId,
        language: context.language,
        name: context.name ?? context.language,
        isDraft: context.isDraft,
      };

      const boundary = `caption_boundary_${Date.now()}`;
      const body = [
        `--${boundary}`,
        "Content-Type: application/json; charset=UTF-8",
        "",
        JSON.stringify({ snippet }),
        `--${boundary}`,
        `Content-Type: text/${context.format === "vtt" ? "vtt" : "plain"}`,
        "",
        context.content,
        `--${boundary}--`,
      ].join("\r\n");

      const response = await fetch(
        `https://www.googleapis.com/upload/youtube/v3/captions?uploadType=multipart&part=snippet`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": `multipart/related; boundary=${boundary}`,
          },
          body,
        },
      );

      if (!response.ok) {
        const text = await response.text();
        throw new Error(
          `Caption upload failed (${response.status}): ${text.slice(0, 500)}`,
        );
      }

      const result = (await response.json()) as {
        id: string;
        snippet?: {
          language?: string;
          name?: string;
          trackKind?: string;
          isDraft?: boolean;
        };
      };

      return {
        captionId: result.id,
        videoId: context.videoId,
        language: result.snippet?.language ?? context.language,
        name: result.snippet?.name,
        trackKind: result.snippet?.trackKind,
        isDraft: result.snippet?.isDraft,
      };
    },
  });

export const createUpdateCaptionTool = (env: Env) =>
  createPrivateTool({
    id: "YOUTUBE_ADMIN_UPDATE_CAPTION",
    description:
      "Replace the content of an existing caption track. Quota: 450 units.",
    inputSchema: z.object({
      captionId: z.string(),
      content: z.string().describe("New full SRT or VTT content"),
      format: z.enum(["srt", "vtt"]).default("srt"),
      isDraft: z.boolean().optional(),
    }),
    outputSchema: z.object({
      captionId: z.string(),
      language: z.string().optional(),
      name: z.string().optional(),
      isDraft: z.boolean().optional(),
    }),
    execute: async ({ context }) => {
      const { getAccessToken } = await import("../lib/auth.ts");
      const token = getAccessToken(env);

      const snippet = {
        id: context.captionId,
        isDraft: context.isDraft,
      };

      const boundary = `caption_boundary_${Date.now()}`;
      const body = [
        `--${boundary}`,
        "Content-Type: application/json; charset=UTF-8",
        "",
        JSON.stringify({ snippet }),
        `--${boundary}`,
        `Content-Type: text/${context.format === "vtt" ? "vtt" : "plain"}`,
        "",
        context.content,
        `--${boundary}--`,
      ].join("\r\n");

      const response = await fetch(
        `https://www.googleapis.com/upload/youtube/v3/captions?uploadType=multipart&part=snippet`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": `multipart/related; boundary=${boundary}`,
          },
          body,
        },
      );

      if (!response.ok) {
        const text = await response.text();
        throw new Error(
          `Caption update failed (${response.status}): ${text.slice(0, 500)}`,
        );
      }

      const result = (await response.json()) as {
        id: string;
        snippet?: {
          language?: string;
          name?: string;
          isDraft?: boolean;
        };
      };

      return {
        captionId: result.id,
        language: result.snippet?.language,
        name: result.snippet?.name,
        isDraft: result.snippet?.isDraft,
      };
    },
  });

export const createDeleteCaptionTool = (env: Env) =>
  createPrivateTool({
    id: "YOUTUBE_ADMIN_DELETE_CAPTION",
    description: "Delete a caption track from a video.",
    inputSchema: z.object({
      captionId: z.string(),
    }),
    outputSchema: z.object({
      captionId: z.string(),
      deleted: z.boolean(),
    }),
    execute: async ({ context }) => {
      await dataApi(env, "/captions", {
        method: "DELETE",
        params: { id: context.captionId },
      });
      return { captionId: context.captionId, deleted: true };
    },
  });

/** Strips SRT indexes/timestamps, leaving one caption line per row. */
function srtToPlainText(srt: string): string {
  return srt
    .split(/\r?\n/)
    .filter(
      (line) =>
        line.trim().length > 0 &&
        !/^\d+$/.test(line.trim()) &&
        !line.includes("-->"),
    )
    .join("\n");
}
