export const WELL_KNOWN_MODEL_IDS = [
  "google/gemini-2.5-pro",
  "google/gemini-2.5-flash-lite-preview-06-17",
  "google/gemini-2.5-pro-preview",
  "google/gemini-2.5-pro-preview-03-25",
  "anthropic/claude-3.7-sonnet-thinking",
  "anthropic/claude-3.7-sonnet",
  "anthropic/claude-3.5-sonnet",
  "anthropic/claude-3.5-haiku",
  "openai/o3-mini-high",
  "openai/gpt-4.1",
  "openai/gpt-4.1-mini",
  "openai/gpt-4.1-nano",
  "x-ai/grok-3-beta",
  "x-ai/grok-4",
  "openai/gpt-oss-120b",
  "openai/gpt-oss-20b",
];
