// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;

export interface FS_DELETEInput {
  path: String;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_DELETEOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The root directory to list files from
 */
export type String_1 = string;

export interface FS_LISTInput {
  prefix: String_1;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Array = unknown[];

export interface FS_LISTOutput {
  items: Array;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_2 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number = number;

export interface FS_READInput {
  path: String_2;
  expiresIn?: Number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to read the file from
 */
export type String_3 = string;

export interface FS_READOutput {
  url: String_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_4 = string;

export interface FS_READ_METADATAInput {
  path: String_4;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FS_READ_METADATAOutput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_5 = string;
/**
 * Seconds until URL expires (default: 60)
 */
export type Number_1 = number;
/**
 * Content-Type for the file. This is required.
 */
export type String_6 = string;

export interface FS_WRITEInput {
  path: String_5;
  expiresIn?: Number_1;
  contentType: String_6;
  metadata?: Object;
}
/**
 * Metadata to be added to the file
 */
export interface Object {
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL to upload the file to
 */
export type String_7 = string;

export interface FS_WRITEOutput {
  url: String_7;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_8 = string;
export type Number_2 = number;
export type Array_1 = Object_1[];

export interface CONTRACT_AUTHORIZEInput {
  clauses: Array_1;
}
export interface Object_1 {
  clauseId: String_8;
  amount: Number_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_9 = string;
export type String_10 = string;
export type Number_3 = number;

export interface CONTRACT_AUTHORIZEOutput {
  transactionId: String_9;
  totalAmount: String_10;
  timestamp: Number_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CONTRACT_GETInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_11 = string;
export type String_12 = string;
export type String_13 = string;
export type StringNumber = String_14 | Number_4;
export type String_14 = string;
export type Number_4 = number;
export type String_15 = string;
export type String_16 = string;
export type Array_3 = String_16[];
export type Array_2 = Object_3[];

export interface CONTRACT_GETOutput {
  appName?: String_11;
  contract: Object_2;
}
export interface Object_2 {
  body?: String_12;
  clauses?: Array_2;
}
export interface Object_3 {
  id: String_13;
  price: StringNumber;
  description?: String_15;
  usedByTools?: Array_3;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_17 = string;
export type String_18 = string;
export type Number_5 = number;
export type Array_4 = Object_4[];
export type Number_6 = number;
export type String_19 = string;

export interface CONTRACT_SETTLEInput {
  transactionId: String_17;
  clauses?: Array_4;
  amount?: Number_6;
  vendorId: String_19;
}
export interface Object_4 {
  clauseId: String_18;
  amount: Number_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_20 = string;

export interface CONTRACT_SETTLEOutput {
  transactionId: String_20;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_21 = string;

export interface DECO_CHAT_OAUTH_STARTInput {
  returnUrl: String_21;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_22 = string;
export type Array_5 = String_22[];

export interface DECO_CHAT_OAUTH_STARTOutput {
  stateSchema?: unknown;
  scopes?: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_23 = string;

export interface DECO_CHAT_OAUTH_STARTInput_1 {
  returnUrl: String_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_24 = string;
export type Array_6 = String_24[];

export interface DECO_CHAT_OAUTH_STARTOutput_1 {
  stateSchema?: unknown;
  scopes?: Array_6;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_STATE_VALIDATIONInput {
  state?: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean = boolean;

export interface DECO_CHAT_STATE_VALIDATIONOutput {
  valid: Boolean;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_25 = string;
export type String_26 = string;
export type String_27 = string;
export type String_28 = string;
export type String_29 = string;
export type String_30 = string;
export type String_31 = string;
export type String_32 = string;
export type String_33 = string;
export type Array_8 = String_33[];
export type String_34 = string;
export type String_35 = "none" | "open" | "autoPin";
export type Array_7 = Object_5[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_7;
}
export interface Object_5 {
  id?: String_25;
  name?: String_26;
  title: String_27;
  description?: String_28;
  icon: String_29;
  url?: String_30;
  mimeTypePattern?: String_31;
  resourceName?: String_32;
  tools?: Array_8;
  prompt?: String_34;
  installBehavior?: String_35;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The text prompt describing the video to generate
 */
export type String_36 = string;
/**
 * URL of an existing image to use as base (image-to-video generation)
 */
export type StringNull = String_37 | Null;
export type String_37 = string;
export type Null = null;
/**
 * Up to 3 reference images to guide generation
 *
 * @maxItems 3
 */
export type Array_9 =
  | []
  | [Object_6]
  | [Object_6, Object_6]
  | [Object_6, Object_6, Object_6];
export type String_38 = string;
export type String_39 = "asset" | "style";
/**
 * URL of the first frame image
 */
export type String_40 = string;
/**
 * URL of the last frame image
 */
export type String_41 = string;
/**
 * Aspect ratio for the generated video (default: 16:9)
 */
export type String_42 = "16:9" | "9:16" | "1:1" | "4:3" | "3:4";
/**
 * Video duration in seconds (default: 8)
 */
export type Number_7 = 4 | 5 | 6 | 7 | 8;
/**
 * Control person generation in video
 */
export type String_43 = "dont_allow" | "allow_adult";
/**
 * What to avoid in generation
 */
export type String_44 = string;

export interface GENERATE_VIDEOInput {
  prompt: String_36;
  baseImageUrl?: StringNull;
  referenceImages?: Array_9;
  firstFrameUrl?: String_40;
  lastFrameUrl?: String_41;
  aspectRatio?: String_42;
  duration?: Number_7;
  personGeneration?: String_43;
  negativePrompt?: String_44;
}
export interface Object_6 {
  url: String_38;
  referenceType?: String_39;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * URL of the generated video
 */
export type String_45 = string;
/**
 * Whether the request failed
 */
export type Boolean_1 = boolean;
/**
 * Native finish reason
 */
export type String_46 = string;
/**
 * Operation name for tracking
 */
export type String_47 = string;

export interface GENERATE_VIDEOOutput {
  video?: String_45;
  error?: Boolean_1;
  finishReason?: String_46;
  operationName?: String_47;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GET_USERInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_48 = string;
export type StringNull_1 = String_49 | Null_1;
export type String_49 = string;
export type Null_1 = null;
export type StringNull_2 = String_50 | Null_2;
export type String_50 = string;
export type Null_2 = null;
export type String_51 = string;

export interface GET_USEROutput {
  id: String_48;
  name: StringNull_1;
  avatar: StringNull_2;
  email: String_51;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  VEO3_CONTRACT: z.object({
    value: z.string(),
    __type: z
      .literal("@deco/veo3-bb8709c4fa8fe081f2cf27d8364ec254")
      .default("@deco/veo3-bb8709c4fa8fe081f2cf27d8364ec254"),
  }),
  FILE_SYSTEM: z.object({
    value: z.string(),
    __type: z.literal("@deco/file-system").default("@deco/file-system"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  VEO3_CONTRACT: Mcp<{
    /**
     * Authorize a charge for a contract clause. Creates a single authorization with transactionId.
     */
    CONTRACT_AUTHORIZE: (
      input: CONTRACT_AUTHORIZEInput,
    ) => Promise<CONTRACT_AUTHORIZEOutput>;
    /**
     * Get the current contract state.
     */
    CONTRACT_GET: (input: CONTRACT_GETInput) => Promise<CONTRACT_GETOutput>;
    /**
     * Settle the current authorized charge. Processes the payment for the current authorization.
     */
    CONTRACT_SETTLE: (
      input: CONTRACT_SETTLEInput,
    ) => Promise<CONTRACT_SETTLEOutput>;
    /**
     * Start the OAuth flow for the contract app.
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
  }>;
  FILE_SYSTEM: Mcp<{
    /**
     * Delete a file
     */
    FS_DELETE: (input: FS_DELETEInput) => Promise<FS_DELETEOutput>;
    /**
     * List files from a given bucket given a prefix
     */
    FS_LIST: (input: FS_LISTInput) => Promise<FS_LISTOutput>;
    /**
     * Get a secure temporary link to read a file
     */
    FS_READ: (input: FS_READInput) => Promise<FS_READOutput>;
    /**
     * Get metadata about a file
     */
    FS_READ_METADATA: (
      input: FS_READ_METADATAInput,
    ) => Promise<FS_READ_METADATAOutput>;
    /**
     * Get a secure temporary link to upload a file
     */
    FS_WRITE: (input: FS_WRITEInput) => Promise<FS_WRITEOutput>;
  }>;
  SELF: Mcp<{
    /**
     * OAuth for Deco Chat
     */
    DECO_CHAT_OAUTH_START: (
      input: DECO_CHAT_OAUTH_STARTInput,
    ) => Promise<DECO_CHAT_OAUTH_STARTOutput>;
    /**
     * Validate the state of the OAuth flow
     */
    DECO_CHAT_STATE_VALIDATION: (
      input: DECO_CHAT_STATE_VALIDATIONInput,
    ) => Promise<DECO_CHAT_STATE_VALIDATIONOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
    /**
     * Generate videos using Veo
     */
    GENERATE_VIDEO: (
      input: GENERATE_VIDEOInput,
    ) => Promise<GENERATE_VIDEOOutput>;
    /**
     * Get the current logged in user
     */
    GET_USER: (input: GET_USERInput) => Promise<GET_USEROutput>;
  }>;
}

export const Scopes = {
  FILE_SYSTEM: {
    FS_DELETE: "FILE_SYSTEM::FS_DELETE",
    FS_LIST: "FILE_SYSTEM::FS_LIST",
    FS_READ: "FILE_SYSTEM::FS_READ",
    FS_READ_METADATA: "FILE_SYSTEM::FS_READ_METADATA",
    FS_WRITE: "FILE_SYSTEM::FS_WRITE",
  },
  VEO3_CONTRACT: {
    CONTRACT_AUTHORIZE: "VEO3_CONTRACT::CONTRACT_AUTHORIZE",
    CONTRACT_GET: "VEO3_CONTRACT::CONTRACT_GET",
    CONTRACT_SETTLE: "VEO3_CONTRACT::CONTRACT_SETTLE",
    DECO_CHAT_OAUTH_START: "VEO3_CONTRACT::DECO_CHAT_OAUTH_START",
  },
};
